### ISSUE TITLE
Increase image size

### ISSUE THREAD

**Issue by kzxuan** [Rudrabha/Wav2Lip#1]
Hi, if I want to increase the image size, what should I do?
The default image size is 96, but I want to get a clearer face.
Do I need to redesign the network and train?

By the way, your work is excellent.

**Comment by prajwalkr** [comment]
Hi, thank you for checking out the work! Yes, you will need to re-train the network on higher resolution faces. 

We have trained on LRS2, whose face crops on average come to about 118x118. We have chosen 96, as it makes life easier while downsampling and upsampling.

**Comment by kzxuan** [comment]
Sorry for bothering.
But when I use preprocess.py to process LSR2 dataset (or my own videos), I only get a lot of black square images at pixel level (for *.jpg in the preprocessed_root).
I couldn't figure out what went wrong. Thank you for your attention.
