### ISSUE TITLE
The expert discriminator's eval loss

### ISSUE THREAD

**Issue by ShuaiYeh** [Rudrabha/Wav2Lip#101]
Thank you very much for open source for this solid work.I train on a 2080Ti and follow your README strictly.But eval loss is only 0.28 at best. May I ask if there are other skills?
The README says:
The expert discriminator's eval loss should go down to ~0.25 and the Wav2Lip eval sync loss should go down to ~0.2 to get good results.
I would be very grateful if you could answer my questions.

**Comment by prajwalkr** [comment]
> But eval loss is only 0.28 at best.

Which eval loss are you saying? The one while training the expert discriminator?

**Comment by ShuaiYeh** [comment]
the expert discriminator




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Rudrabha/Wav2Lip"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月7日(星期三) 下午5:46
收件人:&nbsp;"Rudrabha/Wav2Lip"<Wav2Lip@noreply.github.com&gt;;
抄送:&nbsp;"hey"<a1450558849@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Rudrabha/Wav2Lip] The expert discriminator's eval loss (#101)





  
But eval loss is only 0.28 at best.
  
Which eval loss are you saying? The one while training the expert discriminator?

**Comment by prajwalkr** [comment]
That is almost okay, you can use it to train Wav2Lip.
