### ISSUE TITLE
color_syncnet_train.py videocard loaded but nothing going

### ISSUE THREAD

**Issue by crankyz** [Rudrabha/Wav2Lip#102]
total trainable params 16435072
0it [00:00, ?it/s]
i see only this message, made filelists/train.txt and val.txt but i'm not sure, is there should be only jpgs without audio, and is it matter about frame order, not i have something like this:
/home/igor/Wav2Lip/l2/2/00003/0.jpg
/home/igor/Wav2Lip/l2/2/00003/1.jpg
/home/igor/Wav2Lip/l2/2/00003/10.jpg
/home/igor/Wav2Lip/l2/2/00003/100.jpg

**Comment by prajwalkr** [comment]
The file lists format is wrong. It should be:

`/home/igor/Wav2Lip/l2/2/00003/` --- a folder containing all frames of a video
`/home/igor/Wav2Lip/l2/2/00005/ --- another folder for another video
