### ISSUE TITLE
Will we have a video that teaches us how to train it on other dataset in the future and how to code this model?

### ISSUE THREAD

**Issue by JonathanSum** [Rudrabha/Wav2Lip#103]
Hi. I understand we have paper. But it is difficult to read the paper.
I think we need to have a video about how to train it on other datasets in PyTorch and how to code this model from scratch. It is important to teach how to code this model and train it from scratch because we have to know how to code it from scratch in order to fully know how to use it.

**Comment by prajwalkr** [comment]
We do not plan to make a video at this moment. I will leave this issue open for a while if someone wants to make it.

**Comment by JonathanSum** [comment]
How about an article tutorial about how to train on a video that we want?

**Comment by prajwalkr** [comment]
Actually, training on other datasets is challenging and there are several aspects involved. We will upload some instructions once we ourselves figure it out

**Comment by chuqidecha** [comment]
Could you share the high quality discriminator weights so that I can finetune the model on the other datasets ?
