### ISSUE TITLE
Regarding the License

### ISSUE THREAD

**Issue by dheerajmpai** [Rudrabha/Wav2Lip#104]
I just observed that the license for the code is changed from MIT to non-commercial/research use only. I would be really glad if I can know the reason for the same. is it because of the dataset used. Or whether the researchers want to commercialize the work themselves or some other reason. I had been training the code on a separate dataset for quite sometime considering the restrictions by LRS2. And understanding the restrictions of the License would be very helpful for me to proceed further

**Comment by Rudrabha** [comment]
At the moment, we thought it will be best to remove because our model is trained on LRS2 and should not be used for commercial purposes.

**Comment by joodykimdev** [comment]
Thanks for your great works, Rudrabha!
You mean that these non-commercial use license can be resolved by training except any non-commercial dataset?

I had concerned about the SW license problem when you added the SW license sentence in readme.md. 
-----------------
License and Citation
The software can only be used for personal/research/non-commercial purposes.
---------------
Are there any license problems in these codes, not just the problem related to the LRS2 dataset's one?
how can I resolve these non-commercial issues?

**Comment by zgxiangyang** [comment]
I am facing the same problem. Hope it to be commercially available and avoid rewriting.
