### ISSUE TITLE
Runs on cpu

### ISSUE THREAD

**Issue by Vaelek** [Rudrabha/Wav2Lip#105]
After some effort I got this to run without error under Anaconda on Windows 10. 
However, it runs inference on CPU, and thus thrashes my system to the point it is unresponsive.
I do have an nVidia card, how would I go about forcing this to use it?

**Comment by prajwalkr** [comment]
The code uses GPU by default. If your Pytorch/environment is configured to use GPU, then it'll be using GPU. Please search online for guidance to correctly configuring your environment to use GPU.
