### ISSUE TITLE
Model redesign for HD Dataset retrain

### ISSUE THREAD

**Issue by rebotnix** [Rudrabha/Wav2Lip#107]
To collect a dataset in HD is not enough to retrain a model with an HD dataset. When we change the hyparam to a higher size from 96 to 320 (for example) we get a crash in the  

x = torch.cat((x, feats[-1]), dim=1).
RuntimeError: Sizes of tensors must match except in dimension 2. Got 8 and 1 (The offending index is 0)

We still need to adjust the layers in models/wav2lib.py for accepting a higher size than 96x96. Do we have to set a Con2d for the higher resolution or do we also add Wav2Lip_disc_qual function a new one?

nn.Sequential(Conv2d(6, 16, kernel_size=7, stride=1, padding=3)), # 96,96

Anyone has started working on this so that we can use a highres model >96px?

**Comment by qustions** [comment]
@rebotnix hi yes I have tried to use hd dataset (High-resolution image size is 288x288)  for this I have to change the network input size and added few layers in wav2lip.py and train the network without lipsync. But result in lips generation were a little bit blur (better than 96 model) but the output image was at 288x288px only thing is I have trained this on my 1060 GPU dataset was very small trained it for 3 days just to confirm that change in the network size will increase the quality. Maybe If I have access to big GPUs than I can give it a try currently I don't have any gpu. But this was just a try maybe the method I chose was not correct if you want I can share the code with you or collaborate with you.

**Comment by rebotnix** [comment]
I have set up some GPU machines with 2080TI for testing and will change that soon with 3090 where we have 24GB of GPU RAM. So we can run several models on this and can share the research.

I also prepare some custom datasets, hand-selected, currently 720p around 6 hours. Of course, let´s collaborate. You can contact me at neve_capricorn[@]gmx.de.

**Comment by dipam7** [comment]
Hey @qustions, I am trying to train a high res model as well. Can you tell me what changes you made to the architecture?

**Comment by quangbang1989** [comment]
@qustions Can you share your code

**Comment by xiuyayang** [comment]
@qustions Can you share the architecture that you make changed?
Thanks so much.

**Comment by xunan0812** [comment]
@qustions  Can you share the code?  We also try to use hd dataset for High-resolution. Thanks so much.

**Comment by deepconsc** [comment]
@qustions ping me, have some compute to spare.

**Comment by stone100010** [comment]
> @rebotnix hi yes I have tried to use hd dataset (High-resolution image size is 288x288) for this I have to change the network input size and added a few layers `face_encoder_blocks` and in `face_decoder_blocks` in wav2lip.py and train the network without lipsync. But result in lips generation were a little bit blur (better than 96 model) but the output image was at 288x288px only thing is I have trained this on my 1060 GPU dataset was very small trained it for 3 days just to confirm that change in the network size will increase the quality. Maybe If I have access to big GPUs than I can give it a try currently I don't have any gpu. But this was just a try may be the method I chose was not correct if you want I can share the code with you.

你需要多少G的gpu?

**Comment by oraculseed** [comment]
> @rebotnix hi yes I have tried to use hd dataset (High-resolution image size is 288x288) for this I have to change the network input size and added a few layers `face_encoder_blocks` and in `face_decoder_blocks` in wav2lip.py and train the network without lipsync. But result in lips generation were a little bit blur (better than 96 model) but the output image was at 288x288px only thing is I have trained this on my 1060 GPU dataset was very small trained it for 3 days just to confirm that change in the network size will increase the quality. Maybe If I have access to big GPUs than I can give it a try currently I don't have any gpu. But this was just a try may be the method I chose was not correct if you want I can share the code with you.

Can you share your code. Thx.

**Comment by wowopc** [comment]
@rebotnix hi yes I have tried to use hd dataset (High-resolution image size is 288x288) for this I have to change the network input size and added a few layers and in in wav2lip.py and train the network without lipsync. But result in lips generation were a little bit blur (better than 96 model) but the output image was at 288x288px only thing is I have trained this on my 1060 GPU dataset was very small trained it for 3 days just to confirm that change in the network size will increase the quality. Maybe If I have access to big GPUs than I can give it a try currently I don't have any gpu. But this was just a try may be the method I chose was not correct if you want I can share the code with you.face_encoder_blocksface_decoder_blocks

@qustions Can you share your code. Thx.

**Comment by pgyilun** [comment]
@qustions Can you share your code. Thx.

**Comment by chjohnkim** [comment]
@qustions Hey, I'm also trying out higher resolution datasets, would you be able to share your code with me?

**Comment by qustions** [comment]
Hey Sorry I don't have much time to work on this project if you like to collaborate on this you can contact me on telegram https://t.me/wav2lip I will share the code there.

**Comment by Nyquist0** [comment]
Hi @qustions .
May I know what is the name of your dataset? Are you using AVSpeech or a private one?
