### ISSUE TITLE
Some Training Results

### ISSUE THREAD

**Issue by rebotnix** [Rudrabha/Wav2Lip#108]
This is not an issue, just want to share some progress during retraining an (old 96px) model. 

Steps <1000
![4_4](https://user-images.githubusercontent.com/566761/95675101-e8a3cd80-0bb4-11eb-843c-eb11e70cc626.jpg)

Steps 3000
![4_1](https://user-images.githubusercontent.com/566761/95675152-518b4580-0bb5-11eb-80cb-f3ff6ec048d1.jpg)

Steps 6000
![2_1](https://user-images.githubusercontent.com/566761/95675116-fce7ca80-0bb4-11eb-95d8-a1249a4d115c.jpg)

Very interesting that the 3000 checkpoint has good results on train data, but the >6000 seems to go wrong, and maybe it´s overtrained with too little data. I have now tested with a 2 hours dataset to understand how much data we need for good retraining of a custom model.

Let me know your thoughts.

**Comment by quangbang1989** [comment]
why you dont share your model and we can test it. thx

**Comment by dipam7** [comment]
Are these results generated from the inference script after training your model? Or is this evaluation during training?

**Comment by rebotnix** [comment]
> Are these results generated from the inference script after training your model? Or is this evaluation during training?

Evaluation during training.

**Comment by mrlihellohorld** [comment]
How many people are in the two hour video？
