### ISSUE TITLE
video quality differ from the demo page and this github 

### ISSUE THREAD

**Issue by jays0606** [Rudrabha/Wav2Lip#11]
Hello, first I am amazed by this marvelous work. I appreciate your effort for building such a great project. 

I have one question though. 
I generated a video using your demo page (https://bhaasha.iiit.ac.in/lipsync/), and generated a video using the same video/audio in using this github page, and I found the quality in the demo page was much superior. 

Is this an issue regarding some parameters or the checkpoint? 

Thank you very much

**Comment by prajwalkr** [comment]
The demo page produces low-resolution videos. We suggest you to use `--resize_factor` to reduce the resolution of your input video to around 480p as our model will work better on low-resolution video inputs.

**Comment by jays0606** [comment]
The video resolution was already pretty low. I've tried with 256x256, but the results happened to be different, so I was wondering if there are any differences between the demo and this code? 
Are the parameters in the demo page the same as the ones set as 'default' in inference.py? (And the checkpoint?)

**Comment by hav4ik** [comment]
Are the weights (Wav2Lip and Wav2Lip + GAN) linked in the README the same as the ones that you used to produce those stunning video demos?

**Comment by prajwalkr** [comment]
The demo uses Wav2Lip + GAN and it is exactly the same as the one released in this repo as well.

**Comment by prajwalkr** [comment]
Re-open if required.

**Comment by jays0606** [comment]
Thank you for your quick reply. I re-checked the result, and there seemed to have been a problem in the face detection part. All set. Thank you!

**Comment by leijue222** [comment]
> 演示页面会生成低分辨率视频。我们建议您将`--resize_factor`输入视频的分辨率降低到480p左右，因为我们的模型在低分辨率视频输入上会更好地工作。

Hi, if I add --resize_factor 480. Then I got "Face not detected!"
What caused the problem？
