### ISSUE TITLE
OOM Error / Uses CPU instead of GPU although GPU is recognized 

### ISSUE THREAD

**Issue by emran313** [Rudrabha/Wav2Lip#112]
Hi
Thanks for the great repo and demo you have created. Way to go!

I'm using Anaconda to manage my environments. I created a wavtolip environment, installed required packages, checked to see if gpu is recognized. Also resolved issues regarding the installation and use of tensorflow and torch.
Now that it finally runs, I get OOM error. And it says:

Using cpu for inference.
Reading video frames...
Traceback (most recent call last):
  File "inference.py", line 279, in <module>
    main()
  File "inference.py", line 196, in main
    still_reading, frame = video_stream.read()
cv2.error: OpenCV(4.4.0) ..\modules\core\src\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 6220800 bytes in function 'cv::OutOfMemoryError'

I have a NVIDIA GeForce GTX 970 graphics card along with a core i5-6400 CPU and 16 GB my memory. I'm on Windows 10.

Any guidance and help is much appreciated.

Cheers,
Emran

**Comment by prajwalkr** [comment]
What is your video resolution? How long is your video that you are reading?

**Comment by emran313** [comment]
Thanks for your quick reply.
Do you think not working with GPU is due to video resolution or duration? It would be strange!
It's a 1920x1080 video, 4.5 minutes long. 
Thanks again for your help.

**Comment by prajwalkr** [comment]
OpenCV loads the video in your RAM (not GPU). You need to chunk the video into smaller segments or reduce the resolution.

**Comment by emran313** [comment]
Many thanks @prajwalkr
