### ISSUE TITLE
Bad tooth ! Bad tooth

### ISSUE THREAD

**Issue by anthonyyuan** [Rudrabha/Wav2Lip#114]
When i use model  wav2lip_gan.pth ,but got bad tooth
![11](https://user-images.githubusercontent.com/3069415/96866816-74173b80-149e-11eb-982f-8af073f27f59.jpg)

**Comment by prajwalkr** [comment]
Generating accurate teeth is still a known challenge for arbitrary speakers in the wild. We hope to resolve this in future work.
