### ISSUE TITLE
How would I speed up video creation?

### ISSUE THREAD

**Issue by TechGenius28** [Rudrabha/Wav2Lip#117]
Currently, most videos take around 2 hours to process. Is there anything I can do to speed it up?

**Comment by prajwalkr** [comment]
How long are your videos?

**Comment by TechGenius28** [comment]
> How long are your videos? 

Most of the videos created are about 1 minute long with a video input that is usually 30 seconds long.

**Comment by prajwalkr** [comment]
Please ensure the code is using a GPU. The code should not take more than a few minutes for a 30-second video input.
