### ISSUE TITLE
Is the  performance of lip generation related to the quality of input video?

### ISSUE THREAD

**Issue by cenalzw** [Rudrabha/Wav2Lip#119]
Thanks a lot for your sharing, man. I have a few doubts about this work. 

To predict the lip-sync image, we need to input both the entire face frames and the masked frames into the GAN. Are the accuracy of generated lips related to the quality of the original input images (such as their head poses, face expressions, resolutions)? The reason I ask this question is because that I tried to open the 'static' item when running your 'inference.py' and saw a little bit improvement compared with using the whole video.  I guess the improvement is from using the face image with neutral pose. 

Look forward to getting your help, have a good luck in your life.

**Comment by prajwalkr** [comment]
> generated lips related to the quality of the original input images (such as their head poses, face expressions, resolutions)?

Yes, the model is more accurate in morphing certain poses and reference lip shapes. For instance, it is more accurate for frontal poses compared to side (profile) view faces.
