### ISSUE TITLE
How much more training do we have to train with the new dataset?

### ISSUE THREAD

**Issue by scpark20** [Rudrabha/Wav2Lip#12]
Thank you for providing a really easy to understand and neat code. 
Using the model save file you provided, we are applying it to the video file we have, 
but some videos do not produce the desired quality. 
So, we are doing a warm start from the save file you provided, 
and training using our additional dataset and LRS2. 
Can you give me any tips on how much more training we need to do? 
I'll wait for your answer.

**Comment by prajwalkr** [comment]
If you are using the sync loss, the evaluation sync loss must come to about 0.19-0.20 or below and should not improve for about 10 epochs when training on LRS2

**Comment by scpark20** [comment]
Thanks for the quick reply!
