### ISSUE TITLE
Quantization/Optimization of the model to improve speed on CPU

### ISSUE THREAD

**Issue by MarlNox** [Rudrabha/Wav2Lip#120]
Hi there, 
I've been trying to quantize the model to no success. I seem to run into issues when trying to convert the .pth file into jit. Has anyone had experiences in converting the model to torchscript Jit?. 
I've also tried using ONNX for the conversion, quantization and optimization; I created a new inference file to use the ONNX model but I keep getting an error message referencing that the input should be 125, but is 128 - even though the model was just converted to ONNX, and a review with Netron reveals that the structure of the model has been unchanged. 
Thanks, 

EDIT for clarification: 
`
Current error in ONNX inference: 
Traceback (most recent call last):
  File "onnx-inference.py", line 288, in <module>
    main()
  File "onnx-inference.py", line 271, in main
    session.get_inputs()[1].name: img_batch.cpu().detach().numpy()
  File "/home/marlind/anaconda3/envs/tensori/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 123, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: 1 for the following indices
 index: 0 Got: 128 Expected: 125
 Please fix either the inputs or the model.
`

**Comment by prajwalkr** [comment]
We do not have any experience with this. I will leave this issue open for some time so that people who know about this can help you.

**Comment by MarlNox** [comment]
> We do not have any experience with this. I will leave this issue open for some time so that people who know about this can help you.
Thanks for the reply. 
One last question: Any idea why the model would have issues being converted to torch script?

**Comment by prajwalkr** [comment]
> Any idea why the model would have issues being converted to torch script?

No, I have no idea why.

**Comment by ShivamSRS** [comment]
@MarlNox Can you please post somewhere the code you have tried to run? I wanted to have a look

**Comment by prajwalkr** [comment]
Re-open if required.

**Comment by michaelbuddy** [comment]
@MarlNox Any update for this? You have fixed the issue?

**Comment by MarlNox** [comment]
> @MarlNox Any update for this? You have fixed the issue?

Nope, I have come to understand that the fragmentation of the models may have something to do with it, but I haven't found a way around it. Whomever does should post it.

**Comment by anesum99** [comment]
Hi, could you please share how you converted to onnx? I'm having trouble doing so. Thank you

**Comment by aniketzz** [comment]
I am able to convert to ONNX but unable to infer using the ONNX.

here is the torch2onnx code:
```
import torch
import torch.onnx
from models import Wav2Lip

model = Wav2Lip()
checkpoint_path = "checkpoints/wav2lip.pth"
modelz = torch.load(checkpoint_path)

# device = 'cuda' if torch.cuda.is_available() else 'cpu'
device="cuda"
s = modelz["state_dict"]
new_s = {}
for k, v in s.items():
    new_s[k.replace('module.', '')] = v


model.load_state_dict(new_s)
model = model.to(device)

model.eval()
# print(model.eval())
input_shape1 = [(8, 1, 80, 16)]
input_shape2 = [(8, 6, 96, 96)]


torch.onnx.export(model,
                  (torch.randn(input_shape1).cuda(), torch.randn(input_shape2).cuda()),
                  "checkpoints/wav2lip.onnx",
                  input_names=["mel_spectrogram", "video_frames"],
                  output_names=["predicted_frames"],
                  verbose=True)
print("Done !!")
```

I am not sure about the input names though. I tried to infer and got following error.
```
Traceback (most recent call last):
  File "wav2lip_onnx.py", line 283, in <module>
    main()
  File "wav2lip_onnx.py", line 265, in main
    pred = ort_session.run(None, input_feed)
  File "/home/tg-30/.local/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 188, in run
    return self._sess.run(output_names, input_feed, run_options)
TypeError: run(): incompatible function arguments. The following argument types are supported:
    1. (self: onnxruntime.capi.onnxruntime_pybind11_state.InferenceSession, arg0: List[str], arg1: Dict[str, object], arg2: onnxruntime.capi.onnxruntime_pybind11_state.RunOptions) -> List[object]
```

**Comment by instant-high** [comment]
Hi,
above code doesn't work for me.
Found another one, working so far, here:
https://github.com/tpulkit/txt2vid_browser

But inference also does not work, nearly same errormsg.

Filesize of converted wav2lip.onnx is 145.327.310 Bytes ?

**Comment by maxwelhelp** [comment]
wav2lip_GAN2_quantized.onnx (size 76 mb) [https://drive.google.com/file/d/1rStWNOmqrgSVFsBkWouteGi1t9DqiKaq/view](url)

Her is cod for quantize the model and convert from pth to onnx

`import torch
import torch.onnx
import onnxruntime
import numpy as np
from models import Wav2Lip
import time
from onnxruntime.quantization import quantize_dynamic, QuantType

export_onnx_model = "checkpoints/Wav2Lip_GAN2.pth"

def export_to_onnx():
    model = Wav2Lip()
    checkpoint_path = export_onnx_model
    modelz = torch.load(checkpoint_path, map_location='cpu')

    device = 'cuda' if torch.cuda.is_available() else 'cpu'
    s = modelz["state_dict"]
    new_s = {k.replace('module.', ''): v for k, v in s.items()}

    model.load_state_dict(new_s)
    model = model.to(device)
    model.eval()

    # Определение входных форм
    mel_input = torch.randn(8, 1, 80, 16).to(device)
    frame_input = torch.randn(8, 6, 96, 96).to(device)

    # Экспорт модели в ONNX
    torch.onnx.export(model,
                      (mel_input, frame_input),
                      "checkpoints/wav2lip_GAN2.onnx",
                      input_names=["mel_spectrogram", "video_frames"],
                      output_names=["predicted_frames"],
                      dynamic_axes={'mel_spectrogram': {0: 'batch_size'},
                                    'video_frames': {0: 'batch_size'},
                                    'predicted_frames': {0: 'batch_size'}},
                      do_constant_folding=True,
                      opset_version=13,
                      verbose=True)

    print("ONNX модель успешно экспортирована!")

    # Проверка точности
    ort_session = onnxruntime.InferenceSession("checkpoints/wav2lip_GAN2.onnx",
                                               providers=['CUDAExecutionProvider', 'CPUExecutionProvider'])
    ort_inputs = {
        "mel_spectrogram": mel_input.cpu().numpy(),
        "video_frames": frame_input.cpu().numpy()
    }
    ort_output = ort_session.run(None, ort_inputs)[0]
    pytorch_output = model(mel_input, frame_input).detach().cpu().numpy()
    np.testing.assert_allclose(pytorch_output, ort_output, rtol=1e-03, atol=1e-05)
    print("Проверка точности прошла успешно!")

    # Динамическая квантизация ONNX модели
    quantized_model_path = "checkpoints/wav2lip_GAN2_quantized.onnx"
    quantize_dynamic("checkpoints/wav2lip_GAN2.onnx", quantized_model_path, weight_type=QuantType.QUInt8)
    print("Динамически квантованная ONNX модель сохранена!")

def onnx_inference():
    # Загрузка квантованной ONNX модели
    ort_session = onnxruntime.InferenceSession("checkpoints/wav2lip_GAN2_quantized.onnx",
                                               providers=['CUDAExecutionProvider', 'CPUExecutionProvider'])

    # Вывод информации о входных данных
    print("Входные данные модели:")
    for input in ort_session.get_inputs():
        print(f"Имя: {input.name}, Форма: {input.shape}, Тип: {input.type}")

    # Подготовка входных данных
    mel_input = np.random.randn(8, 1, 80, 16).astype(np.float32)
    frame_input = np.random.randn(8, 6, 96, 96).astype(np.float32)

    # Создание словаря входных данных
    input_feed = {
        "mel_spectrogram": mel_input,
        "video_frames": frame_input
    }

    # Прогрев
    _ = ort_session.run(None, input_feed)

    # Замер времени выполнения ONNX
    start_time = time.time()
    output = ort_session.run(None, input_feed)
    end_time = time.time()

    print("Форма выходных данных ONNX:", output[0].shape)
    print(f"Время выполнения ONNX: {end_time - start_time:.4f} секунд")

    # Сравнение с PyTorch
    model = Wav2Lip()
    checkpoint_path = export_onnx_model
    modelz = torch.load(checkpoint_path, map_location='cuda')
    s = modelz["state_dict"]
    new_s = {k.replace('module.', ''): v for k, v in s.items()}
    model.load_state_dict(new_s)
    model = model.to('cuda').eval()

    mel_input_torch = torch.from_numpy(mel_input).to('cuda')
    frame_input_torch = torch.from_numpy(frame_input).to('cuda')

    # Замер времени выполнения PyTorch
    start_time = time.time()
    with torch.no_grad():
        output_torch = model(mel_input_torch, frame_input_torch)
    end_time = time.time()

    print("Форма выходных данных PyTorch:", output_torch.shape)
    print(f"Время выполнения PyTorch: {end_time - start_time:.4f} секунд")

def main():
    export_to_onnx()
    onnx_inference()

if __name__ == "__main__":
    main()`
