### ISSUE TITLE
Issues with requirements and Python3.5.2

### ISSUE THREAD

**Issue by aroraprince** [Rudrabha/Wav2Lip#121]
When trying to install requirements using 
`pip3 install -r requirements.txt`

I am getting the following errors:
`ERROR: Could not find a version that satisfies the requirement opencv-python==4.1.0.25 (from -r requirements.txt (line 4)) (from versions: 3.4.8.29, 3.4.9.31, 3.4.9.33, 3.4.10.35, 3.4.10.37, 3.4.11.39, 3.4.11.41, 3.4.11.43, 4.1.2.30, 4.2.0.32, 4.2.0.34, 4.3.0.36, 4.3.0.38, 4.4.0.40, 4.4.0.42, 4.4.0.44)
ERROR: No matching distribution found for opencv-python==4.1.0.25 (from -r requirements.txt (line 4))`

and

`ERROR: Could not find a version that satisfies the requirement tensorflow==1.12.0 (from -r requirements.txt (line 5)) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1)
ERROR: No matching distribution found for tensorflow==1.12.0 (from -r requirements.txt (line 5))`

Are there any compatible versions to use?

**Comment by prajwalkr** [comment]
If you use a Python version 3.6+ do you get the same errors?

**Comment by aroraprince** [comment]
I am able to install dependencies using Python==3.6.9.
This means the documentation needs to be updated where it says the code works with Python3.5.2.

Let me know if I can take this up.

**Comment by prajwalkr** [comment]
> Let me know if I can take this up.

Sure, go ahead. I will close this issue now.
