### ISSUE TITLE
Expert training conditions 

### ISSUE THREAD

**Issue by BertyWooster** [Rudrabha/Wav2Lip#122]
Thank you for the great work!
I am going to additionally train the expert discriminator on my data. Can you please help me with several questions about your training conditions?

If I correct, there were about 2448 epochs in your expert training procedure. The number of video samples in your data was about 46000 and the batch size was 64.

The questions are:
How long does this process take?
What kind of hardware did you use?
Is there the actual hparams.py file on GitHub?

**Comment by prajwalkr** [comment]
> How long does this process take? What kind of hardware did you use?

~2-3 days on a single NVIDIA 2080Ti GPU. 

> The number of video samples in your data was about 46000 and the batch size was 64

Yes.

> If I correct, there were about 2448 epochs in your expert training procedure.

Around 700K steps are necessary for LRS2. 

Is there the actual hparams.py file on GitHub?

Yes.

**Comment by BertyWooster** [comment]
Thank you very much! And one more short question please:
The number of steps is the total number of optimizer gradient steps (with batch_size=64), am I right?

**Comment by prajwalkr** [comment]
> The number of steps is the total number of optimizer gradient steps (with batch_size=64), am I right?

Yes

**Comment by BertyWooster** [comment]
Thank you!! ^^)
