### ISSUE TITLE
Evaluation: Not gettting metrics for some videos

### ISSUE THREAD

**Issue by avisekiit** [Rudrabha/Wav2Lip#125]
Dear Authors,

I could run your evaluation framework and got the offset and confidence scores on some videos. However, the code does not return any value for some videos.
The below video is a typical example on which I am failing to get any metrics.

https://drive.google.com/file/d/1t4BLBeFoSgM37A6Z9UpssKcY0bw7XyWg/view?usp=sharing

Do you have any idea regarding this and if you have any guidance to tweak the inference code somehow to get the metrics on the above video.

Thanks,
Avisek

**Comment by avisekiit** [comment]
Dear Authors,
Keenly looking forward to your thoughts on why the evaluation script does not return the metrics for videos such as mentioned above. Any insights will be really helpful.

Thanks,
Avisek

**Comment by Rudrabha** [comment]
Are you using the code for real videos? Incase you are not getting any output then, it is probably because the face is not detected or something.

**Comment by avisekiit** [comment]
@Rudrabha 
Yes, I am using the same code for all videos. However, only for few videos such as one above, I am not getting any metrics.
I doubt whether the face detection is failing in such a simple video as above ?

If somehow you get time, will it be kindly possible for you to try to get the metrics for the above video. You might be able to catch the cause sooner than me :p 

Thanks,
Avisek

**Comment by avisekiit** [comment]
Yeah, Ok I understand. Best wishes for the CVPR submission !!!

**Comment by Rudrabha** [comment]
Hello, I checked these and it seems to be an issue with the syncnet_python code. You can try out this [repository](https://github.com/joonson/syncnet_python) directly. If the code does not give you an output then you can open an issue in the same repo. I think they will be able to guide you better.
