### ISSUE TITLE
About audio parameters settings

### ISSUE THREAD

**Issue by QUTGXX** [Rudrabha/Wav2Lip#127]
Hi, I saw some parameters in your 'hparams.py', including min_level_db, ref_level_db, fmin and fmax. You said that we should increase or decrease the value based on the dataset. I want to train my dataset using your model. Could you please tell me how to examine these parameters?

**Comment by prajwalkr** [comment]
Hello, these are parameters borrowed from a multi-speaker TTS model: https://github.com/r9y9/deepvoice3_pytorch. I think you will be able to get a better answer if you raise an issue there.

**Comment by QUTGXX** [comment]
> ese are parameters borrowed from a multi-speaker TTS model

Thanks for your reply, I saw you changed the value of 'fmin' from 125 to 55.  Could you plz tell me how to test the pitch information on your LRS2 Dataset?

**Comment by prajwalkr** [comment]
You can vary that parameter and train as required. No other change would be necessary
