### ISSUE TITLE
expert discriminator using less gpu

### ISSUE THREAD

**Issue by qustions** [Rudrabha/Wav2Lip#128]
hi, @prajwalkr expert discriminator is using 2gb GPU on default code with batch size 64 on lrs dataset is it normal. I even increase the batch size to 512 that it's using 10gb anything I am doing wrong?

**Comment by prajwalkr** [comment]
> is using 2gb GPU on default code with batch size 64 on lrs dataset is it normal.

Yes. 

> I even increase the batch size to 512 that it's using 10gb anything I am doing wrong?

We have not tried this, so we really cannot say for sure.
