### ISSUE TITLE
Mel spectrogram vs mfcc

### ISSUE THREAD

**Issue by KAISER1997** [Rudrabha/Wav2Lip#129]
Hi @prajwalkr I had a small query ,In your previous paper LipGAN you used mfcc here you are using mel spectrogram. Could you give some insights about which feature works better?

**Comment by prajwalkr** [comment]
In our experience, both work roughly the same way. We used Mel spectrograms here, as we had used it in other recent projects such as this one: https://github.com/Rudrabha/Lip2Wav/

No particular advantage of one over the other was observed in our experiments.
