### ISSUE TITLE
use other dataset

### ISSUE THREAD

**Issue by stone100010** [Rudrabha/Wav2Lip#133]
Hello, it's a bit troublesome to download LRS2 dataset. Would you please explain the characteristics of LRS2 dataset? Actually, I want to use CMLR dataset, do I need to go through a lot of trouble?

**Comment by prajwalkr** [comment]
It is very hard to comment on a different dataset. We use the train set of LRS2 and its characteristics are mentioned here: http://www.robots.ox.ac.uk/~vgg/data/lip_reading/lrs2.html

Make sure your dataset contains a large number of speakers (hundreds to thousands) and not limited by vocabulary (several thousands of unique words)
