### ISSUE TITLE
Colab Notebook errors 

### ISSUE THREAD

**Issue by leonardog27** [Rudrabha/Wav2Lip#134]
Dear friends, 
The following errors appears when I was trying to run the Colab Notebook

error 1 at code: !cp -ri "/content/gdrive/My Drive/Wav2lip/wav2lip_gan.pth" /content/Wav2Lip/checkpoints/

cp: cannot stat '/content/gdrive/My Drive/Wav2lip/wav2lip_gan.pth': No such file or directory

error 2 at !cd Wav2Lip && python inference.py --checkpoint_path checkpoints/wav2lip_gan.pth --face "../sample_data/input_vid.mp4" --audio "../sample_data/input_audio.wav"

FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/wav2lip_gan.pth'

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Using cuda for inference.
Reading video frames...
Number of frames available for inference: 675
(80, 2161)
Length of mel chunks: 672
  0% 0/6 [00:00<?, ?it/s]
  0% 0/42 [00:00<?, ?it/s]
  2% 1/42 [00:03<02:31,  3.69s/it]
  5% 2/42 [00:04<01:50,  2.76s/it]
  7% 3/42 [00:04<01:21,  2.10s/it]
 10% 4/42 [00:05<01:02,  1.64s/it]
 12% 5/42 [00:05<00:48,  1.31s/it]
 14% 6/42 [00:06<00:38,  1.08s/it]
 17% 7/42 [00:07<00:32,  1.08it/s]
 19% 8/42 [00:07<00:27,  1.23it/s]
 21% 9/42 [00:08<00:24,  1.33it/s]
 24% 10/42 [00:08<00:22,  1.39it/s]
 26% 11/42 [00:09<00:21,  1.45it/s]
 29% 12/42 [00:10<00:19,  1.53it/s]
 31% 13/42 [00:10<00:18,  1.60it/s]
 33% 14/42 [00:11<00:17,  1.64it/s]
 36% 15/42 [00:11<00:15,  1.69it/s]
 38% 16/42 [00:12<00:15,  1.71it/s]
 40% 17/42 [00:12<00:14,  1.74it/s]
 43% 18/42 [00:13<00:13,  1.75it/s]
 45% 19/42 [00:13<00:13,  1.75it/s]
 48% 20/42 [00:14<00:12,  1.76it/s]
 50% 21/42 [00:15<00:12,  1.74it/s]
 52% 22/42 [00:15<00:11,  1.76it/s]
 55% 23/42 [00:16<00:10,  1.75it/s]
 57% 24/42 [00:16<00:10,  1.73it/s]
 60% 25/42 [00:17<00:10,  1.70it/s]
 62% 26/42 [00:18<00:09,  1.67it/s]
 64% 27/42 [00:18<00:09,  1.65it/s]
 67% 28/42 [00:19<00:08,  1.62it/s]
 69% 29/42 [00:19<00:07,  1.63it/s]
 71% 30/42 [00:20<00:07,  1.65it/s]
 74% 31/42 [00:21<00:06,  1.66it/s]
 76% 32/42 [00:21<00:05,  1.67it/s]
 79% 33/42 [00:22<00:05,  1.69it/s]
 81% 34/42 [00:22<00:04,  1.71it/s]
 83% 35/42 [00:23<00:04,  1.72it/s]
 86% 36/42 [00:24<00:03,  1.71it/s]
 88% 37/42 [00:24<00:02,  1.73it/s]
 90% 38/42 [00:25<00:02,  1.74it/s]
 93% 39/42 [00:25<00:01,  1.77it/s]
 95% 40/42 [00:26<00:01,  1.75it/s]
 98% 41/42 [00:26<00:00,  1.76it/s]
100% 42/42 [00:27<00:00,  1.53it/s]
Load checkpoint from: checkpoints/wav2lip_gan.pth
  0% 0/6 [00:32<?, ?it/s]
Traceback (most recent call last):
  File "inference.py", line 279, in <module>
    main()
  File "inference.py", line 251, in main
    model = load_model(args.checkpoint_path)
  File "inference.py", line 170, in load_model
    checkpoint = _load(path)
  File "inference.py", line 161, in _load
    checkpoint = torch.load(checkpoint_path)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 382, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/wav2lip_gan.pth'

**Comment by prajwalkr** [comment]
See if this tutorial helps you: https://www.youtube.com/watch?v=Ic0TBhfuOrA

**Comment by leonardog27** [comment]
In this second experiment I tried to do a 75 seconds video and audio but the following error appears

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Using cpu for inference.
Reading video frames...
Number of frames available for inference: 2250
(80, 6001)
Length of mel chunks: 2246
  0% 0/18 [00:00<?, ?it/s]
  0% 0/141 [00:00<?, ?it/s]tcmalloc: large alloc 2415919104 bytes == 0x118208000 @  0x7f26e8bfcb6b 0x7f26e8c1c379 0x7f265f072e4e 0x7f265f074dca 0x7f265fcb8d62 0x7f265fdd6b1b 0x7f265fd7bceb 0x7f265ff8a300 0x7f265dbfe26c 0x7f265fb63469 0x7f265ff8fe1e 0x7f265dd8e166 0x7f265fb5bd29 0x7f265ff8ff07 0x7f265dd91222 0x7f265fb5b9fa 0x7f265ff8f9b0 0x7f265dfabdf4 0x7f269e4df042 0x50a4a5 0x50beb4 0x508cd5 0x594a01 0x59fd0e 0x50d256 0x507be4 0x508ec2 0x594a01 0x54a971 0x5a9dac 0x50a433
tcmalloc: large alloc 2415919104 bytes == 0x1a8aec000 @  0x7f26e8bfcb6b 0x7f26e8c1c379 0x7f265fd81734 0x7f265fd7cccb 0x7f265ff8a300 0x7f265dbfe26c 0x7f265fb63469 0x7f265ff8fe1e 0x7f265dd8e166 0x7f265fb5bd29 0x7f265ff8ff07 0x7f265dd91222 0x7f265fb5b9fa 0x7f265ff8f9b0 0x7f265dfabdf4 0x7f269e4df042 0x50a4a5 0x50beb4 0x508cd5 0x594a01 0x59fd0e 0x50d256 0x507be4 0x508ec2 0x594a01 0x54a971 0x5a9dac 0x50a433 0x50beb4 0x508cd5 0x594a01
tcmalloc: large alloc 2415919104 bytes == 0x1a8aec000 @  0x7f26e8bfcb6b 0x7f26e8c1c379 0x7f265f072e4e 0x7f265f074dca 0x7f2660020d46 0x7f265fcb93f9 0x7f265fdac1fc 0x7f265fcc3ff6 0x7f265fcc4678 0x7f265fcc54cf 0x7f265fb23d99 0x7f265fb2460d 0x7f265ff8583d 0x7f265fb2280f 0x7f265fe24812 0x7f265dbf232d 0x7f269e479d6b 0x50a4a5 0x50beb4 0x507be4 0x509900 0x50a2fd 0x50beb4 0x508cd5 0x594a01 0x59fd0e 0x50d256 0x507be4 0x508ec2 0x594a01 0x54a971
tcmalloc: large alloc 2415919104 bytes == 0x118208000 @  0x7f26e8bfcb6b 0x7f26e8c1c379 0x7f265f072e4e 0x7f265f074dca 0x7f265fcb8d62 0x7f265fdd6b1b 0x7f265fd7bceb 0x7f265ff8a300 0x7f265dbfe26c 0x7f265fb63469 0x7f265ff8fe1e 0x7f265dd8e166 0x7f265fb5bd29 0x7f265ff8ff07 0x7f265dd91222 0x7f265fb5b9fa 0x7f265ff8f9b0 0x7f265dfabdf4 0x7f269e4df042 0x50a4a5 0x50beb4 0x508cd5 0x594a01 0x59fd0e 0x50d256 0x507be4 0x508ec2 0x594a01 0x54a971 0x5a9dac 0x50a433
tcmalloc: large alloc 2415919104 bytes == 0x238aec000 @  0x7f26e8bfcb6b 0x7f26e8c1c379 0x7f265fd81734 0x7f265fd7cc23 0x7f265ff8a300 0x7f265dbfe26c 0x7f265fb63469 0x7f265ff8fe1e 0x7f265dd8e166 0x7f265fb5bd29 0x7f265ff8ff07 0x7f265dd91222 0x7f265fb5b9fa 0x7f265ff8f9b0 0x7f265dfabdf4 0x7f269e4df042 0x50a4a5 0x50beb4 0x508cd5 0x594a01 0x59fd0e 0x50d256 0x507be4 0x508ec2 0x594a01 0x54a971 0x5a9dac 0x50a433 0x50beb4 0x508cd5 0x594a01
tcmalloc: large alloc 2415919104 bytes == 0x2c8aec000 @  0x7f26e8bfcb6b 0x7f26e8c1c379 0x7f265fd81734 0x7f265fd7cccb 0x7f265ff8a300 0x7f265dbfe26c 0x7f265fb63469 0x7f265ff8fe1e 0x7f265dd8e166 0x7f265fb5bd29 0x7f265ff8ff07 0x7f265dd91222 0x7f265fb5b9fa 0x7f265ff8f9b0 0x7f265dfabdf4 0x7f269e4df042 0x50a4a5 0x50beb4 0x508cd5 0x594a01 0x59fd0e 0x50d256 0x507be4 0x508ec2 0x594a01 0x54a971 0x5a9dac 0x50a433 0x50beb4 0x508cd5 0x594a01
^C

**Comment by prajwalkr** [comment]
Please try a shorter sample (5-10 seconds) to start with. You can try longer segments after that. Use a lower batch size if your resolution is high.

**Comment by leonardog27** [comment]
> Please try a shorter sample (5-10 seconds) to start with. You can try longer segments after that. Use a lower batch size if your resolution is high.

Dear prajwalkr; I perform the generative model with lower resolution option. the following is the result
[https://www.youtube.com/watch?v=3H-e5xg0DLM](url)
Audio is a OpenAI Jukebox song, I used another AI to separate the vocals only to use that file with the video, Finally I mixed again with the music.
Thank you very much!

**Comment by prajwalkr** [comment]
Great! :+1:

**Comment by nikilteja215** [comment]
Using cuda for inference.
Reading video frames...
Number of frames available for inference: 210
Traceback (most recent call last):
  File "/content/Wav2Lip/inference.py", line 280, in <module>
    main()
  File "/content/Wav2Lip/inference.py", line 225, in main
    mel = audio.melspectrogram(wav)
  File "/content/Wav2Lip/audio.py", line 47, in melspectrogram
    S = _amp_to_db(_linear_to_mel(np.abs(D))) - hp.ref_level_db
  File "/content/Wav2Lip/audio.py", line 95, in _linear_to_mel
    _mel_basis = _build_mel_basis()
  File "/content/Wav2Lip/audio.py", line 100, in _build_mel_basis
    return librosa.filters.mel(hp.sample_rate, hp.n_fft, n_mels=hp.num_mels,
TypeError: mel() takes 0 positional arguments but 2 positional arguments (and 3 keyword-only arguments) were given

I'm getting this error, what am i supposed to do to rectify that?

**Comment by isabellahoch** [comment]
> Using cuda for inference. Reading video frames... Number of frames available for inference: 210 Traceback (most recent call last): File "/content/Wav2Lip/inference.py", line 280, in main() File "/content/Wav2Lip/inference.py", line 225, in main mel = audio.melspectrogram(wav) File "/content/Wav2Lip/audio.py", line 47, in melspectrogram S = _amp_to_db(_linear_to_mel(np.abs(D))) - hp.ref_level_db File "/content/Wav2Lip/audio.py", line 95, in _linear_to_mel _mel_basis = _build_mel_basis() File "/content/Wav2Lip/audio.py", line 100, in _build_mel_basis return librosa.filters.mel(hp.sample_rate, hp.n_fft, n_mels=hp.num_mels, TypeError: mel() takes 0 positional arguments but 2 positional arguments (and 3 keyword-only arguments) were given
> 
> I'm getting this error, what am i supposed to do to rectify that?

Hi @nikilteja215 try downgrading the librosa version and see if that fixes it:

`!pip install "librosa==0.9.1"`
