### ISSUE TITLE
Demo page result unrelated to input

### ISSUE THREAD

**Issue by ANDALACA** [Rudrabha/Wav2Lip#135]
Whenever I provide video and audio to sync on your demo page (tried several), the output is totally unrelated, often playing a russian hip hop audio track over Elon Musk or Boris Johnson video. Is this intended if the algorithm doesn't sync successfully, or? There are no error messages related to the input/output, as far as I can see?

**Comment by prajwalkr** [comment]
I just tried it again, and it seems to be working just fine. Can you rename your file to something else, and try in an incognito tab?
