### ISSUE TITLE
requirements.txt again - YES I have 3.6 :)

### ISSUE THREAD

**Issue by fred-aghq** [Rudrabha/Wav2Lip#137]
Hi folks,

**As far as  I can tell, I'm definitely using python 3.6.x! **

I've read through the closed issues related to requirements.txt and cannot seem to come up with a solution at this time.

I'm on windows - using miniconda to change my python environment to 3.6.9

`conda install --file requirements.txt` doesn't work as conda cant seem to find the versions detailed in requirements.txt:

```
PackagesNotFoundError: The following packages are not available from current channels:

  - opencv-python==4.1.0.25
  - librosa==0.7.0
  - torch==1.1.0
  - torchvision==0.3.0
  - numpy==1.17.1
  - opencv-contrib-python==4.2.0.34

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

Fair enough, I dont think this is what conda is intended for.

`pip install -r requirements.txt` fails on the following:

```
ERROR: Could not find a version that satisfies the requirement torch==1.1.0 (from -r requirements.txt (line 6)) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.1.0 (from -r requirements.txt (line 6))
```

I try changing torch to 0.1.2 and it fails on 

```
Collecting torch==0.1.2
  Using cached torch-0.1.2.tar.gz (294 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\freds\miniconda3\envs\3.6.9\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\freds\\AppData\\Local\\Temp\\pip-install-ufih0e9j\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\freds\\AppData\\Local\\Temp\\pip-install-ufih0e9j\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\freds\AppData\Local\Temp\pip-pip-egg-info-muzese2x'
         cwd: C:\Users\freds\AppData\Local\Temp\pip-install-ufih0e9j\torch\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\freds\AppData\Local\Temp\pip-install-ufih0e9j\torch\setup.py", line 12, in <module>
        from tools.setup_helpers.env import check_env_flag
    ModuleNotFoundError: No module named 'tools.setup_helpers'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

From what research I've done (I'm not a python dev by trade so I may be super wrong here), the package versions detailed in requirements.txt are quite old?

Where am I going wrong? 

Thanks in advance :)

**Comment by prajwalkr** [comment]
Are you using a 64-bit version of Python?

**Comment by fred-aghq** [comment]
> Are you using a 64-bit version of Python?

Possibly. How can I check, and should I not be?

**Comment by prajwalkr** [comment]
Yes, you should be using a 64-bit version. I am not sure how to check that on Windows. You can look it up.

**Comment by fred-aghq** [comment]
Thanks for replying.

I AM using 64-bit version - this is the default.

Can you maybe just update the package versions? :) seems like this is causing a lot of problems for people.

Do you have any other suggestions?

**Comment by gpavanb1** [comment]
Yes, I have already posted an issue related to this. Even `tensorflow==1.12.0` is also being utilized and that is far from what is in vogue.

Please revise your `requirements.txt` or at least mention the exact configurations you have used for execution.

**Comment by prajwalkr** [comment]
We have used Python 3.5.2 and the requirements.txt is generated from the working environment itself. People have raised issues about this. Please check:

https://github.com/Rudrabha/Wav2Lip/issues/30
https://github.com/Rudrabha/Wav2Lip/issues/81
https://github.com/Rudrabha/Wav2Lip/issues/85
https://github.com/Rudrabha/Wav2Lip/issues/121
https://github.com/Rudrabha/Wav2Lip/issues/131

Please let me know if any of the above help and what works.

**Comment by Acurisu** [comment]
To install `torch==1.1.0` and `torchvision==0.3.0` on python 3.6.x do
`pip install torch===1.1.0 torchvision===0.3.0 -f https://download.pytorch.org/whl/torch_stable.html`

**Comment by fred-aghq** [comment]
Thank you all for your patience and help :)

I will try your advice and update this issue with the outcome.

**Comment by fred-aghq** [comment]
> We have used Python 3.5.2 and the requirements.txt is generated from the working environment itself. 

Tried using conda to switch to 3.5.2 but its not even available on their repo any more.

Is there a docker image you could recommend I use? It's a bit of a pain having to switch envs all the time to try different python versions.

**Comment by fred-aghq** [comment]
I think I might just need Visual Studio C++ Build Tools to build numba and it might be working on 3.6.9. I'll update when I know more.

**Comment by fred-aghq** [comment]
I'm going around and around in dependency hell here and I don't really have any more time for this.

Solutions listed above didn't work.

Thanks anyway.

**Comment by wowopc** [comment]
python inference.py --checkpoint_path checkpoints/wav2lip_gan.pth --face /Video/1.MOV --audio /Video/1.mp4

Boss, I tried many times and the command is correct. My path is not wrong, but why is it found?    np_resource = np.dtype([("resource", np.ubyte, 1)])
Using cpu for inference.
Traceback (most recent call last):
  File "inference.py", line 280, in <module>
    main()
  File "inference.py", line 183, in main
    raise ValueError('--face argument must be a valid path to video/image file')
ValueError: --face argument must be a valid path to video/image file

**Comment by Saraceni** [comment]
Having the same problem. I was unable to run the script =/

**Comment by shikhasingh1797** [comment]
Hello 
Please update requirements.txt , facing too many issues related to packages

**Comment by prajwalkr** [comment]
Could you tell us what are the packages with issues?

**Comment by zozidalom** [comment]
@prajwalkr 

ERROR: Could not find a version that satisfies the requirement torch===1.1.0 (from versions: none)
ERROR: No matching distribution found for torch===1.1.0
