### ISSUE TITLE
Wrong model inside the demo?

### ISSUE THREAD

**Issue by clone95** [Rudrabha/Wav2Lip#138]
Yesterday I tried the demo at https://bhaasha.iiit.ac.in/lipsync/upload/ and I obtained excellent results. But after this night downtime, the trials I'm doing now are giving back completely horrible results. Did you upload a different model from yesterday?

**Comment by prajwalkr** [comment]
Please try to upload a model at https://bhaasha.iiit.ac.in/lipsync in incognito and see if you are able to reproduce the results from yesterday. 

> Did you upload a different model from yesterday?

No.

**Comment by clone95** [comment]
Nice I will try, thanks!

**Comment by clone95** [comment]
I tried in incognito, but I have the same (completely non-consistent) result. I've upload my .wav and .mp4 in this repo:
https://github.com/clone95/Speech-to_lips
It should be a very simple trial!
maybe you can try to reproduce the result / point me where the problem can reside. The language is Italian.

**Comment by prajwalkr** [comment]
Can you try with this code and see if you are able to reproduce the result? The model here is the same as the one in the demo. The demo website seems to be down due to heavy traffic.

**Comment by clone95** [comment]
yes sure, I will try with the code soon :)
