### ISSUE TITLE
Librosa error no wav file

### ISSUE THREAD

**Issue by bostjan39** [Rudrabha/Wav2Lip#139]
Hey,

I tried to run the script, but it throws "no file temp/temp.wav" and exits.
Why is that?

**Comment by prajwalkr** [comment]
Can you explain the steps to reproduce the error?

**Comment by SnoutBug** [comment]
try to set your terminal working directory to the repo path and don't use relative paths.
So dont use python c:\users\name\repo\inference.py but navigate to c:\users\name\repo\ and use python inference.py
worked for me

**Comment by bostjan39** [comment]
Thanks, but I was able to solve this by uploading my audio file in wav format, instead mp3.
