### ISSUE TITLE
Make face detection a generator

### ISSUE THREAD

**Issue by kousu** [Rudrabha/Wav2Lip#14]
`face_detect()` is by far the slowest part of `inference.py`, and it also buffers all its results. This means getting results is slow and RAM is wasted. You could make `face_detect()` a generator instead and the output video would start being written immediately and your RAM usage would be bounded (by the batch size).

**Comment by prajwalkr** [comment]
Could you please submit a pull request for this change as well? Currently busy for a few days.

**Comment by kousu** [comment]
I am happy to do this. I love writing generators.

On September 5, 2020 3:58:41 AM EDT, Prajwal <notifications@github.com> wrote:
>Closed #14.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Rudrabha/Wav2Lip/issues/14#event-3732708295

-- 
kousu
