### ISSUE TITLE
Default checkpoint

### ISSUE THREAD

**Issue by gpavanb1** [Rudrabha/Wav2Lip#140]
How do we run the code without any available checkpoint files? Currently, there seems to be a `wav2lip_gan.pth` being referenced in the example Google Colab notebook, but we are reluctant to give our Google Drive permission for its sake.

**Comment by prajwalkr** [comment]
you can make ur own private copy of the notebook and give the permissions to that for your private copy. And also, this is an inference code of a model, so without the checkpoint, the code would not make much sense to run, I guess.

**Comment by gpavanb1** [comment]
Does it mean it is specific to the face detection model we are downloading? Since it is being mentioned as a pre-requisite anyways, would be great if you can add the `.pth` to the repository as well.

**Comment by prajwalkr** [comment]
> Does it mean it is specific to the face detection model we are downloading?

I meant you need to use the wav2lip checkpoint. Face detection checkpoint you can download easily using the `wget` command.

**Comment by gpavanb1** [comment]
It seems to be a pre-requisite in that case. I have downloaded it from Drive for now but would be great if it is part of the repo too.

**Comment by Minjun-KANG** [comment]
Thank you for doing good research. I agree with gpavanb1's opinion. I think the .pth file is basically large. I think it would be better to write a comment in the colab rather than adding it to the repository.
