### ISSUE TITLE
custom training set parameters

### ISSUE THREAD

**Issue by jays0606** [Rudrabha/Wav2Lip#143]
I have read through your guide to custon training set. I was wondering if there are any other changes I have to make other than setting the video into 25 fps. Currently, the below is how my dataset is defined. The 2nd image is a sample in the lrs3 dataset.

Thank you very much
<img width="1229" alt="Screen Shot 2020-11-13 at 11 21 08 AM" src="https://user-images.githubusercontent.com/59599444/99020629-58d1b480-25a2-11eb-813b-4e633747f7c1.png">
![Screen Shot 2020-11-13 at 11 14 14 AM](https://user-images.githubusercontent.com/59599444/99020632-5a9b7800-25a2-11eb-8c22-28f9aeb516c2.png)

**Comment by prajwalkr** [comment]
I would suggest you resample all videos to 25fps and that will save you a lot of trouble.

**Comment by jays0606** [comment]
Thank you very much !

**Comment by jays0606** [comment]
One more question please. 

I noticed this command in preprocess.py 
#template2 = 'ffmpeg -hide_banner -loglevel panic -threads 1 -y -i {} -async 1 -ac 1 -vn -acodec pcm_s16le -ar 16000 {}'

When preprocessing, should I also set the frequency to 16k Hz ? Currently the audio files are in 44.1k Hz

Thank you very much.

**Comment by prajwalkr** [comment]
> should I also set the audio frequency to 16k Hz ?

yes
