### ISSUE TITLE
is possible to install your code?

### ISSUE THREAD

**Issue by sasanaskari** [Rudrabha/Wav2Lip#144]
Hi,Is possible to install or have your code on local desktop computer to run and use?

**Comment by sasanaskari** [comment]
if there is a way please help me!

**Comment by prajwalkr** [comment]
Please read the instructions in the README to use the code

**Comment by sasanaskari** [comment]
unfortunately,the part that you mention is inexpressive for me!is there a video to learn install it on desktop computer?

**Comment by prajwalkr** [comment]
https://www.youtube.com/results?search_query=wav2lip+tutorial
