### ISSUE TITLE
Error FileNotFoundError [winError 2]

### ISSUE THREAD

**Issue by Mark-papi** [Rudrabha/Wav2Lip#145]
i get the error bellow, running the python code, 
im running the program through anaconda cause it works only with python 3.6 or something, but i get the following error.

**Traceback (most recent call last):
  File "inference.py", line 279, in <module>
    main()
  File "inference.py", line 276, in main
    subprocess.call(command, shell=True)
  File "C:\ProgramData\Anaconda3\envs\wav2lip\lib\subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\ProgramData\Anaconda3\envs\wav2lip\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "C:\ProgramData\Anaconda3\envs\wav2lip\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified**

thank you for any help for solving the issue.

**Comment by Mark-papi** [comment]
it seems there is a problem here in the inference file command command = 'ffmpeg -y -i {} -i {} -strict -2 -q:v 1 {}'.format(args.audio, 'temp/result.avi', args.outfile)

**Comment by prajwalkr** [comment]
Ensure `ffmpeg` is installed. Also, try giving the audio in the `.wav` format.

**Comment by Mark-papi** [comment]
> Ensure `ffmpeg` is installed. Also, try giving the audio in the `.wav` format.

Thanks for the answer !
The audio is on wav format , the ffmpeg is installed on C:/Windows/ffmpeg and I set it on the systems path 
With cmd command ffmpeg -version 
I can see the version of ffmpeg

**Comment by Mark-papi** [comment]
In the tmp folder of the project I can see the result , and the lips are moving correctly , but there is no audio mixing with the video/jpg

**Comment by Mark-papi** [comment]
I had to manually mix them to get the end result

**Comment by prajwalkr** [comment]
> 'temp/result.avi'

I think this is the issue. Windows uses a different slash. Can you replace it with `os.path.join("temp", "result.avi")' and try again?

**Comment by Mark-papi** [comment]
Perfect thank you !!, 
Probably this is the problem 
I will try it and I will report back.

**Comment by Mark-papi** [comment]
i canged it to **command = 'ffmpeg -y -i {} -i {} -strict -2 -q:v 1 {}'.format(args.audio, os.path.join("temp", "result.avi"), args.outfile)**
but i still get the error, saying **FileNotFoundError: [WinError 2] The system cannot find the file specified**

**Comment by prajwalkr** [comment]
> In the tmp folder of the project I can see the result , and the lips are moving correctly

You need to point the path of this file in the line of code that is rising an error.

**Comment by Mark-papi** [comment]
i dont know, maybe it is the ffmpeg,
do you have a link to download the correct version of it, and if you can, a how to install it.
i found only builds of it on the internet

**Comment by Mark-papi** [comment]
i tried from cmd ffmpeg -i file.wav output.mp3
and it worked so i suppose it is not ffmpeg error

**Comment by Mark-papi** [comment]
can you explain me what its parameter commands of this line do ? 
command = 'ffmpeg -y -i {} -i {} -strict -2 -q:v 1 {}'.format(args.audio, 'temp/result.avi', args.outfile)
i may have a workaround to fix the problem .

**Comment by prajwalkr** [comment]
> it is not ffmpeg error

most probably not. 

> can you explain me what its parameter commands of this line do ?

you are passing the audio file (args.audio), the generated silent file with the morphed lip movements (temp/result.avi) and specifying an output path to save the result. I think FFMpeg is unable to read/write one of these as the paths might be incorrect

**Comment by Mark-papi** [comment]
yea probably that, cause when im running the ffmpeg command inside the conda python environment it works (and im able to join the generated video/lip movement with the sound)

**Comment by Mark-papi** [comment]
im gonna try to modify it or do a workaround, and i will report back

**Comment by Mark-papi** [comment]
successssssss!!!
what worked for me is that
i change the code a little bit and in the command =
i just place this line 
subprocess.run("ffmpeg -y -i {} -i {} -strict -2 -q:v 1 {}".format(args.audio, 'temp/result.avi', args.outfile))

**Comment by Mark-papi** [comment]
i dont know why, maybe the double quotes ?

**Comment by Mark-papi** [comment]
successssss i solve it!!
deleting the last shell=true helped to solve the problem!
where this command is used for ?

**Comment by Mark-papi** [comment]
It works perfectly !!
It's awesome and fun I love it!!!!

**Comment by bigdog3604** [comment]
I have this same issue.  Mark-papi fixed this problem by "deleting the last shell=true" parameter.  I need help figuring out how to do that.  Any ideas?
