### ISSUE TITLE
Support animals

### ISSUE THREAD

**Issue by franz101** [Rudrabha/Wav2Lip#146]
Is it possible to make a cat talk for example?
Or which alternative paper would you recommend?

**Comment by prajwalkr** [comment]
You can try it on a cat image yourself. The first challenge is that the face detection module might not detect the face in the image, so you might need to change the code specifying the bounding box of the ``cat face"

**Comment by Ha0Tang** [comment]
@franz101 Did you let the cat talk? how did you modify the code? Thanks.
