### ISSUE TITLE
Inference time estimate

### ISSUE THREAD

**Issue by pietro-ux** [Rudrabha/Wav2Lip#147]
Hi,
I am was wondering about the inference time because it runs pretty slow on my computer, I want to compare different resolutions and lengths of the videos. Do you have any idea how the inference time depends on the input resolution, rescale factor and the length of the audio or if there are any more parameters to consider?

**Comment by prajwalkr** [comment]
The inference time is mostly dependent on the face resolution and face detection is the most time-consuming part. You can make things much faster by using a GPU.

**Comment by pietro-ux** [comment]
I am using linear regression to estimate the time on 30 videos with different lengths, resolutions and rescale factors, and I get 94 % accuracy on them but 64% on unseen 10 videos. I am using the face resolution, input video resolution, rescale factor, fps and the audio length as features. Any idea why its not fitting well?

**Comment by rizwanishaq** [comment]
@prajwalkr @pietro-ux I am trying the model with [RetinaNetMobileNetV1](https://pypi.org/project/face-detection/). It is pretty fast even on cpu.

**Comment by prajwalkr** [comment]
Yes, the face detection is the major bottleneck.

**Comment by Vishal24102002** [comment]
give some suggestions for this problems how to solve this
