### ISSUE TITLE
Computer frozen when running the program.

### ISSUE THREAD

**Issue by Mark-papi** [Rudrabha/Wav2Lip#148]
Hello!

so its working fine for a single/still image but when im trying a video and an audio together it becomes frozen (my computer unusable)
probably cause its running all the stuff in the cpu and ram, and probably cause its using a big batch ? 
is there a way to tell the program to run everything in my second gpu (and with minimum resources ) ? 
i dont want to run it on my main gpu , neither on my cpu and ram, but entirely on my second gpu but also with minimu resources as possible.
i dont have a problem if i wait like a day to finish a 2 mins video ;) 
the other solution is to try it on google colab, but i dont wanna to.

**Comment by Rudrabha** [comment]
In general, PyTorch will automatically coordinate the resources required from the CPU and GPU. You can reduce the batch size for both face detection as well as the wav2lip model itself. You can find them in these [lines](https://github.com/Rudrabha/Wav2Lip/blob/d6b84272fd48d501b5ede1ee0c1795d20f445d0c/inference.py#L31). If you want to force the model to test on a particular GPU, you can run the following command before running the inference code.
```
export CUDA_VISIBLE_DEVICES=gpu_id
```

**Comment by Mark-papi** [comment]
Perfect thank you!!
i will give it a shot, otherwise i can still use it through the google colab, if my system cant handle it.
