### ISSUE TITLE
Multi GPU support for color_syncnet_train.py

### ISSUE THREAD

**Issue by hmen97** [Rudrabha/Wav2Lip#150]
Does color_syncnet_train.py have multi gpu support? Just want to know because for me in a multi gpu server only one is being used and that too 2G/11G. I can see all the cores are being used up, does this mean the bottleneck is in the reading of images?. Can you tell me where the bottleneck in the training process is and how we could improve the speed of training. 
PS: This is an amazing implementation, kudos to the team

**Comment by prajwalkr** [comment]
The syncnet model is pretty fast even on a single GPU. You can increase the batch size if you want to use more GPU memory. You can use `DataParallel` to use multiple GPUs, but we have not tested its accuracy, etc.
