### ISSUE TITLE
How to use Expert discriminator?

### ISSUE THREAD

**Issue by bostjan39** [Rudrabha/Wav2Lip#155]
Hey,

I downloaded the lipsync_expert.pth, but don't know where to put it and how to use it in command?

Thanks!

**Comment by prajwalkr** [comment]
https://github.com/Rudrabha/Wav2Lip#training-the-wav2lip-models

**Comment by leotran1987** [comment]
Hello, how to render video higher resolution, ex: 720p?
Thank you!
