### ISSUE TITLE
Time estimate 2

### ISSUE THREAD

**Issue by pietro-ux** [Rudrabha/Wav2Lip#156]
I am using linear regression to estimate the time of inference of 30 videos with different lengths, resolutions and rescale factors, and I get 0.94 R2 score on them but 0.64 R2 on unseen 10 videos. I am using the face resolution, input video resolution, rescale factor, fps and the audio length as features. Any idea why its not fitting well, I must be missing some feature? I am using GPU and if I run the same video with the same parameters multiple times, the difference in time is within 2 seconds, so there is not much randomness.

**Comment by prajwalkr** [comment]
> I am using linear regression to estimate the time of inference of 30 videos with different lengths, resolutions and rescale factors

why are you doing this?

**Comment by pietro-ux** [comment]
I want to run it automatically and I need to know which video takes how much time so I can set a reasonable limit

**Comment by prajwalkr** [comment]
I have no idea to fix your issue. I suggest you can estimate rescale factors etc. with simple if condition heuristics if needed.
