### ISSUE TITLE
How to train your gan? 

### ISSUE THREAD

**Issue by wanghzhRun** [Rudrabha/Wav2Lip#157]
why Percep loss keep increasing when using gan?
![image](https://user-images.githubusercontent.com/24540965/100046633-87297c80-2e4b-11eb-81a6-11ad690f3afd.png)

**Comment by prajwalkr** [comment]
Your L1 and sync loss are quite low and decreasing rapidly. The GAN is hard to train due to the pose changes and artifacts that occur during training. We are working on an improvement for this at the moment.

**Comment by wanghzhRun** [comment]
your means is we should train gan without pretrain wav2lip model when we want to use gan to train wav2lip?

**Comment by prajwalkr** [comment]
No, I didn't mean that. I just told the reason why perceptual loss is increasing.
