### ISSUE TITLE
About the proportion of head size in video in training data，Thank you！

### ISSUE THREAD

**Issue by ZerRui** [Rudrabha/Wav2Lip#160]
I found that the proportion of the head in the whole video picture in your training data is basically fixed. Do we have to make such data? What's the impact if the distance or size of the characters in our videos are not fixed? If we have to do the imaging of your data scale, how do you cut the original video? Thank you very much!

**Comment by prajwalkr** [comment]
I do not fully understand the question. Do you want to create your own training data? And you are asking what the scale of the face in the video should be?

**Comment by ZerRui** [comment]
Yes，want to create your own training data，
I found that your video size is 160 * 160, and the size of people in the picture is basically fixed. Do we need to cut it to this size or any size?

**Comment by prajwalkr** [comment]
We suggest you to not resize it to anything when creating the data. You can resize it on-the-fly while training the model.

**Comment by ZerRui** [comment]
Different sizes of video, different people in the video ratio will affect the size of face clipping,  Does this affect the training effect?

**Comment by prajwalkr** [comment]
No, it should be okay.

**Comment by ZerRui** [comment]
OK, thank you very much for your patience. Thank you!

**Comment by ZerRui** [comment]
Is it necessary to cut a complete video of a person into sentence by sentence? Does silence before and after a sentence affect it? 
Looking forward to your reply, thank you

**Comment by prajwalkr** [comment]
No, that is fine. You can keep the silence.
