### ISSUE TITLE
About the background of training data

### ISSUE THREAD

**Issue by ZerRui** [Rudrabha/Wav2Lip#161]
I found that your training data are very diverse, including background and characters. I have recorded many videos using only the green screen background. There is an obvious fusion trace in the jaw position of the synthesized video. Do you think we should record videos with different backgrounds? We look forward to your reply!

**Comment by ZerRui** [comment]
![2020-12-01 10-43-04屏幕截图](https://user-images.githubusercontent.com/34739958/100690724-20afdb80-33c2-11eb-90e4-847e24b6afa1.png)

**Comment by prajwalkr** [comment]
Your L1 loss needs to go down further to improve the generation/reconstruction. If you are training and testing on green screens only, there is no need to record in different backgrounds.
