### ISSUE TITLE
Face not detected

### ISSUE THREAD

**Issue by KolyaToys** [Rudrabha/Wav2Lip#165]
Hello everyone! My Wav2Lip not detected face in frames, but video has face in every frame... How to fix it?

Inputs:
https://drive.google.com/drive/folders/1RdgowhobQe0dSF5FiMl4BjC6exaMUCLP?usp=sharing

**Comment by prajwalkr** [comment]
Can you crop out the last few seconds and the first few seconds of the video and try again? If it does not work still, then it is just that the face detector has failed to detect the face for some reason.

**Comment by KolyaToys** [comment]
I gonna try

**Comment by KolyaToys** [comment]
thank you!
