### ISSUE TITLE
Multiple face in frame of the video

### ISSUE THREAD

**Issue by rhulprksh** [Rudrabha/Wav2Lip#166]
Why it shows "a face not found in each frame" error when there are more than one faces in the video?
Is there anyway to lipsync for multiple faces in frames of a video?

**Comment by prajwalkr** [comment]
Check if this option is useful: https://github.com/Rudrabha/Wav2Lip/blob/d6b84272fd48d501b5ede1ee0c1795d20f445d0c/inference.py#L38

And the options below that line as well.

Otherwise you would need to feed manually cropped videos or change the code.
