### ISSUE TITLE
Has anyone tried training with high-qual avspeech dataset?

### ISSUE THREAD

**Issue by jays0606** [Rudrabha/Wav2Lip#167]
I have tried to do so after resizing the image to 192 x 192, but the sync loss does not fall below 0.7, so the final result isn't very good.

Has anyone succeeded in training with high-qual videos? 

I'm not sure what the problem is

**Comment by rebotnix** [comment]
Do you just resize the image or can the layers inside the network?  Image Rezing will not help.

**Comment by jays0606** [comment]
I used the avspeech data, resized face detection results to 192x192, added some layers into the model.

**Comment by CHUUUU** [comment]
i resize 512x512 (using wav2lip face_detection and resize) -> 96x96 
but almost sync loss is between 1 and 2

**Comment by jays0606** [comment]
> i resize input image to 512x512 (using wav2lip face_detection and resize) -> and generator output image 512x512 and resize 96x96
> but almost sync loss is between 1 and 2

How was your final output?

**Comment by CHUUUU** [comment]
lips don't follow the sound , but follow the image, because decoder almost doesnt get sync loss.

and i tried label image and label mel put to syncnet , sync loss was between 1 and 2

**Comment by jinny960812** [comment]
I tried with my own dataset but it either sync well but has lots of artifacts or doesn't sync but looks clean and realistic. I looked at the loss graph and it actually does drop and rise abruptly... Does anyone know what the problem is?

**Comment by rebotnix** [comment]
The loss must be < 0.25 to get good results. Loss 1 - 2 is not useable at all and it seems that you have an issue in your dataset. Try to split to more smaller clips. The other thing is that you have to redesign the whole network, cause this project uses input size of only 96px. It´s required to add more layers to accept higher input size for your dataset as well for the inference. After that you have to re-train syncnet first, then wav2lip. Hope that can help you guys.
