### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by wowopc** [Rudrabha/Wav2Lip#168]
C:\Wav2Lip>cd C:\Wav2Lip && python inference.py --checkpoint_path checkpoints/wav2lip_gan.pth --face VSP/.mp4" --audio /VSP/1.MOV
Traceback (most recent call last):
  File "inference.py", line 3, in <module>
    import scipy, cv2, os, sys, argparse, audio
ModuleNotFoundError: No module named 'cv2'

C:\Wav2Lip>
C:\Wav2Lip>cd C:\Wav2Lip && python inference.py --checkpoint_path checkpoints/wav2lip_gan.pth --face VSP/.mp4"
Traceback (most recent call last):
  File "inference.py", line 3, in <module>
    import scipy, cv2, os, sys, argparse, audio
ModuleNotFoundError: No module named 'cv2'
I don't know what went wrong, ask the boss for advice

**Comment by marianobasti** [comment]
You have to install opencv-python

**Comment by wowopc** [comment]
I installed the extension, but it is still wrong     cd C:\Wav2Lip && python inference.py --checkpoint_path checkpoints/wav2lip_gan.pth --face VSP/.mp4" --audio /VSP/1.MOV
Traceback (most recent call last):
  File "inference.py", line 3, in <module>
    import scipy, cv2, os, sys, argparse, audio
  File "C:\Wav2Lip\audio.py", line 1, in <module>
    import librosa
ModuleNotFoundError: No module named 'librosa'

**Comment by marianobasti** [comment]
You have to install all the modules that are in requirements.txt

**Comment by wowopc** [comment]
Hey, thanks for your hard work, all the environments have been successfully installed, but I have encountered a new problem. . . C:\Wav2Lip>cd C:\Wav2Lip && python inference.py --checkpoint_path checkpoints/wav2lip_gan.pth --face VSP/.mp4" --audio /VSP/1.MOV
C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) /'(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) /'(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) /'(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) /'(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) /'(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) /'(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

**Comment by wowopc** [comment]
Thank you very much. What is the problem?

**Comment by wowopc** [comment]
Thank you very much. Why is this wrong? I have configured the environment for a day and I am about to cry

**Comment by prajwalkr** [comment]
Hi! Those are just warnings. You can ignore them. As you can see the program will continue to run after those warnings.

**Comment by wowopc** [comment]
python inference.py --checkpoint_path checkpoints / wav2lip_gan.pth --face /Video/1.MOV --audio /Video/1.mp4

老板，我试了很多次，命令是正确的。我的路径没有错，但是为什么找到它呢？np_resource = np.dtype（[（“ resource”，np.ubyte，1）]）
使用cpu进行推断。
追溯（最近一次通话最后一次）： main（）中的
文件“ inference.py”，第280 行，主 抬高中的文件“ inference.py”，第183行，ValueError（'-面参数必须是video /的有效路径图片文件'） ValueError：--face参数必须是视频/图片文件的有效路径

**Comment by wowopc** [comment]
It seems to run, but it seems that I run by the CPU and not the GPU......-。- How do I set the GPU to run...

**Comment by wowopc** [comment]
How to deal with it, brothe

**Comment by wowopc** [comment]
Thank you very much for the successful installation
