### ISSUE TITLE
Output audio shorter than input audio

### ISSUE THREAD

**Issue by JanFschr** [Rudrabha/Wav2Lip#17]
In my tests the generated audio output was 0.05 seconds shorter than the input. Input: 01:04.16, Output 01:04.11 .
Not much but enough to disturb a seamless integration. Is this possibly due to a ffmpeg setting?

**Comment by prajwalkr** [comment]
No. This is because the current code doesn’t generate one last frame. I will leave this open until this is fixed.

**Comment by Rudrabha** [comment]
You can try with padding the original audio video by replication the last frame 2-3 times and also adding 0's in the audio channel. This will probably be enough for you to get back the original duration in the generated video.

**Comment by prajwalkr** [comment]
> You can try with padding the original audio video by replication the last frame 2-3 times and also adding 0's in the audio channel. This will probably be enough for you to get back the original duration in the generated video.

This is probably a quick and easy thing to try for you. closing this for now.
