### ISSUE TITLE
Expert training curve.

### ISSUE THREAD

**Issue by BertyWooster** [Rudrabha/Wav2Lip#170]
Hello! As I already mentioned your results are really good! I try to train your expert model on my own data in the Russian language. I am going to train before loss~0.2 as you mentioned earlier.

I have about 30 hours of data from youtube. There are about 200 unique speakers and data is balanced (equal video time for each speaker - about 10 minutes).

I started with your weights and went through 125 000 iterations with batch_size=64. I get such a loss stat and now try to understand: Is there some problem with the training speed in my case or I have to wait for. (For the last 79 000 steps loss has changed from  0.53 to 0.51) Can you tell me, please, is this loss curve similar to yours's or there can be some problem in my experiment conditions?  

![stat](https://user-images.githubusercontent.com/25998658/102977713-6f114f80-4514-11eb-9f00-75ebe5d4d723.png)

**Comment by prajwalkr** [comment]
YouTube videos are generally not sync corrected. Please use https://github.com/joonson/syncnet_python to sync correct your training videos, before training on them.

**Comment by BertyWooster** [comment]
Thank you for the advice! Does it mean that there was a better speed of convergence in your case?

**Comment by prajwalkr** [comment]
Idk about speed, but the loss must go down much further if the videos are proper.

**Comment by BertyWooster** [comment]
Thank you very much!
