### ISSUE TITLE
Training problem

### ISSUE THREAD

**Issue by wowopc** [Rudrabha/Wav2Lip#171]
Hi, because it is a tutorial that is a pure white novice without training.. LRS2 data set folder structure
Is the content in a txt file like this? Data_root (mvlrs_v1) under request guidance
├──main, pretrain (in this work, we only use the main folder)
| ├──Folder list
| │├──A five-digit video ID ending in (.mp4)

**Comment by wowopc** [comment]
The damn translation may not be very clear. Write the video location in the txt file
MP4? such as



Hi, because it is a tutorial that is a pure white novice without training.. LRS2 data set folder structure
Is the content in a txt file like this? Data_root (mvlrs_v1) under request guidance
├──main, pretrain (in this work, we only use the main folder)
| ├──Folder list
| │├──A five-digit video ID ending in (C/:1.mp4)

**Comment by wowopc** [comment]
The damn translation may not be very clear. Write the video location in the txt file
MP4? such as

Data_root (mvlrs_v1) under request guidance
├──main, pretrain (in this work, we only use the main folder)
| ├──Folder list
| │├──A five-digit video ID ending in (C/:1.mp4)

**Comment by prajwalkr** [comment]
I do not understand your question

**Comment by wowopc** [comment]
Simply put, how to train...There is no tutorial on tou tube...please follow the tutorial
I don’t know how to operate after looking at the folder structure

**Comment by nchengyeeshen** [comment]
The filelists can be obtained along with the LRS2 dataset. Look at https://www.robots.ox.ac.uk/~vgg/data/lip_reading/lrs2.html and you'll see links to the filelists.

**Comment by wowopc** [comment]
Big guy, I want to ask about training videos... Is there any video tutorial... There are videos and you understand everything... The text is too abstract

**Comment by prajwalkr** [comment]
Sorry, such videos are not available from our side. You can search on YouTube if there are any.
