### ISSUE TITLE
Training issues error

### ISSUE THREAD

**Issue by wowopc** [Rudrabha/Wav2Lip#172]
run
 
python wav2lip_train.py --data_root lrs2_preprocessed/ --checkpoint_dir checkpoint --syncnet_checkpoint_path checkpoints/lipsync_expert.pth 

use_cuda: True
Traceback (most recent call last):
  File "wav2lip_train.py", line 342, in <module>
    train_dataset = Dataset('train')
  File "wav2lip_train.py", line 42, in __init__
    self.all_videos = get_image_list(args.data_root, split)
  File "C:\Wav2Lip\hparams.py", line 9, in get_image_list
    for line in f:
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 30: illegal multibyte sequence        What's wrong

**Comment by prajwalkr** [comment]
Your file-list text file might be corrupted.

**Comment by wowopc** [comment]
data_root (mvlrs_v1)
├── main, pretrain (we use only main folder in this work)
|	├── list of folders
|	│   ├── five-digit numbered video IDs ending with (.mp4)      

he file list text file is Chinese under Google. Can this be handled? The file is UTF-8

**Comment by wowopc** [comment]
The file list text file is Chinese under Google. Can this be handled? The file is UTF-8

**Comment by prajwalkr** [comment]
I think probably then you need to read/write in UTF-8

**Comment by wowopc** [comment]
How to change files, novices who don’t understand, can you teach me?

**Comment by prajwalkr** [comment]
https://www.google.com/search?q=read+%2F+write+data+in+utf8+python

https://stackoverflow.com/a/6048203

Another option would be to name your files with numbers (similar to how LRS2 has) so that the characters are all ASCII.
