### ISSUE TITLE
How many hours of video of how many different speakers is required if training on own dataset?

### ISSUE THREAD

**Issue by Shriram-Coder99** [Rudrabha/Wav2Lip#175]
Hello,
I would like to train the model on a high quality video dataset because  the current model gives a blurry output. I would like to know how many hours of video and how many speakers I should use to get accurate results comparable to the current model.

**Comment by prajwalkr** [comment]
Do you want the model to work on any speaker without further training? Then you can try the AVSpeech dataset. If you are focusing on a single speaker, we do not know how much data is required, as we have never tried a speaker-specific experiment
