### ISSUE TITLE
我已经下好LRS2数据集 运行命令 怎么错误呢

### ISSUE THREAD

**Issue by wowopc** [Rudrabha/Wav2Lip#177]
I have already downloaded the LRS2 data set and run the command. What's wrong!

![屏幕截图(12)](https://user-images.githubusercontent.com/23237930/103234783-76ed4b80-497b-11eb-9a2d-b8d7dc9e3675.png)

run    

 python preprocess.py --data_root data_root \ main --preprocessed_root lrs2_preprocessed\

result 

  np_resource = np.dtype([("resource", np.ubyte, 1)])
usage: preprocess.py [-h] [--ngpu NGPU] [--batch_size BATCH_SIZE] --data_root
                     DATA_ROOT --prep

rocessed_root PREPROCESSED_ROOT
preprocess.py: error: unrecognized arguments: \ main

**Comment by prajwalkr** [comment]
> data_root \ main

there is space in between these two. remove the spaces.

**Comment by wowopc** [comment]
Started processing for data_root\main with 1 GPUs
0it [00:00, ?it/s]
Dumping audios...
0it [00:00, ?it/s]

No response

**Comment by wowopc** [comment]
be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Started processing for data_root\main with 1 GPUs
0it [00:00, ?it/s]
Dumping audios...
0it [00:00, ?it/s]

C:\Wav2Lip>

**Comment by prajwalkr** [comment]
Closing because you have opened another issue regd this.

**Comment by DWCTOD** [comment]
你好，可以分享一下这个数据集吗？已经毕业了，没有权限下载，非常感谢！邮箱 534155562@qq.com
wx：nvshenj125 谢谢大佬

**Comment by wowopc** [comment]
大佬我加你微信了啊------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;zero&amp;nbsp;is&amp;nbsp;not&amp;nbsp;none&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年2月24日(星期三) 下午2:48
收件人:&nbsp;&quot;Rudrabha/Wav2Lip&quot;<Wav2Lip@noreply.github.com&gt;;
抄送:&nbsp;&quot;wowopc&quot;<1944404023@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Rudrabha/Wav2Lip] 我已经下好LRS2数据集 运行命令 怎么错误呢 (#177)

**Comment by loongofqiao** [comment]
@wowopc @DWCTOD 你好，可以分享下LRS2数据集吗？邮箱m13122317086@163.com

**Comment by houdajun** [comment]
@wowopc @DWCTOD , 可以也要一份吗？ dajun.hou@gmail.com

**Comment by SRbone** [comment]
@wowopc @DWCTOD 你好，可以分享下LRS2数据集吗？邮箱812336801@qq.com

**Comment by fengmy** [comment]
@wowopc @DWCTOD 你好，请问分享下LRS2数据集吗？邮箱[620734263@qq.com](mailto:620734263@qq.com)
