### ISSUE TITLE
What is the output image size of the model?

### ISSUE THREAD

**Issue by Shriram-Coder99** [Rudrabha/Wav2Lip#179]
Is the output blurry because the output size is small? How can we make the output clearer and less blurry?
Will training on a new dataset with HD video quality, without changing the network structure in any way, result in clearer output?

**Comment by prajwalkr** [comment]
> Is the output blurry because the output size is small?

Yes.

> Will training on a new dataset with HD video quality, without changing the network struucture in any way, result in clearer output?

You need to change the architecture significantly, it is still a work in progress to achieve this. After these changes, training on a HD dataset will give a better quality.
