### ISSUE TITLE
LRS3 issues

### ISSUE THREAD

**Issue by wowopc** [Rudrabha/Wav2Lip#180]
LRS2 dataset folder structure
data_root (mvlrs_v1)
├── main, pretrain (we use only main folder in this work)
|	├── list of folders
|	│   ├── five-digit numbered video IDs ending with (.mp4)

Place the LRS2 filelists (train, val, test) .txt files in the filelists/ folder.
The LRS2 I downloaded is not tested. The txt files are all videos in the folder 00001*
How to write txt?
![屏幕截图(14)](https://user-images.githubusercontent.com/23237930/103299520-b9745e00-4a37-11eb-89b7-7d4690c2e9d1.png)
![屏幕截图(16)](https://user-images.githubusercontent.com/23237930/103299529-bbd6b800-4a37-11eb-81dd-574c59f6bcdc.png)
![屏幕截图(18)](https://user-images.githubusercontent.com/23237930/103299533-be391200-4a37-11eb-9a77-d95493d6518e.png)

**Comment by wowopc** [comment]
I am very sorry, because I am a novice and have no basic knowledge, so I asked a lot of novice questions. After learning, I will conduct training courses and share with you. After n attempts, I still cannot solve the problem, please ask a question! thank you very much

**Comment by prajwalkr** [comment]
> Place the LRS2 filelists (train, val, test) .txt files in the filelists/ folder.

Download the filelists from here: https://www.robots.ox.ac.uk/~vgg/data/lip_reading/lrs2.html


Filelist: Train | ae240cd86c8432afb5a6b8935c863f24
Filelist: Val | 3b7502de5c102519d62477f209c4cd35
Filelist: Test | e76bb897a2141f3581266daa850966bc
