### ISSUE TITLE
Seems doesn't work with blank(scilence) audio.

### ISSUE THREAD

**Issue by kjhgfdsaas** [Rudrabha/Wav2Lip#183]
I'm trying to use this brilliant work into a new synthesis way.
I select a normal video includes a talking person. And I create an audio which is slience(data in wave is all set 0, sounds scilence). 
I just want to replace the oringinal talking mouth to a closed mouth. But the output result video seems doesn't work. The result video has the synthesis boundary but it didn't change the talking mouth too much.

**Comment by prajwalkr** [comment]
Try once with adding small non-zero values (1e-5 for example). If it does not work even for that then, we really cannot help you. To be honest, generating for silent audios is still a work in progress.
