### ISSUE TITLE
图片人像边框

### ISSUE THREAD

**Issue by wowopc** [Rudrabha/Wav2Lip#184]
![FO72I ZITE E H$T6$JL(~9](https://user-images.githubusercontent.com/23237930/103519701-f1a0f400-4eb0-11eb-8e1d-79226dc6e8d5.png)
Can you handle it?

**Comment by wowopc** [comment]
Picture human border

**Comment by prajwalkr** [comment]
Is this during test-time using the pre-trained model?

**Comment by wowopc** [comment]
on wav2lip_gan.pth training

**Comment by prajwalkr** [comment]
Please explain further.

**Comment by wowopc** [comment]
Is using a pre-trained model

**Comment by prajwalkr** [comment]
I do not understand what you are trying to do.

**Comment by wowopc** [comment]
I run
cd C:\Wav2Lip &&python inference.py --checkpoint checkpoints/wav2lip_gan.pth  --face video/1.mp4 --audio video/1.m4a --pads 0 00 0 0 --resize_factor 2 --nosmooth 
There is a border in the image How to solve the big brother

**Comment by Rudrabha** [comment]
You can give more padding to see if the border becomes smoother. There is no specific way to remove border artifacts. We use a rectangular face crop for feeding the network and then paste back the generated face into the same coordinates. This can ideally be solved by a face mask used to crop exactly the facial region.  At the moment, we don't have a model supporting this.

**Comment by wowopc** [comment]
Provide more padding? Is it to run the command or something? pads 0 00 0 0  ？
