### ISSUE TITLE
Fix for requirments.txt using python 3.8 because it only runs with 3.6 (not 3.6+)

### ISSUE THREAD

**Issue by princessmittens** [Rudrabha/Wav2Lip#185]
I have read the previous comments about fixing the requirements txt. Here was my experience and I hope this helps others. 

These are the issues I ran into: 
```
ERROR: Could not find a version that satisfies the requirement opencv-python==4.1.0.25
ERROR: No matching distribution found for opencv-python==4.1.0.25
```

After installing opencv I ran into further errors (similar as above) trying to install torch 1.1.0 and torchvision. I messed around with trying to install the torch packages with 'wheel' manually (which didn't work).

My solution and I hope this helps others was to downgrade to python 3.6. 
1. Install Anaconda 
2. Created a virtual environment (so that I didn't have 3.6 running everywhere else, although this is not really necessary).
3. ```conda install python=3.6```
4. Check the version to ensure you have 3.6 ``` python3 --version```
5. Run the requirements.txt file

I hope this helps.

**Comment by prajwalkr** [comment]
Edited the Python version in the readme: https://github.com/Rudrabha/Wav2Lip/commit/67eacb185d34b8843c3d4309c6d2d0379342065c
