### ISSUE TITLE
train syncnet 

### ISSUE THREAD

**Issue by CHUUUU** [Rudrabha/Wav2Lip#186]
I am training both (syncnet, wav2lip) with a custom dataset, (30 min, one person,  FHD, 128p) 

How far should the loss fall when training syncnet ?

Because in wav2lip,
The sync loss doesn't fall well anymore 

The training seems to go well though,
When predicting, the lips move too small (not extremely)

![33333](https://user-images.githubusercontent.com/15378594/103608703-48650700-4f5f-11eb-9ced-4e9af45cc202.png)

**Comment by prajwalkr** [comment]
Please see: https://github.com/Rudrabha/Wav2Lip#training-on-datasets-other-than-lrs2

**Comment by ayush714** [comment]
Hi @CHUUUU Can u tell me how you were training, means I am only training on 3 videos duration of seconds, it has been 2+ hours but still not 1 epoch?
