### ISSUE TITLE
How long time did  you spend to  train wav2lip model  and eval_model's sync dropped to 0.75

### ISSUE THREAD

**Issue by wangzheliu** [Rudrabha/Wav2Lip#187]
evel _model:L1: 0.01623823121190071, Sync: 0.8051875829696655, Percep: 0.6918524503707886 | Fake: 0.6944650113582611, Real: 0.688401073217392
train loss :    L1: 0.011584884487092495, Sync: 0.0, Percep: 0.6792548845211664 | Fake: 0.70755
I train wav2lip model Several days.the L1 loss is good,but eval_model's sync is More than 0.75.so syncnet_wt =0.How long time did  you spend to  train wav2lip model  and eval_model's sync dropped to 0.75

**Comment by prajwalkr** [comment]
What dataset are you training on?

**Comment by wangzheliu** [comment]
my own dataset,one person ,2 hour,25 fps , 1080*720P，I change the input image size,and add some layers .the training  evel _model 's result image quality is good,but Lips move movement is small.

**Comment by wangzheliu** [comment]
> 
> 
> What dataset are you training on?

my own dataset,one person ,2 hour,25 fps , 1080*720P，I change the input image size,and add some layers .the training evel _model 's result image quality is good,but Lips move movement is small.

**Comment by prajwalkr** [comment]
Have you trained the SyncNet on the new dataset?

**Comment by Mombin** [comment]
did you trained with 96x96 of face size or other size???

**Comment by prajwalkr** [comment]
All our models are trained at 96x96

**Comment by burning846** [comment]
I have the same question. I have 10 hours of one person's videos in my dataset and my sync loss never fell below 1.0. AIthough my output seems good, syncNet didn't make any influence?

**Comment by prajwalkr** [comment]
Have you read this: https://github.com/Rudrabha/Wav2Lip#training-on-datasets-other-than-lrs2?
