### ISSUE TITLE
LRS2 data set problem rookie diary 1

### ISSUE THREAD

**Issue by wowopc** [Rudrabha/Wav2Lip#188]
I have downloaded some LRS2 data test.txt train.txt val.txt and part A. All BCFs behind. Should be placed in the main folder?
![K`I3F3 90)PMB71 E059MTO](https://user-images.githubusercontent.com/23237930/103675362-d0c4c580-4fba-11eb-84f2-3d625edbbf73.png)

**Comment by wowopc** [comment]
Why shouldn't this file be a folder with video? This is a compressed file?
![{V ZXF4IKZTWIM}%6KS(KSQ](https://user-images.githubusercontent.com/23237930/103675722-3d3fc480-4fbb-11eb-83d5-26a1426e7590.png)

**Comment by wowopc** [comment]
Please forgive my ignorance-. -

**Comment by prajwalkr** [comment]
We are unable to understand your question. Sorry.
