### ISSUE TITLE
Invalid preliminary data set

### ISSUE THREAD

**Issue by wowopc** [Rudrabha/Wav2Lip#189]
Run code

cd C:\Wav2Lip&& python preprocess.py --data_root  /mvlrs_v1 --preprocessed_root  /lrs2_preprocessed

result
 be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Started processing for /mvlrs_v1 with 1 GPUs
0it [00:00, ?it/s]
Dumping audios...
0it [00:00, ?it/s]

Why not run?

**Comment by wowopc** [comment]
Run code
python preprocess.py --data_root mvlrs_v1\main --preprocessed_root lrs2_preprocessed/
result
IndexError: list index out of range
Traceback (most recent call last):
  File "preprocess.py", line 105, in main
    process_audio_file(vfile, args)
  File "preprocess.py", line 71, in process_audio_file
    dirname = vfile.split('/')[-2]
IndexError: list index out of range
100%|██████████████████████████████████████████████████████████████████████████| 48165/48165 [00:10<00:00, 4568.66it/s]
Why not run?

**Comment by prajwalkr** [comment]
The preprocessing script only handles LRS2. Not mvlrs_v1. You need to change the code appropriately to do that.

**Comment by wowopc** [comment]
运行 
cd C:\Wav2Lip &&preprocess.py --data_root data_root/main --preprocessed_root lrs2_preprocessed/ 
no effect...

**Comment by backpass** [comment]
Hi @prajwalkr 

I also have downloaded LRS2 dataset (from https://www.robots.ox.ac.uk/~vgg/data/lip_reading/lrs2.html) and the folder "mvlrs_v1" has been created. Is it okay and did you get the same title after unpacking? 

I am suspicious because there is an actual dataset called "MV-LRS" so it may be possible that the wrong dataset is distributed on this website.

**Comment by prajwalkr** [comment]
> Is it okay and did you get the same title after unpacking?

Yes, and yes.

**Comment by backpass** [comment]
Thanks for clarification, I was a bit nervous about it )
