### ISSUE TITLE
How to shut it up?

### ISSUE THREAD

**Issue by bigboss97** [Rudrabha/Wav2Lip#19]
I used the colab and it worked beautifully, THANKS!
I have a problem. Whenever the audio has a silence piece the original mouth movement remains unchanged.
I've tried with "mmm" to "shutup". But it had no effect. So I used "ha ha ha" to minimize the lip movement.
Is there a way to close the mouth for silence?

**Comment by prajwalkr** [comment]
Did you try once with the non-GAN model? It performs better on silences

**Comment by bigboss97** [comment]
> 
> 
> Did you try once with the non-GAN model? It performs better on silences

I'm not familiar with that. How can I do that in colab?

**Comment by prajwalkr** [comment]
Just download the corresponding checkpoint and pass it as an argument in the same inference command.

**Comment by HusainKapadia** [comment]
Just a suggestion...perhaps to improve performance on silence you can add some simulated data to the training data set, where:

1. The audio inputs would be silence or add some low DB noise to it (to avoid Mel bands being NaN) 
2. The corresponding video could be created with an image of any random person with a neutral expression (of course the length's of the audio and video should match) 
3. Train the model with this extra data along with the LSR2 dataset specified in the README

Do you agree @prajwalkr ?

**Comment by prajwalkr** [comment]
Maybe it can help. Maybe using some short range temporal info might help even better. We are yet to experiment more on this.

**Comment by prajwalkr** [comment]
Re-open if needed.
