### ISSUE TITLE
Final MP4 quality is poor by default - How to change the CRF value?

### ISSUE THREAD

**Issue by AlonDan** [Rudrabha/Wav2Lip#193]
I've tried multiple smaller videos with nice quality and different (not big) resolutions.
But it seems like the final quality is always really poor probably because of [MP4] CRF value via FFMPEG compression.

I'm not sure what are the compression options or if I can change them by edit one of the files, since I'm not a programmer, I don't think I can mess with the code itself.

From my experience if the [MP4] CRF value is set to 16 and we'll change to 1 the quality will stay almost the same at the end.
I did many tests and I these great results using other edit softwares and even in DAINAPP it proves that it works and the final render quality results are NICE! 👍 

if change CRF from 16 to 0 for example the quality will remain poor, but if changed to 1 the quality will stay almost like the original video quality!

![DAINAPP_2021-01-11_16-21-23](https://user-images.githubusercontent.com/21152334/104193758-2240da80-5429-11eb-9a16-cca4f90209c5.png)

**MY QUESTION:**
How can I change the [MP4] CRF value from whatever the default is, to **1** ❓
is there a file I can just edit for that? (since I can't code)

Thanks ahead!

**Comment by prajwalkr** [comment]
Can you check if the `temp/result.avi` generated by the model is of the quality you desire? Because this is not influenced by FFMpeg. FFMpeg is only used to overlay this result.avi with the audio.

**Comment by AlonDan** [comment]
The result.avi is a bad quality compare to the video I put on first place.
I'm pretty sure if I can change the CRF from 16 (or whatever default is currently) to 1, it will look really good! almost like the original.

Is there a way to do that in one of the file so I can edit with notepad?

**Comment by prajwalkr** [comment]
but the result.avi is not generated using FFMpeg, it is rather created using OpenCV. So, where is the CRF value for that?

**Comment by AlonDan** [comment]
> but the result.avi is not generated using FFMpeg, it is rather created using OpenCV. So, where is the CRF value for that?

Interesting, I'm not sure why the video that is exported (result.avi) is lower quality, looked like poor compare to the source used than, I thought it's related to CRF value, but I guess I don't know what is the reason if not that. I hope it will be improved in the future because it looks like it's somehow compressing the result.avi or at least do something to the quality in a different way while exporting the final video result.

**Comment by prajwalkr** [comment]
Yes, we are working to release better models.

**Comment by AlonDan** [comment]
> Yes, we are working to release better models.

Sounds great! 
Is there a chance for the new models to be released during this year? 🙏

I tried to understand how to train my own high-quality dataset but since there is no step-by-step tutorial or video to show the process I believe it's very complex to setup.

If I could train (and others as well) we could share different high-quality datasets with each other to expand tests and experiments to get different results, it could be nice.

I hope that somebody who already figure out how to train original dataset for new models will be kind to make a video tutorial so more people will understand how to setup this.
