### ISSUE TITLE
accessible colabs using wav2lip with some novel applications

### ISSUE THREAD

**Issue by eyaler** [Rudrabha/Wav2Lip#196]
hi, i have been working on colabs to make wav2lip more accessible and apply it for some novel applications.
In [j.mp/wav2lip](https://j.mp/wav2lip) you can find a wrapper for wav2lip allowing one-click operation with easy choice of audio, grabbing audio from youtube, manual upload of visual assets, and dealing with cases where the face detection fails. Moreover, there is an option to use **speaker diarization** to remix wav2lip on different images/videos to create a "skit" between several speakers: e.g. [wav2skit demo](https://twitter.com/eyaler/status/1348769977663451136). In [j.mp/vid2head](https://j.mp/vid2head) I have added wav2lip as an optional **post processes** after creating a first-order-motion-model (FOMM) single image animation. the post process takes the audio used in the generated video and tries to improve the lip sync results of FOMM. sometimes this can improve the result. this are part of my [https://github.com/eyaler/avatars4all/](https://github.com/eyaler/avatars4all/) repo. I would be grateful I you would consider adding these to your highlights section.

**Comment by prajwalkr** [comment]
Thanks! Done. In the notebook, can you please link to the Github repo instead of the demo website? Thanks!!

**Comment by eyaler** [comment]
done. thanks!
