### ISSUE TITLE
You shouldn't open this to the public

### ISSUE THREAD

**Issue by misosouplol** [Rudrabha/Wav2Lip#2]
This is only my thought, but it is too powerful for fake news generation and other misuse.
You should whitelist people at least or cancel your "easy demo website"

In any case your work is wonderful, and will be a huge hit !!!

**Comment by Rudrabha** [comment]
Hello, thanks for liking our work. We are putting some restrictions and authentications in place for the interactive demo very soon. We have a presentation in ECCV Demos with this work. We wanted people to use it there, hence the demo is open at the moment. We also want to put strong water-marking and other checks on the results generated from our model. Any more ideas on how to prevent people from mis-using this?

**Comment by misosouplol** [comment]
That should be enough I guess... I don't want to be the party pooper here 🤣
Maybe keeping your own model files (.pth) for you in the future so the people has to train to have some result could be a solution.
Once again, I am just saying that because I am amazed about what you are doing here and how well it works!

**Comment by prajwalkr** [comment]
Thank you very much! We will keep your suggestions in mind! :smile:
