### ISSUE TITLE
How to get higher resolution?

### ISSUE THREAD

**Issue by jbyu** [Rudrabha/Wav2Lip#20]
Hi @Rudrabha ,

What a great work and thanks for sharing it.
I am wondering 

1. How to generate higher resolution output?
2. By cropping face with square area (not resize to 96x96), Will it improve visual quality?

Thank you.

**Comment by Rudrabha** [comment]
Hello,
Thanks for checking out our work.
1. Right now the model can only generate 96 x 96. This is due to the dataset we use to train Wav2Lip. We are currently trying to train a model on higher resolution data. Once trained, we will release it.
2. Currently, the model needs a 96 x 96 face crop as input. It cannot be changed at the moment.

**Comment by zgxiangyang** [comment]
Hi @Rudrabha , Is there public higher resolution data available? Could'you please share it.

**Comment by prajwalkr** [comment]
https://looking-to-listen.github.io/avspeech/download.html

**Comment by AlonDan** [comment]
> https://looking-to-listen.github.io/avspeech/download.html

How do I use these higher quality datasets?
I tried to copy these files to Wav2Lip\checkpoints\  and I renamed them the .csv to .pth
But it doesn't work

Can you please explain how to make these higher resolution models to work?

If there are higher resolution models to download please share the link + how to make it work with wav2lip if it's different than copy them in the checkpoints and use them on the command.

Thanks ahead! :)

**Comment by FacundoMartinezCampos** [comment]
@AlonDan that is not a model for wav2lip, its a dataset.

**Comment by hazemabdelkawy** [comment]
May you share the High quality trained model?

**Comment by AlonDan** [comment]
> May you share the High quality trained model?

Yes please! 💙

**Comment by lidachuan211** [comment]
May you share the High quality trained model?

**Comment by Xuey1nger** [comment]
Hi @Rudrabha ,how should I train on a high quality dataset.I change the img_size as 288×288 and restructure  the model.But I does not get better result than using 96×96.what shoule I change?
