### ISSUE TITLE
Code in model/wave2lip.py not clear

### ISSUE THREAD

**Issue by chetanpandey1266** [Rudrabha/Wav2Lip#201]
![issue](https://user-images.githubusercontent.com/55939332/105225146-2b961980-5b84-11eb-89a4-63431b5d7bf4.png)
![issue1](https://user-images.githubusercontent.com/55939332/105225788-18377e00-5b85-11eb-9329-e39c2161183b.png)

In model/wav2lip.py, you have taken the lower half part as the input for encoder while in paper you have taken the random sampled image and upper half part as the input. Can you elaborate on this part

**Comment by rizwanishaq** [comment]
@chetanpandey1266 the code part you are showing is for the Visual Quality Discriminator, and for Generator part we have reference image concatenated with maksed original image. But for Visual Quality Discriminator we have original image, and comparing it with Generated images. 

(mel, [ref,oring[96//2:,;]=0] ----> gen ----> Generated frames, ---> sync loss + L1 loss


(original_image> ----> Dis ----> real loss
(Generated frames ----> Dis ---> fake loss

**Comment by chetanpandey1266** [comment]
Okay! My Bad
Thanks for making it clear

**Comment by rizwanishaq** [comment]
@chetanpandey1266 Ask as many question, still lots of things are not clear to me as well, but with more discussion we will get the idea, more and more.
