### ISSUE TITLE
How to generate frame?

### ISSUE THREAD

**Issue by HeonKK** [Rudrabha/Wav2Lip#203]
In training process

Input shape of face encoder (batch size * 5, 6, 96, 96), audio (batch size * 5, 1, 80, 16) and model output shape is (batchsize, 3, 5, 96, 96).

In this process, one pair of image(concat half masked image and random reference image) and one mel-spectrogram are generate one image and stacked each generated image?

or five pair of image and five mel-spectrogram are generate five image at once?

**Comment by rizwanishaq** [comment]
@HeonKK according to code, what I understand, that we need to give batch of 5 images (B, 5, 6, 96,96), as input just for calculating expert sync loss, otherwise, the model process each frame independent of other frames, and for audio (B, 5, 1, 80, 16) make sense in training as well, but I am little bit confused about it as how this part of the audio is correspond to 5 images ( B, 5, 6, 96,96), and in inference we only have ( B, 6, 96,69) with audio (B, 1,80,16) (but in reality this shouldn't be equal to 5 images???

**Comment by HeonKK** [comment]
the model process each frame independent of other frames

I wonder 5 mel-spectrograms are used in generate each frame or 1 mel-spectrogram is used in generate 1 frame.

As I understanding your comment, each frame pair make one frame right??


for audio (B, 5, 1, 80, 16) make sense in training as well, but I am little bit confused about it as how this part of the audio is correspond to 5 images ( B, 5, 6, 96,96),

I think 5 audio mels are related with each frames start time, so I understand this part as (1, 1, 80, 16) audio and (1, 6, 96, 96) face images generate 1 image. I can't understand well this part too.

in inference we only have ( B, 6, 96,69) with audio (B, 1,80,16) (but in reality this shouldn't be equal to 5 images

As I said above, in inference B is length of mel-spectrogram.

So at inference time, each mels are related to audio mels.

I hope the answer is helpful, because I am not good at English and beginner in this field..

**Comment by rizwanishaq** [comment]
@HeonKK thanks for the detailed answer, I also need to add something to this

-> In training 5-mels-spectrogram is used for generating 5 images (i.e. 200 msec for each image)
-> In Inference 1-mels is used to generate 1 images. 

So key is that each 200 ms is generating 1 image with step size of (12.5 ms I suppose) (200 samples).

May be one suggestion is take 200 ms and generate 5 images with 40ms step size (25 fps in video), Trying to explore that, lets see how it goes...

**Comment by HeonKK** [comment]
@rizwanishaq 
Thank you for your helpful answer.

It's helped me to solve my curiosity.

If you know about how to extract 5 mel-spectrograms which is related to video sequence?

As I understand this part, selected ground truth frame -1 frame's mel-spectrogram to +3 frame's mel-spectrogram, but i don't know why this model extract -1 to +3 frame's mel-spectrogram.

**Comment by rizwanishaq** [comment]
@HeonKK 
I never noticed that model extract mels frames (-1 to +3) I was thinking it is (-2 to +2), lets ask that question to @prajwalkr ,why it is the case?

**Comment by prajwalkr** [comment]
I think it was because of 0-indexing and 1-indexing of the frame numbers. But an offset of 1 frame should not matter much for the performance.

**Comment by 649459021** [comment]
At traing time, the mels frames is (-2, 2). But at inference time,  I found the mels frames is (0, 5).
Inference.py:
while 1:
		start_idx = int(i * mel_idx_multiplier)
		if start_idx + mel_step_size > len(mel[0]):
			mel_chunks.append(mel[:, len(mel[0]) - mel_step_size:])
			break
		mel_chunks.append(mel[:, start_idx : start_idx + mel_step_size])

I'm confused. @prajwalkr  @Rudrabha     Why use (-2, 2) at inference?
