### ISSUE TITLE
Where is  the missing 'checkpoints/wav2lip_gan.pth' file 

### ISSUE THREAD

**Issue by dzeitman** [Rudrabha/Wav2Lip#204]
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/wav2lip_gan.pth'

**Comment by prajwalkr** [comment]
Download the weights from here: https://github.com/Rudrabha/Wav2Lip#getting-the-weights and place them in the checkpoints folder

**Comment by IljaPilja** [comment]
Hi, I get this same error message but the link that is suppose to provide me with the so-called weights simply sends me to the Wav2lip GitHub page. Where do I obtain these weights from, or more precisely, this *.pth file?
Thanks in advance for the help.
