### ISSUE TITLE
Mels-frame generation for wav2lip train

### ISSUE THREAD

**Issue by rizwanishaq** [Rudrabha/Wav2Lip#209]
I have a question why mels frames are taken from -1 to +3

```
start_frame_num = self.get_frame_id(start_frame) + 1 # 0-indexing ---> 1-indexing
if start_frame_num - 2 < 0: return None
for i in range(start_frame_num, start_frame_num + syncnet_T):
    m = self.crop_audio_window(spec, i - 2)
```

and why not 
-2 to +2 any particular reason?

**Comment by prajwalkr** [comment]
It is taken from (start_frame_num - 2) to (start_frame_num + syncnet_T - 1 - 2)

syncnet_T = 5, hence:
(start_frame_num - 2) to (start_frame_num + 2)

which is -2 to +2

**Comment by rizwanishaq** [comment]
@prajwalkr in code we have 
start_frame_num = self.get_frame_id(start_frame) + 1 
so which make it -1 to +3 if I am not wrong..

**Comment by prajwalkr** [comment]
> start_frame_num = self.get_frame_id(start_frame) + 1

The frame_id follows 0-indexing. By doing +1, we convert it to 1-indexing.

**Comment by Tinkle78** [comment]
def crop_audio_window(self, spec, start_frame):
        if type(start_frame) == int:
            start_frame_num = start_frame
        else:
            start_frame_num = self.get_frame_id(start_frame) # 0-indexing ---> 1-indexing
        start_idx = int(80. * (start_frame_num / float(hparams.fps)))
        
        end_idx = start_idx + syncnet_mel_step_size

        return spec[start_idx : end_idx, :]

    def get_segmented_mels(self, spec, start_frame):
        mels = []
        assert syncnet_T == 5
        start_frame_num = self.get_frame_id(start_frame) + 1 # 0-indexing ---> 1-indexing
        if start_frame_num - 2 < 0: return None
        for i in range(start_frame_num, start_frame_num + syncnet_T):
            m = self.crop_audio_window(spec, i - 2)
            if m.shape[0] != syncnet_mel_step_size:
                return None
            mels.append(m.T)

mel = self.crop_audio_window(orig_mel.copy(), img_name)
indiv_mels = self.get_segmented_mels(orig_mel.copy(), img_name)

Hello parjwalkr, I have the same question as rizwanishaq. If img_name is "3.jpg", the mel which is  the return of crop_audio_window is calculated based on start_frame_num that is 3。But indiv_mels which is used to generate five frames is calculated based on start_frame_num that is 2,3,4,5,6（start_frame_num = get_frame_id(start_frame)+1=4。I think this make it -1 to +3.

Did you forget to write "+1" in the "else" part of the crop_audio_window function? Because it has the same comment as the line of code in the get_segmented_mels function

**Comment by Owen-Fish** [comment]
@Tinkle78 you are right. @prajwalkr make a small mistake for that question.

**Comment by sunjian2015** [comment]
> ```
> def crop_audio_window(self, spec, start_frame):
>     if type(start_frame) == int:
>         start_frame_num = start_frame
>     else:
>         start_frame_num = self.get_frame_id(start_frame) # 0-indexing ---> 1-indexing
>     start_idx = int(80. * (start_frame_num / float(hparams.fps)))
>     
>     end_idx = start_idx + syncnet_mel_step_size
> 
>     return spec[start_idx : end_idx, :]
> 
> def get_segmented_mels(self, spec, start_frame):
>     mels = []
>     assert syncnet_T == 5
>     start_frame_num = self.get_frame_id(start_frame) + 1 # 0-indexing ---> 1-indexing
>     if start_frame_num - 2 < 0: return None
>     for i in range(start_frame_num, start_frame_num + syncnet_T):
>         m = self.crop_audio_window(spec, i - 2)
>         if m.shape[0] != syncnet_mel_step_size:
>             return None
>         mels.append(m.T)
> ```
> 
> mel = self.crop_audio_window(orig_mel.copy(), img_name) indiv_mels = self.get_segmented_mels(orig_mel.copy(), img_name)
> 
> Hello parjwalkr, I have the same question as rizwanishaq. If img_name is "3.jpg", the mel which is the return of crop_audio_window is calculated based on start_frame_num that is 3。But indiv_mels which is used to generate five frames is calculated based on start_frame_num that is 2,3,4,5,6（start_frame_num = get_frame_id(start_frame)+1=4。I think this make it -1 to +3.
> 
> Did you forget to write "+1" in the "else" part of the crop_audio_window function? Because it has the same comment as the line of code in the get_segmented_mels function

so, it is not need +1 here, right?

**Comment by sunjian2015** [comment]
> @Tinkle78 you are right. @prajwalkr make a small mistake for that question.

I think there should be no +1

**Comment by lordlxh** [comment]
start_frame_num = self.get_frame_id(start_frame) + 1 # 0-indexing ---> 1-indexing
if start_frame_num - 2 < 0: return None
for i in range(start_frame_num, start_frame_num + syncnet_T):
    m = self.crop_audio_window(spec, i - 2)

![image](https://github.com/user-attachments/assets/43af65a6-84a4-43f4-b0b0-8a916986488b)

Why do we need -2 here? When we train Syncnet, we only used image_frame_num 0 to 4 to align with mel which is used to generate image_frame_num 0. Shouldn't we follow the same training process as Syncnet？
