### ISSUE TITLE
basic information about synthetic lip

### ISSUE THREAD

**Issue by Adorablepet** [Rudrabha/Wav2Lip#21]
This is a very good project. Thanks for your sharing. When I use my own video and voice synthesis video, the characters in the generated video feel less lips?  Will there be ghosts?  How to adjust this?

**Comment by prajwalkr** [comment]
I am unable to understand the question. Can you elaborate with an example?

**Comment by Adorablepet** [comment]
Is the mouth shape of the characters in the synthesized video that can be clearly seen that they fit together, sometimes it is significantly less?

**Comment by Adorablepet** [comment]
like this, ![image](https://user-images.githubusercontent.com/29625016/92447081-5e4d0000-f1e9-11ea-8f6c-8ccdfb7bbf75.png)

**Comment by prajwalkr** [comment]
those are visual artifacts, and they can come sometimes. You can resolve them using more bottom padding, or reducing the video resolution, both of which are mentioned in the readme. You should also try once with the GAN model if you have not tried it already.

**Comment by Adorablepet** [comment]
thanks, I will try.
