### ISSUE TITLE
KeyError: 'state_dict'

### ISSUE THREAD

**Issue by instant-high** [Rudrabha/Wav2Lip#210]
Running wav2lip on Win10 / Anaconda 3,8 gives me the following error:
KeyError: 'state_dict'

The commandline is:
python inference.py --checkpoint_path C:\Tutorial\wav2lip\face_detection\detection\sfd\s3fd.pth --face d:\temp\ich2.mp4 --audio d:\versicherung.wav

I've downloaded the pretrained model mentioned on the GitHub prerequisites
What am I doing wrong?

![error](https://user-images.githubusercontent.com/77229558/106363213-815a8680-6327-11eb-91e8-21b96e574583.jpg)

**Comment by instant-high** [comment]
OK
wav2lip_gan.pth seems to work...
No sound in output file 
subprocess.py - file not found, maybe ffmpeg ?

**Comment by prajwalkr** [comment]
> subprocess.py - file not found, maybe ffmpeg ?

Yea

**Comment by instant-high** [comment]
Problem already solved. 
Everythings fine now , I've also written a simple GUI for it
Thanks

**Comment by instant-high** [comment]
BTW: setting batch size to 1 solved not enough memory problem running on GPU (2GB Gforce)

--face_det_batch_size 1 --wav2lip_batch_size 1

**Comment by shahidkarimi** [comment]
@instant-high how I solve this for cpu?
