### ISSUE TITLE
Pretrained model on LRS3 dataset

### ISSUE THREAD

**Issue by niladridutt** [Rudrabha/Wav2Lip#211]
Hi,
Can you please release the trained model weights of Wav2Lip and Wav2Lip+GAN on LRS3 dataset if possible?
Also, does the results generated on these weights have better image quality since LRS3 dataset has image crops of 256x256 compared to 128x128 (LRS2)?
Thanks for open sourcing the code.

**Comment by Rudrabha** [comment]
We have never trained a model on the LRS3 dataset. The LRS3 dataset is made up of TED talks which inherently have a darker background and light scheme. We found that it causes unwanted artifacts in the generated images. Additionally, according to us, the amount of extra resolution that can be gained by using that dataset is not significant.

**Comment by niladridutt** [comment]
Thanks for the reply. 
I noticed table 1 on page 6 of your [paper](https://arxiv.org/pdf/2008.10010.pdf) where it talks about the evaluations on LRS3 dataset.
1. Can you suggest some things I could try to get higher image quality results?
2. How long does the actor video be to produce best results? Does the duration of the video have any effect on the result - as in will 1 hr video of the actor produce better results than a 2 min video?

**Comment by Rudrabha** [comment]
We use LRS3 and LRW datasets only for evaluation purposes to show that our model truly works for unseen identities. We mention it in the caption of the same table: "Note that we only train on the train set on LRS2 [1]". 

1. The idea would be to train on a dataset containing high-res videos. A dataset like [AVSpeech ](https://looking-to-listen.github.io/avspeech/download.html) can be used to train. You can try out some other datasets as well. Please go through this [section](https://github.com/Rudrabha/Wav2Lip#training-on-datasets-other-than-lrs2) for getting an idea about the steps that you may have to follow.
2. We have not done this sort of an experiment to give a definitive answer. It might be beneficial to have more data of specific speakers (thus biasing the model towards them). But we cannot guarantee this at the moment without concrete experiments.

**Comment by niladridutt** [comment]
Thanks for your help
