### ISSUE TITLE
Colab fix

### ISSUE THREAD

**Issue by CaptainStabs** [Rudrabha/Wav2Lip#213]
Cell 8 needs to be changed to 
`!cp -ri "/content/gdrive/MyDrive/Wav2Lip/wav2lip_gan.pth" /content/Wav2Lip/checkpoints/` 

I'd do it myself but the notebook doesn't seem to be in this repo

**Comment by Minjun-KANG** [comment]
https://github.com/Rudrabha/Wav2Lip/issues/140
I think it would be better to refer to the link above.
