### ISSUE TITLE
Sync loss problem

### ISSUE THREAD

**Issue by wangzheliu** [Rudrabha/Wav2Lip#214]
I Start train hq_wav2lip_train.py ,only use l1 loss and perceptual_loss ,the sample face looks better and better,but once sync_loss <0.75 , I add sync_loss to train ,however,the sync_loss get bigger,from 0.75 to 18,The resulting face becomes distorted.Have you ever had this problem.can you tell me when  sync_loss =0.75,your L1 loss and perceptual_loss.

**Comment by prajwalkr** [comment]
Which dataset are you training on?

**Comment by wangzheliu** [comment]
> 
> 
> Which dataset are you training on?
my own dataset，about 3 hours，25fps.I fristly use this dataset to  training expert syncnet model，when global_step=600800, train loss is 0.1，eval loss is 0.09. Then I use this expert model to train generator model.

**Comment by prajwalkr** [comment]
Please read this: https://github.com/Rudrabha/Wav2Lip#training-on-datasets-other-than-lrs2. The issues could be anywhere as to why it is not working on custom single speaker datasets.
