### ISSUE TITLE
libomp.dylib not loaded

### ISSUE THREAD

**Issue by JacquesGodin** [Rudrabha/Wav2Lip#216]
When using inference.py I'm getting the following error:

```
File "inference.py", line 7, in <module>
    import torch, face_detection
  File "/Users/jamesdean/opt/anaconda3/envs/wav2vid/lib/python3.6/site-packages/torch/__init__.py", line 79, in <module>
    from torch._C import *
ImportError: dlopen(/Users/jamesdean/opt/anaconda3/envs/wav2vid/lib/python3.6/site-packages/torch/_C.cpython-36m-darwin.so, 9): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /Users/jamesdean/opt/anaconda3/envs/wav2vid/lib/python3.6/site-packages/torch/lib/libshm.dylib
  Reason: image not found
```
I'm using a MacBook Air with Big Sur (version 11.2) with an Intel HD Graphics 6000

**Comment by prajwalkr** [comment]
There is something wrong with your torch installation

**Comment by medhap02** [comment]
@JacquesGodin how did you manage to resolve this issue. I'm running into the same thing

**Comment by JacquesGodin** [comment]
> @JacquesGodin how did you manage to resolve this issue. I'm running into the same thing

I didn’t unfortunately. Sorry I couldn’t help any further

**Comment by zychyz95822** [comment]
I fix with "pip install --upgrade torch"
