### ISSUE TITLE
Train me whether the CPU is running or the GPU

### ISSUE THREAD

**Issue by wowopc** [Rudrabha/Wav2Lip#217]
![11111](https://user-images.githubusercontent.com/23237930/108623534-80c29500-747a-11eb-81ad-6f104f13023b.jpg)
I trained two videos, four seconds in length. Why is it so long
The CPU on the graph is full of GPU 0, which is running on the CPU, boss

**Comment by wowopc** [comment]
This problem is reported in W10 and normal in Ubuntu

**Comment by prajwalkr** [comment]
Please ensure that PyTorch is using the GPU on Windows. Closing this, as it is not a problem in the Wav2Lip code.
