### ISSUE TITLE
Train the expert lip sync discriminator

### ISSUE THREAD

**Issue by wowopc** [Rudrabha/Wav2Lip#218]
Hi, big brother

I pre trained a video using the expert lip sync discriminator

Does the training mouth data need multi-point data? How long does the training mouth data need to be fused

![111111](https://user-images.githubusercontent.com/23237930/109109933-2888dd00-7771-11eb-94f2-3e33b3896035.jpg)
My graphics card is 2070

**Comment by wowopc** [comment]
Why is my training so slow? I only get about 1,000 data a night

**Comment by wowopc** [comment]
![Uploading image.png…]()

**Comment by wowopc** [comment]
![image](https://user-images.githubusercontent.com/23237930/109927047-9e0b2500-7cfe-11eb-8e58-911f04786976.png)

**Comment by wowopc** [comment]
If you want to run to 70W data, how long will it be?
One year?

**Comment by Rudrabha** [comment]
Please check if your code uses CUDA or not.

**Comment by DDDlk** [comment]
I have the same question, have you solved??
