### ISSUE TITLE
Train the Wav2Lip model to freeze and not run 

### ISSUE THREAD

**Issue by wowopc** [Rudrabha/Wav2Lip#219]
wowopc@DESKTOP-HSJ1KM1:/mnt/d/Wav2Lip$
 wav2lipwowopc@DESKTOP-HSJ1KM1:/mnt/d/Wav2Lip$ python3 wav2lip_train.py --data_root lrs2_preprocessed --checkpoint_dir checkpoints t_checkpoint_path checkpoints/lipsync_expert.pth
use_cuda: True
total trainable params 36298035
Load checkpoint from: checkpoints/lipsync_expert.pth
Starting Epoch: 0
0it [00:00, ?it/s]Saved checkpoint: checkpoints/checkpoint_step000000001.pth
Evaluating for 700 steps

Hasn't moved 
There are  heckpoints
 samples_step000000000

**Comment by prajwalkr** [comment]
Ensure that the test file paths are correct. It is most likely that the validation/test data loader is stuck in an infinite loop

**Comment by wowopc** [comment]
The path is right 
I run python3 wav2lip_train.py --data_root lrs2_preprocessed --checkpoint_dir checkpoints --syncnet_checkpoint_path checkpoints/lipsync_expert.pth Just stuck   
But running python3 hq_wav2lip_train.py --data_root lrs2_preprocessed --checkpoint_dir checkpoints --syncnet_checkpoint_path checkpoints/lipsync_expert.pth is normal, very puzzled

**Comment by wowopc** [comment]
Brother i run 
python3 hq_wav2lip_train.py --data_root lrs2_preprocessed --checkpoint_dir checkpoints --syncnet_checkpoint_path checkpoints/lipsync_expert.pth  get
L1: 0.04055480286478996, Sync: 0.0, Percep: 0.0 | Fake: 100.0, Real: 0.0: : 1it [00:06,  6.03s/it]
Starting Epoch: 834
L1: 0.0391601137816906, Sync: 0.0, Percep: 0.0 | Fake: 100.0, Real: 0.0: : 1it [00:06,  6.00s/it]
Starting Epoch: 835
0it [00:00, ?it/s]
L1: 0.03869321197271347, Sync: 0.0, Percep: 0.0 | Fake: 100.0, Real: 0.0: : 1it [00:06,  6.42s/it]
Starting Epoch: 836
L1: 0.04593410715460777, Sync: 0.0, Percep: 0.0 | Fake: 100.0, Real: 0.0: : 1it [00:06,  6.16s/it]
Starting Epoch: 837
L1: 0.03871723264455795, Sync: 0.0, Percep: 0.0 | Fake: 100.0, Real: 0.0: : 1it [00:06,  6.20s/it]
Starting Epoch: 838
L1: 0.04055677726864815, Sync: 0.0, Percep: 0.0 | Fake: 100.0, Real: 0.0: : 1it [00:06,  6.27s/it]
Starting Epoch: 839
0it [00:00, ?it/s]
L1: 0.03807450458407402, Sync: 0.0, Percep: 0.0 | Fake: 100.0, Real: 0.0: : 1it [00:06,  6.48s/it]
Starting Epoch: 840
L1: 0.03997894003987312, Sync: 0.0, Percep: 0.0 | Fake: 100.0, Real: 0.0: : 1it [00:06,  6.23s/it]
Starting Epoch: 841
L1: 0.03780364617705345, Sync: 0.0, Percep: 0.0 | Fake: 100.0, Real: 0.0: : 1it [00:06,  6.17s/it]
Starting Epoch: 842
L1: 0.046111639589071274, Sync: 0.0, Percep: 0.0 | Fake: 100.0, Real: 0.0: : 1it [00:06,  6.03s/it]
Starting Epoch: 843
L1: 0.03653215616941452, Sync: 0.0, Percep: 0.0 | Fake: 100.0, Real: 0.0: : 1it [00:06,  6.13s/it]
Starting Epoch: 844
L1: 0.03948122262954712, Sync: 0.0, Percep: 0.0 | Fake: 100.0, Real: 0.0: : 1it [00:06,  6.37s/it]
Starting Epoch: 845
L1: 0.03920793533325195, Sync: 0.0, Percep: 0.0 | Fake: 100.0, Real: 0.0: : 1it [00:06,  6.36s/it]
Starting Epoch: 846
0it [00:00, ?it/s] Is this closed?

**Comment by wowopc** [comment]
Is it necessary to train clear characters in the third position of the picture? 
![Uploading 0_0.jpg…]()

**Comment by DDDlk** [comment]
> Brother i run
> python3 hq_wav2lip_train.py --data_root lrs2_preprocessed --checkpoint_dir checkpoints --syncnet_checkpoint_path checkpoints/lipsync_expert.pth get
> L1: 0.04055480286478996, Sync: 0.0, Percep: 0.0 | Fake: 100.0, Real: 0.0: : 1it [00:06, 6.03s/it]
> Starting Epoch: 834
> L1: 0.0391601137816906, Sync: 0.0, Percep: 0.0 | Fake: 100.0, Real: 0.0: : 1it [00:06, 6.00s/it]
> Starting Epoch: 835
> 0it [00:00, ?it/s]
> L1: 0.03869321197271347, Sync: 0.0, Percep: 0.0 | Fake: 100.0, Real: 0.0: : 1it [00:06, 6.42s/it]
> Starting Epoch: 836
> L1: 0.04593410715460777, Sync: 0.0, Percep: 0.0 | Fake: 100.0, Real: 0.0: : 1it [00:06, 6.16s/it]
> Starting Epoch: 837
> L1: 0.03871723264455795, Sync: 0.0, Percep: 0.0 | Fake: 100.0, Real: 0.0: : 1it [00:06, 6.20s/it]
> Starting Epoch: 838
> L1: 0.04055677726864815, Sync: 0.0, Percep: 0.0 | Fake: 100.0, Real: 0.0: : 1it [00:06, 6.27s/it]
> Starting Epoch: 839
> 0it [00:00, ?it/s]
> L1: 0.03807450458407402, Sync: 0.0, Percep: 0.0 | Fake: 100.0, Real: 0.0: : 1it [00:06, 6.48s/it]
> Starting Epoch: 840
> L1: 0.03997894003987312, Sync: 0.0, Percep: 0.0 | Fake: 100.0, Real: 0.0: : 1it [00:06, 6.23s/it]
> Starting Epoch: 841
> L1: 0.03780364617705345, Sync: 0.0, Percep: 0.0 | Fake: 100.0, Real: 0.0: : 1it [00:06, 6.17s/it]
> Starting Epoch: 842
> L1: 0.046111639589071274, Sync: 0.0, Percep: 0.0 | Fake: 100.0, Real: 0.0: : 1it [00:06, 6.03s/it]
> Starting Epoch: 843
> L1: 0.03653215616941452, Sync: 0.0, Percep: 0.0 | Fake: 100.0, Real: 0.0: : 1it [00:06, 6.13s/it]
> Starting Epoch: 844
> L1: 0.03948122262954712, Sync: 0.0, Percep: 0.0 | Fake: 100.0, Real: 0.0: : 1it [00:06, 6.37s/it]
> Starting Epoch: 845
> L1: 0.03920793533325195, Sync: 0.0, Percep: 0.0 | Fake: 100.0, Real: 0.0: : 1it [00:06, 6.36s/it]
> Starting Epoch: 846
> 0it [00:00, ?it/s] Is this closed?

hello,I got the same log as you, is this right?Thank you!
