### ISSUE TITLE
What files need to be modified for training HD 

### ISSUE THREAD

**Issue by wowopc** [Rudrabha/Wav2Lip#220]
Modify the file hparam 
img_size=96，increase  ?264？
	fps=25，
Where is the neural network architecture modified ？

**Comment by wowopc** [comment]
Modify file wav2lip.py ？
If I need to train a 960*540 video, how do I set it up?

**Comment by wowopc** [comment]
Change the model architecture to accommodate more high-resolution faces 
How to modify?

**Comment by prajwalkr** [comment]
Training on high resolution videos needs a lot of changes, and it is a work in progress from our side.

**Comment by burning846** [comment]
> Training on high resolution videos needs a lot of changes, and it is a work in progress from our side.
any progress？
