### ISSUE TITLE
Why do I use this model(wav2lip_gan_base.pth) to generate a video with a mask on it, which makes it unclear?

### ISSUE THREAD

**Issue by iamchenxin-coder** [Rudrabha/Wav2Lip#222]
Hello, I use this model to input the video generated by picture 1. I feel that there is a layer of mask on it, which is not clear. What's the matter? How can I remove it？sorry，the video can't be uploaded

**Comment by prajwalkr** [comment]
Sorry, I do not understand your question. What mask are you talking about? what is the picture 1?

**Comment by iamchenxin-coder** [comment]
![input_static_image](https://user-images.githubusercontent.com/74162528/109769277-efe77880-7c34-11eb-9449-3f1ea624dec3.jpg)

**Comment by iamchenxin-coder** [comment]
Because my computer can't upload pictures with too much memory, I will reduce the image of the generated video and send it to you for a look. This picture is generated by wav2lip + Gan, but there is a layer of template on it, which makes the whole video unclear
![video_with_mask](https://user-images.githubusercontent.com/74162528/109769807-ae0b0200-7c35-11eb-81f5-f9c2f6c1f971.jpg)

**Comment by Rudrabha** [comment]
We concatenate a reference frame (from any random time step) and the GT frame with the lower half masked (during training). This is to provide the model with the target head pose information without leaking the lip shape (GT frame contains the GT lip shape). During inference at any time step, we concatenate the lower half masked frame with itself. This is the masking step you find in this [line](https://github.com/Rudrabha/Wav2Lip/blob/403bc711dfb70171c09233ba9cf765b290f76e32/inference.py#L149). I think the face detection failed for this particular example. Probably the face was detected above the real face, and the lower half mask meant that the forehead region was masked out.
