### ISSUE TITLE
Cannot get the inference to run on Windows 10 (Anaconda)

### ISSUE THREAD

**Issue by tushar-31093** [Rudrabha/Wav2Lip#228]
![image](https://user-images.githubusercontent.com/40886260/111104674-3c0cb400-8577-11eb-9f28-98efd16b17cc.png)
![image](https://user-images.githubusercontent.com/40886260/111104702-4929a300-8577-11eb-8217-1be8cef1b5ac.png)

After cloning and installing all the necessary libraries, there seems to be an issue running the last FFmpeg command. At the same time, if I use just an image and audio for the animation, it shows that the GPU cannot handle it and breaks. I have added the FFmpeg library to the path as well, just in case it needed that. 

Could you guide me on how to make it work hereon? Screenshots attached.

**Comment by tushar-31093** [comment]
![image](https://user-images.githubusercontent.com/40886260/111105476-11235f80-8579-11eb-95ea-982e25ef0e8d.png)

After modifying the last line regarding FFmpeg, this is the error I'm getting.

**Comment by prajwalkr** [comment]
Is the result.avi generated? Can you run the FFMPEG command manually and check if that works?

**Comment by Rudrabha** [comment]
Please re-open the issue in case the problem persists.
