### ISSUE TITLE
ImportError: No module named 'cv2'"

### ISSUE THREAD

**Issue by FarangoJones** [Rudrabha/Wav2Lip#23]
I tried the following command : "python inference.py --checkpoint_path checkpoints/wav2lip_gan.pth  --face video.mp4 --audio audio.wav" but I'm getting this error : 

"Traceback (most recent call last):
  File "inference.py", line 3, in <module>
    import scipy, cv2, os, sys, argparse, audio
ImportError: No module named 'cv2'"

What should I do to fix this ? I'm on python 3.5.6.

**Comment by Rudrabha** [comment]
```pip install -r requirements.txt```
Please follow the steps given in the Readme thoroughly to run the code.
