### ISSUE TITLE
Changing the size of the image generated by the preprocessing script

### ISSUE THREAD

**Issue by miteshyadav** [Rudrabha/Wav2Lip#230]
Hi all. Thanks you for open-sourcing this amazing project.

I'm trying to re-train the model on a HD quality AVSpeech dataset in order to get better quality videos. The output from the pre-processing script is always a 96 x 96 image. How do I change the image size to output bigger and better quality image frames in the pre-processed files? I couldn't find any variable that pertains to the image size. Thank you

**Comment by prajwalkr** [comment]
I do not think the preprocessing yields a constant size image. The training and testing scripts handle constant size face though. Are you talking about preprocess.py though?

**Comment by miteshyadav** [comment]
Yes, the out put of the preprocess.py files always give an image size of 96 by 96. I am trying to get a bigger and better quality imageset to feed it to the neural network to get better results.  Is that the right approach?

Also, you guys mentioned about training the dataset on an HD model. Is there any progress made on that end? When do you plan to release the model trained from HD dataset

**Comment by Rudrabha** [comment]
We do not have plans to publicly release the HD model. We are in the process of submitting a extended version of this paper in a journal.
