### ISSUE TITLE
How should I set it？

### ISSUE THREAD

**Issue by DWCTOD** [Rudrabha/Wav2Lip#235]
First of all, thanks for this awesome project. 
I try to retrain this model. But the result is not very well for me. Because of syncnet model,  I'm confused about how long should I
set the train data ( vdeo time).
I found the LRS2 dataset that each video time is about 1~5s, but my dataset is not like this.What does that lead to? Can you give me a hand?Thanks , waiting for your reply.

**Comment by prajwalkr** [comment]
You can crop your videos to short segments, but you should have enough number of hours (LRS2 is 29 hours). The data also needs to be sync corrected.

**Comment by DWCTOD** [comment]
> You can crop your videos to short segments, but you should have enough number of hours (LRS2 is 29 hours). The data also needs to be sync corrected.

Thanks 
I have try crop  train data, the syncnet model is train Ok. But for wav2lip can't fitting well, maybe my train data is too little.

**Comment by Rudrabha** [comment]
Please re-open the issue if needed.

**Comment by Quanta-of-solitude** [comment]
It's been a year, I would like to know about your results, coupd you share? @DWCTOD :)
