### ISSUE TITLE
Training with higher FPS

### ISSUE THREAD

**Issue by shehrum** [Rudrabha/Wav2Lip#236]
In the readme, it is mentioned that changes in FPS require significant code changes. I am trying to train on a custom dataset. Can someone point out what changes do I need to make in order to cater for 30 FPS. Any help would be appreciated, thankyou!

I am guessing some changes are to be made here in color_syncnet_train.py:

>     def crop_audio_window(self, spec, start_frame):
>         # num_frames = (T x hop_size * fps) / sample_rate
>         start_frame_num = self.get_frame_id(start_frame)
>         start_idx = int(80. * (start_frame_num / float(hparams.fps)))
>         end_idx = start_idx + syncnet_mel_step_size
> 
>         return spec[start_idx : end_idx, :]
>

**Comment by codehearted** [comment]
There is a parameter in hparams.py called "fps" that defaults to 25. I have been using Wav2Lip with it set to 30, though I haven't done a before/after test comparing it to 25 to see the difference. It looks like this would be taken into account in your code above on the fifth line, though other changes may be necessary.

**Comment by shehrum** [comment]
Thankyou for your response. Did you make other changes to the original code to cater for 30fps? Or did it train just fine?

**Comment by codehearted** [comment]
Well, I'm having problems with color_syncnet_train, the pattern of loss over steps looks like a random float generator, it's not consistently going down at all. But I don't know if that is related the the fps change. My guess is that it is not. The final stage of training (in either form) does seem to have it's loss go down as you would expect, but my best loss value for the syncnet is not very good at all, so I don't have good output on my trained network yet. It's a work in progress. But I'm hoping I can figure out what is going on with the non-reducing loss on syncnet, I think that's a separate issue.

**Comment by narayanan-ka** [comment]
@codehearted Are any public available datasets available which you are using other than lrs2
