### ISSUE TITLE
Tried to install on MacOS Big Sur and some python libraries were not found for the text file

### ISSUE THREAD

**Issue by inglesuniversal** [Rudrabha/Wav2Lip#237]
Please update requirements.txt

I tried to change the missing libraries, but made a total mess by mixing versions I am not familiar with.

Excellent project, our English Learning School (which is about to turn 25 years of existence) would great appreciate your support on this project.

Best regards.

These is how I updated the requirements.txt

librosa==0.7.0
numpy==1.19.3
opencv-contrib-python>=4.2.0.34
opencv-python==4.4.0.46
torch==1.7.1
torchvision==0.8.2
tqdm==4.45.0
numba==0.48

::: THREW A LOT OF ERRORS

**Comment by prajwalkr** [comment]
Could you post the errors you received with the original requirements.txt?

**Comment by inglesuniversal** [comment]
Hi, thanks for your prompt reply... using the origina requirements.txt ... I almost immediately got this error:

Collecting librosa==0.7.0
  Using cached librosa-0.7.0-py3-none-any.whl
Collecting numpy==1.17.1
  Using cached numpy-1.17.1.zip (6.5 MB)
Collecting opencv-contrib-python>=4.2.0.34
  Using cached opencv_contrib_python-4.5.1.48-cp39-cp39-macosx_10_13_x86_64.whl (51.3 MB)

ERROR: Could not find a version that satisfies the requirement opencv-python==4.1.0.25
ERROR: No matching distribution found for opencv-python==4.1.0.25

Thanks

**Comment by prajwalkr** [comment]
We have not tested this on MacOS. Can you change the OpenCV version in the requirements.txt file to some close, but available version and try?

**Comment by inglesuniversal** [comment]
4.4.0.40 DID work, however during installation I got the following error...

% pip3 install -r requirements.txt
Collecting librosa==0.7.0
  Using cached librosa-0.7.0-py3-none-any.whl
Collecting numpy==1.17.1
  Using cached numpy-1.17.1.zip (6.5 MB)
Collecting opencv-contrib-python>=4.2.0.34
  Using cached opencv_contrib_python-4.5.1.48-cp39-cp39-macosx_10_13_x86_64.whl (51.3 MB)
Collecting opencv-python==4.4.0.40
  Downloading opencv-python-4.4.0.40.tar.gz (88.9 MB)
     |████████████████████████████████| 88.9 MB 2.1 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done

ERROR: Could not find a version that satisfies the requirement torch==1.1.0
ERROR: No matching distribution found for torch==1.1.0

**Comment by inglesuniversal** [comment]
Morning... Should I take the same approach and look for the next version up for "torch"? >= torch==1.1.0

Thanks... I did not want to do things on my own and then mess the installation again LOL

**Comment by ThePieMonster** [comment]
I am on Windows 10 and I have to use the following for my requirements.txt.

If this repo needs specific version then those packages should be copied to a private repo that others can pull from. The versions listed in the current commit are outdated / no longer exist. 

```
librosa==0.7.0
numpy==1.17.1
opencv-contrib-python>=4.2.0.34
opencv-python==4.1.0.25
torch==1.8.1
torchvision==0.9.1
tqdm==4.45.0
numba==0.48
```

**Comment by inglesuniversal** [comment]
This combination worked...

librosa==0.7.0
numpy==1.19.3
opencv-contrib-python>=4.2.0.34
opencv-python==4.4.0.40
torch==1.8.1
torchvision==0.9.1
tqdm==4.45.0
numba==0.48

But... after about 30 min.... of build wheel...

Successfully built librosa numba opencv-python audioread resampy
Failed to build llvmlite
Installing collected packages: llvmlite, typing-extensions, threadpoolctl, six, scipy, numba, joblib, cffi, torch, soundfile, scikit-learn, resampy, decorator, audioread, tqdm, torchvision, opencv-python, opencv-contrib-python, librosa
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/cw/mcvz3t0n7nj45hw2nkg96b6m0000gn/T/pip-install-6mr5jw28/llvmlite_e33a53a0c56242449d94e4d8763b30e4/setup.py'"'"'; __file__='"'"'/private/var/folders/cw/mcvz3t0n7nj45hw2nkg96b6m0000gn/T/pip-install-6mr5jw28/llvmlite_e33a53a0c56242449d94e4d8763b30e4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/cw/mcvz3t0n7nj45hw2nkg96b6m0000gn/T/pip-record-rdyn5c0u/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/llvmlite
         cwd: /private/var/folders/cw/mcvz3t0n7nj45hw2nkg96b6m0000gn/T/pip-install-6mr5jw28/llvmlite_e33a53a0c56242449d94e4d8763b30e4/
    Complete output (29 lines):
    running install
    running build
    got version from file /private/var/folders/cw/mcvz3t0n7nj45hw2nkg96b6m0000gn/T/pip-install-6mr5jw28/llvmlite_e33a53a0c56242449d94e4d8763b30e4/llvmlite/_version.py {'version': '0.31.0', 'full': 'fe7d985f6421d87f613bd414479d29d912771562'}
    running build_ext
    /usr/local/opt/python@3.9/bin/python3.9 /private/var/folders/cw/mcvz3t0n7nj45hw2nkg96b6m0000gn/T/pip-install-6mr5jw28/llvmlite_e33a53a0c56242449d94e4d8763b30e4/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/private/var/folders/cw/mcvz3t0n7nj45hw2nkg96b6m0000gn/T/pip-install-6mr5jw28/llvmlite_e33a53a0c56242449d94e4d8763b30e4/ffi/build.py", line 105, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 505, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1823, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/private/var/folders/cw/mcvz3t0n7nj45hw2nkg96b6m0000gn/T/pip-install-6mr5jw28/llvmlite_e33a53a0c56242449d94e4d8763b30e4/ffi/build.py", line 168, in <module>
        main()
      File "/private/var/folders/cw/mcvz3t0n7nj45hw2nkg96b6m0000gn/T/pip-install-6mr5jw28/llvmlite_e33a53a0c56242449d94e4d8763b30e4/ffi/build.py", line 162, in main
        main_posix('osx', '.dylib')
      File "/private/var/folders/cw/mcvz3t0n7nj45hw2nkg96b6m0000gn/T/pip-install-6mr5jw28/llvmlite_e33a53a0c56242449d94e4d8763b30e4/ffi/build.py", line 107, in main_posix
        raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/usr/local/opt/python@3.9/bin/python3.9' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/cw/mcvz3t0n7nj45hw2nkg96b6m0000gn/T/pip-install-6mr5jw28/llvmlite_e33a53a0c56242449d94e4d8763b30e4/setup.py'"'"'; __file__='"'"'/private/var/folders/cw/mcvz3t0n7nj45hw2nkg96b6m0000gn/T/pip-install-6mr5jw28/llvmlite_e33a53a0c56242449d94e4d8763b30e4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/cw/mcvz3t0n7nj45hw2nkg96b6m0000gn/T/pip-record-rdyn5c0u/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/llvmlite Check the logs for full command output.


Any clues?

**Comment by Rudrabha** [comment]
Can you try using python 3.5 instead of 3.9?
