### ISSUE TITLE
What is the recommend video dimension size?

### ISSUE THREAD

**Issue by MZhang88** [Rudrabha/Wav2Lip#242]
Hi,

Every video I use for the Wav2Lip keeps telling me to resize ( --resize_factor). Can you please tell me what is the recommend video dimension size? Also, I'm new to all of this and I was wondering if you could spare a few mins and tell me how to I run the --resize_factor? I see no button for this :(. I'm novice.

Thanks

**Comment by mrlogick** [comment]
I'm having the same issue here: "Image too big to run face detection on GPU. Please use the --resize_factor argument"

**Comment by Rudrabha** [comment]
We generally recommend, 480p or 720p video as standard for this model. If you have a 1080p, please use --resize_factor 2 to get a 720p output during inference.
