### ISSUE TITLE
Grey or Blue Colored Videos being produced

### ISSUE THREAD

**Issue by MesumRaza** [Rudrabha/Wav2Lip#243]
![image](https://user-images.githubusercontent.com/22402962/113456793-ad79ad00-9427-11eb-8309-32c95a0305fe.png)

Please check. I have tried cv2.BGR2RGB or cv2.GRAY2RGB 

But doesnt work

**Comment by Rudrabha** [comment]
Can you share the original video?

**Comment by MesumRaza** [comment]
In the last line I had to cv2.cvtColor(f, cv2.COLOR_BGR2RGB) when final frames are written

**Comment by MesumRaza** [comment]
Mistakenly commented here, here is the fix: https://github.com/ml4a/ml4a/pull/69
