### ISSUE TITLE
Using HQ_ wav2lip_ train.py error

### ISSUE THREAD

**Issue by wowopc** [Rudrabha/Wav2Lip#247]
) ➜  Wav2Lip-master python3 hq_wav2lip_train.py --data_root lrs2_preprocessed/data_root --checkpoint_dir color_sync --syncnet_checkpoint_path color_sync/checkpoint_step000036000.pth

use_cuda: True
total trainable params 40431411
total DISC trainable params 17391105
Load checkpoint from: color_sync/checkpoint_step000036000.pth
Traceback (most recent call last):
  File "hq_wav2lip_train.py", line 435, in <module>
    overwrite_global_states=False)
  File "hq_wav2lip_train.py", line 385, in load_checkpoint
    model.load_state_dict(new_s)
  File "/environment/python/versions/miniconda3-4.7.12/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for SyncNet_color:
        Missing key(s) in state_dict: "face_encoder.0.conv_block.0.weight", "face_encoder.0.conv_block.0.bias", "face_encoder.0.conv_block.1.weight", "face_encoder.0.conv_block.1.bias", "face_encoder.0.conv_block.1.running_mean", "face_encoder.0.conv_block.1.running_var", "face_encoder.1.conv_block.0.weight", "face_encoder.1.conv_block.0.bias", "face_encoder.1.conv_block.1.weight", "face_encoder.1.conv_block.1.bias", "face_encoder.1.conv_block.1.running_mean", "face_encoder.1.conv_block.1.running_var", "face_encoder.2.conv_block.0.weight", "face_encoder.2.conv_block.0.bias", "face_encoder.2.conv_block.1.weight", "face_encoder.2.conv_block.1.bias", "face_encoder.2.conv_block.1.running_mean", "face_encoder.2.conv_block.1.running_var", "face_encoder.3.conv_block.0.weight", "face_encoder.3.conv_block.0.bias", "face_encoder.3.conv_block.1.weight", "face_encoder.3.conv_block.1.bias", "face_encoder.3.conv_block.1.running_mean", "face_encoder.3.conv_block.1.running_var", "face_encoder.4.conv_block.0.weight", "face_encoder.4.conv_block.0.bias", "face_encoder.4.conv_block.1.weight", "face_encoder.4.conv_block.1.bias", "face_encoder.4.conv_block.1.running_mean", "face_encoder.4.conv_block.1.running_var", "face_encoder.5.conv_block.0.weight", "face_encoder.5.conv_block.0.bias", "face_encoder.5.conv_block.1.weight", "face_encoder.5.conv_block.1.bias", "face_encoder.5.conv_block.1.running_mean", "face_encoder.5.conv_block.1.running_var", "face_encoder.6.conv_block.0.weight", "face_encoder.6.conv_block.0.bias", "face_encoder.6.conv_block.1.weight", "face_encoder.6.conv_block.1.bias", "face_encoder.6.conv_block.1.running_mean", "face_encoder.6.conv_block.1.running_var", "face_encoder.7.conv_block.0.weight", "face_encoder.7.conv_block.0.bias", "face_encoder.7.conv_block.1.weight", "face_encoder.7.conv_block.1.bias", "face_encoder.7.conv_block.1.running_mean", "face_encoder.7.conv_block.1.running_var", "face_encoder.8.conv_block.0.weight", "face_encoder.8.conv_block.0.bias", "face_encoder.8.conv_block.1.weight", "face_encoder.8.conv_block.1.bias", "face_encoder.8.conv_block.1.running_mean", "face_encoder.8.conv_block.1.running_var", "face_encoder.9.conv_block.0.weight", "face_encoder.9.conv_block.0.bias", "face_encoder.9.conv_block.1.weight", "face_encoder.9.conv_block.1.bias", "face_encoder.9.conv_block.1.running_mean", "face_encoder.9.conv_block.1.running_var", "face_encoder.10.conv_block.0.weight", "face_encoder.10.conv_block.0.bias", "face_encoder.10.conv_block.1.weight", "face_encoder.10.conv_block.1.bias", "face_encoder.10.conv_block.1.running_mean", "face_encoder.10.conv_block.1.running_var", "face_encoder.11.conv_block.0.weight", "face_encoder.11.conv_block.0.bias", "face_encoder.11.conv_block.1.weight", "face_encoder.11.conv_block.1.bias", "face_encoder.11.conv_block.1.running_mean", "face_encoder.11.conv_block.1.running_var", "face_encoder.12.conv_block.0.weight", "face_encoder.12.conv_block.0.bias", "face_encoder.12.conv_block.1.weight", "face_encoder.12.conv_block.1.bias", "face_encoder.12.conv_block.1.running_mean", "face_encoder.12.conv_block.1.running_var", "face_encoder.13.conv_block.0.weight", "face_encoder.13.conv_block.0.bias", "face_encoder.13.conv_block.1.weight", "face_encoder.13.conv_block.1.bias", "face_encoder.13.conv_block.1.running_mean", "face_encoder.13.conv_block.1.running_var", "face_encoder.14.conv_block.0.weight", "face_encoder.14.conv_block.0.bias", "face_encoder.14.conv_block.1.weight", "face_encoder.14.conv_block.1.bias", "face_encoder.14.conv_block.1.running_mean", "face_encoder.14.conv_block.1.running_var", "face_encoder.15.conv_block.0.weight", "face_encoder.15.conv_block.0.bias", "face_encoder.15.conv_block.1.weight", "face_encoder.15.conv_block.1.bias", "face_encoder.15.conv_block.1.running_mean", "face_encoder.15.conv_block.1.running_var", "face_encoder.16.conv_block.0.weight", "face_encoder.16.conv_block.0.bias", "face_encoder.16.conv_block.1.weight", "face_encoder.16.conv_block.1.bias", "face_encoder.16.conv_block.1.running_mean", "face_encoder.16.conv_block.1.running_var", "face_encoder.17.conv_block.0.weight", "face_encoder.17.conv_block.0.bias", "face_encoder.17.conv_block.1.weight", "face_encoder.17.conv_block.1.bias", "face_encoder.17.conv_block.1.running_mean", "face_encoder.17.conv_block.1.running_var", "face_encoder.18.conv_block.0.weight", "face_encoder.18.conv_block.0.bias", "face_encoder.18.conv_block.1.weight", "face_encoder.18.conv_block.1.bias", "face_encoder.18.conv_block.1.running_mean", "face_encoder.18.conv_block.1.running_var", "face_encoder.19.conv_block.0.weight", "face_encoder.19.conv_block.0.bias", "face_encoder.19.conv_block.1.weight", "face_encoder.19.conv_block.1.bias", "face_encoder.19.conv_block.1.running_mean", "face_encoder.19.conv_block.1.running_var", "audio_encoder.13.conv_block.0.weight", "audio_encoder.13.conv_block.0.bias", "audio_encoder.13.conv_block.1.weight", "audio_encoder.13.conv_block.1.bias", "audio_encoder.13.conv_block.1.running_mean", "audio_encoder.13.conv_block.1.running_var". 
        Unexpected key(s) in state_dict: "face_encoder_blocks.0.0.conv_block.0.weight", "face_encoder_blocks.0.0.conv_block.0.bias", "face_encoder_blocks.0.0.conv_block.1.weight", "face_encoder_blocks.0.0.conv_block.1.bias", "face_encoder_blocks.0.0.conv_block.1.running_mean", "face_encoder_blocks.0.0.conv_block.1.running_var", "face_encoder_blocks.0.0.conv_block.1.num_batches_tracked", "face_encoder_blocks.1.0.conv_block.0.weight", "face_encoder_blocks.1.0.conv_block.0.bias", "face_encoder_blocks.1.0.conv_block.1.weight", "face_encoder_blocks.1.0.conv_block.1.bias", "face_encoder_blocks.1.0.conv_block.1.running_mean", "face_encoder_blocks.1.0.conv_block.1.running_var", "face_encoder_blocks.1.0.conv_block.1.num_batches_tracked", "face_encoder_blocks.1.1.conv_block.0.weight", "face_encoder_blocks.1.1.conv_block.0.bias", "face_encoder_blocks.1.1.conv_block.1.weight", "face_encoder_blocks.1.1.conv_block.1.bias", "face_encoder_blocks.1.1.conv_block.1.running_mean", "face_encoder_blocks.1.1.conv_block.1.running_var", "face_encoder_blocks.1.1.conv_block.1.num_batches_tracked", "face_encoder_blocks.1.2.conv_block.0.weight", "face_encoder_blocks.1.2.conv_block.0.bias", "face_encoder_blocks.1.2.conv_block.1.weight", "face_encoder_blocks.1.2.conv_block.1.bias", "face_encoder_blocks.1.2.conv_block.1.running_mean", "face_encoder_blocks.1.2.conv_block.1.running_var", "face_encoder_blocks.1.2.conv_block.1.num_batches_tracked", "face_encoder_blocks.2.0.conv_block.0.weight", "face_encoder_blocks.2.0.conv_block.0.bias", "face_encoder_blocks.2.0.conv_block.1.weight", "face_encoder_blocks.2.0.conv_block.1.bias", "face_encoder_blocks.2.0.conv_block.1.running_mean", "face_encoder_blocks.2.0.conv_block.1.running_var", "face_encoder_blocks.2.0.conv_block.1.num_batches_tracked", "face_encoder_blocks.2.1.conv_block.0.weight", "face_encoder_blocks.2.1.conv_block.0.bias", "face_encoder_blocks.2.1.conv_block.1.weight", "face_encoder_blocks.2.1.conv_block.1.bias", "face_encoder_blocks.2.1.conv_block.1.running_mean", "face_encoder_blocks.2.1.conv_block.1.running_var", "face_encoder_blocks.2.1.conv_block.1.num_batches_tracked", "face_encoder_blocks.2.2.conv_block.0.weight", "face_encoder_blocks.2.2.conv_block.0.bias", "face_encoder_blocks.2.2.conv_block.1.weight", "face_encoder_blocks.2.2.conv_block.1.bias", "face_encoder_blocks.2.2.conv_block.1.running_mean", "face_encoder_blocks.2.2.conv_block.1.running_var", "face_encoder_blocks.2.2.conv_block.1.num_batches_tracked", "face_encoder_blocks.2.3.conv_block.0.weight", "face_encoder_blocks.2.3.conv_block.0.bias", "face_encoder_blocks.2.3.conv_block.1.weight", "face_encoder_blocks.2.3.conv_block.1.bias", "face_encoder_blocks.2.3.conv_block.1.running_mean", "face_encoder_blocks.2.3.conv_block.1.running_var", "face_encoder_blocks.2.3.conv_block.1.num_batches_tracked", "face_encoder_blocks.3.0.conv_block.0.weight", "face_encoder_blocks.3.0.conv_block.0.bias", "face_encoder_blocks.3.0.conv_block.1.weight", "face_encoder_blocks.3.0.conv_block.1.bias", "face_encoder_blocks.3.0.conv_block.1.running_mean", "face_encoder_blocks.3.0.conv_block.1.running_var", "face_encoder_blocks.3.0.conv_block.1.num_batches_tracked", "face_encoder_blocks.3.1.conv_block.0.weight", "face_encoder_blocks.3.1.conv_block.0.bias", "face_encoder_blocks.3.1.conv_block.1.weight", "face_encoder_blocks.3.1.conv_block.1.bias", "face_encoder_blocks.3.1.conv_block.1.running_mean", "face_encoder_blocks.3.1.conv_block.1.running_var", "face_encoder_blocks.3.1.conv_block.1.num_batches_tracked", "face_encoder_blocks.3.2.conv_block.0.weight", "face_encoder_blocks.3.2.conv_block.0.bias", "face_encoder_blocks.3.2.conv_block.1.weight", "face_encoder_blocks.3.2.conv_block.1.bias", "face_encoder_blocks.3.2.conv_block.1.running_mean", "face_encoder_blocks.3.2.conv_block.1.running_var", "face_encoder_blocks.3.2.conv_block.1.num_batches_tracked", "face_encoder_blocks.4.0.conv_block.0.weight", "face_encoder_blocks.4.0.conv_block.0.bias", "face_encoder_blocks.4.0.conv_block.1.weight", "face_encoder_blocks.4.0.conv_block.1.bias", "face_encoder_blocks.4.0.conv_block.1.running_mean", "face_encoder_blocks.4.0.conv_block.1.running_var", "face_encoder_blocks.4.0.conv_block.1.num_batches_tracked", "face_encoder_blocks.4.1.conv_block.0.weight", "face_encoder_blocks.4.1.conv_block.0.bias", "face_encoder_blocks.4.1.conv_block.1.weight", "face_encoder_blocks.4.1.conv_block.1.bias", "face_encoder_blocks.4.1.conv_block.1.running_mean", "face_encoder_blocks.4.1.conv_block.1.running_var", "face_encoder_blocks.4.1.conv_block.1.num_batches_tracked", "face_encoder_blocks.4.2.conv_block.0.weight", "face_encoder_blocks.4.2.conv_block.0.bias", "face_encoder_blocks.4.2.conv_block.1.weight", "face_encoder_blocks.4.2.conv_block.1.bias", "face_encoder_blocks.4.2.conv_block.1.running_mean", "face_encoder_blocks.4.2.conv_block.1.running_var", "face_encoder_blocks.4.2.conv_block.1.num_batches_tracked", "face_encoder_blocks.5.0.conv_block.0.weight", "face_encoder_blocks.5.0.conv_block.0.bias", "face_encoder_blocks.5.0.conv_block.1.weight", "face_encoder_blocks.5.0.conv_block.1.bias", "face_encoder_blocks.5.0.conv_block.1.running_mean", "face_encoder_blocks.5.0.conv_block.1.running_var", "face_encoder_blocks.5.0.conv_block.1.num_batches_tracked", "face_encoder_blocks.5.1.conv_block.0.weight", "face_encoder_blocks.5.1.conv_block.0.bias", "face_encoder_blocks.5.1.conv_block.1.weight", "face_encoder_blocks.5.1.conv_block.1.bias", "face_encoder_blocks.5.1.conv_block.1.running_mean", "face_encoder_blocks.5.1.conv_block.1.running_var", "face_encoder_blocks.5.1.conv_block.1.num_batches_tracked", "face_encoder_blocks.5.2.conv_block.0.weight", "face_encoder_blocks.5.2.conv_block.0.bias", "face_encoder_blocks.5.2.conv_block.1.weight", "face_encoder_blocks.5.2.conv_block.1.bias", "face_encoder_blocks.5.2.conv_block.1.running_mean", "face_encoder_blocks.5.2.conv_block.1.running_var", "face_encoder_blocks.5.2.conv_block.1.num_batches_tracked", "face_encoder_blocks.6.0.conv_block.0.weight", "face_encoder_blocks.6.0.conv_block.0.bias", "face_encoder_blocks.6.0.conv_block.1.weight", "face_encoder_blocks.6.0.conv_block.1.bias", "face_encoder_blocks.6.0.conv_block.1.running_mean", "face_encoder_blocks.6.0.conv_block.1.running_var", "face_encoder_blocks.6.0.conv_block.1.num_batches_tracked", "face_encoder_blocks.6.1.conv_block.0.weight", "face_encoder_blocks.6.1.conv_block.0.bias", "face_encoder_blocks.6.1.conv_block.1.weight", "face_encoder_blocks.6.1.conv_block.1.bias", "face_encoder_blocks.6.1.conv_block.1.running_mean", "face_encoder_blocks.6.1.conv_block.1.running_var", "face_encoder_blocks.6.1.conv_block.1.num_batches_tracked", "face_encoder_blocks.7.0.conv_block.0.weight", "face_encoder_blocks.7.0.conv_block.0.bias", "face_encoder_blocks.7.0.conv_block.1.weight", "face_encoder_blocks.7.0.conv_block.1.bias", "face_encoder_blocks.7.0.conv_block.1.running_mean", "face_encoder_blocks.7.0.conv_block.1.running_var", "face_encoder_blocks.7.0.conv_block.1.num_batches_tracked", "face_encoder_blocks.7.1.conv_block.0.weight", "face_encoder_blocks.7.1.conv_block.0.bias", "face_encoder_blocks.7.1.conv_block.1.weight", "face_encoder_blocks.7.1.conv_block.1.bias", "face_encoder_blocks.7.1.conv_block.1.running_mean", "face_encoder_blocks.7.1.conv_block.1.running_var", "face_encoder_blocks.7.1.conv_block.1.num_batches_tracked", "face_decoder_blocks.0.0.conv_block.0.weight", "face_decoder_blocks.0.0.conv_block.0.bias", "face_decoder_blocks.0.0.conv_block.1.weight", "face_decoder_blocks.0.0.conv_block.1.bias", "face_decoder_blocks.0.0.conv_block.1.running_mean", "face_decoder_blocks.0.0.conv_block.1.running_var", "face_decoder_blocks.0.0.conv_block.1.num_batches_tracked", "face_decoder_blocks.1.0.conv_block.0.weight", "face_decoder_blocks.1.0.conv_block.0.bias", "face_decoder_blocks.1.0.conv_block.1.weight", "face_decoder_blocks.1.0.conv_block.1.bias", "face_decoder_blocks.1.0.conv_block.1.running_mean", "face_decoder_blocks.1.0.conv_block.1.running_var", "face_decoder_blocks.1.0.conv_block.1.num_batches_tracked", "face_decoder_blocks.1.1.conv_block.0.weight", "face_decoder_blocks.1.1.conv_block.0.bias", "face_decoder_blocks.1.1.conv_block.1.weight", "face_decoder_blocks.1.1.conv_block.1.bias", "face_decoder_blocks.1.1.conv_block.1.running_mean", "face_decoder_blocks.1.1.conv_block.1.running_var", "face_decoder_blocks.1.1.conv_block.1.num_batches_tracked", "face_decoder_blocks.2.0.conv_block.0.weight", "face_decoder_blocks.2.0.conv_block.0.bias", "face_decoder_blocks.2.0.conv_block.1.weight", "face_decoder_blocks.2.0.conv_block.1.bias", "face_decoder_blocks.2.0.conv_block.1.running_mean", "face_decoder_blocks.2.0.conv_block.1.running_var", "face_decoder_blocks.2.0.conv_block.1.num_batches_tracked", "face_decoder_blocks.2.1.conv_block.0.weight", "face_decoder_blocks.2.1.conv_block.0.bias", "face_decoder_blocks.2.1.conv_block.1.weight", "face_decoder_blocks.2.1.conv_block.1.bias", "face_decoder_blocks.2.1.conv_block.1.running_mean", "face_decoder_blocks.2.1.conv_block.1.running_var", "face_decoder_blocks.2.1.conv_block.1.num_batches_tracked", "face_decoder_blocks.2.2.conv_block.0.weight", "face_decoder_blocks.2.2.conv_block.0.bias", "face_decoder_blocks.2.2.conv_block.1.weight", "face_decoder_blocks.2.2.conv_block.1.bias", "face_decoder_blocks.2.2.conv_block.1.running_mean", "face_decoder_blocks.2.2.conv_block.1.running_var", "face_decoder_blocks.2.2.conv_block.1.num_batches_tracked", "face_decoder_blocks.3.0.conv_block.0.weight", "face_decoder_blocks.3.0.conv_block.0.bias", "face_decoder_blocks.3.0.conv_block.1.weight", "face_decoder_blocks.3.0.conv_block.1.bias", "face_decoder_blocks.3.0.conv_block.1.running_mean", "face_decoder_blocks.3.0.conv_block.1.running_var", "face_decoder_blocks.3.0.conv_block.1.num_batches_tracked", "face_decoder_blocks.3.1.conv_block.0.weight", "face_decoder_blocks.3.1.conv_block.0.bias", "face_decoder_blocks.3.1.conv_block.1.weight", "face_decoder_blocks.3.1.conv_block.1.bias", "face_decoder_blocks.3.1.conv_block.1.running_mean", "face_decoder_blocks.3.1.conv_block.1.running_var", "face_decoder_blocks.3.1.conv_block.1.num_batches_tracked", "face_decoder_blocks.3.2.conv_block.0.weight", "face_decoder_blocks.3.2.conv_block.0.bias", "face_decoder_blocks.3.2.conv_block.1.weight", "face_decoder_blocks.3.2.conv_block.1.bias", "face_decoder_blocks.3.2.conv_block.1.running_mean", "face_decoder_blocks.3.2.conv_block.1.running_var", "face_decoder_blocks.3.2.conv_block.1.num_batches_tracked", "face_decoder_blocks.4.0.conv_block.0.weight", "face_decoder_blocks.4.0.conv_block.0.bias", "face_decoder_blocks.4.0.conv_block.1.weight", "face_decoder_blocks.4.0.conv_block.1.bias", "face_decoder_blocks.4.0.conv_block.1.running_mean", "face_decoder_blocks.4.0.conv_block.1.running_var", "face_decoder_blocks.4.0.conv_block.1.num_batches_tracked", "face_decoder_blocks.4.1.conv_block.0.weight", "face_decoder_blocks.4.1.conv_block.0.bias", "face_decoder_blocks.4.1.conv_block.1.weight", "face_decoder_blocks.4.1.conv_block.1.bias", "face_decoder_blocks.4.1.conv_block.1.running_mean", "face_decoder_blocks.4.1.conv_block.1.running_var", "face_decoder_blocks.4.1.conv_block.1.num_batches_tracked", "face_decoder_blocks.4.2.conv_block.0.weight", "face_decoder_blocks.4.2.conv_block.0.bias", "face_decoder_blocks.4.2.conv_block.1.weight", "face_decoder_blocks.4.2.conv_block.1.bias", "face_decoder_blocks.4.2.conv_block.1.running_mean", "face_decoder_blocks.4.2.conv_block.1.running_var", "face_decoder_blocks.4.2.conv_block.1.num_batches_tracked", "face_decoder_blocks.5.0.conv_block.0.weight", "face_decoder_blocks.5.0.conv_block.0.bias", "face_decoder_blocks.5.0.conv_block.1.weight", "face_decoder_blocks.5.0.conv_block.1.bias", "face_decoder_blocks.5.0.conv_block.1.running_mean", "face_decoder_blocks.5.0.conv_block.1.running_var", "face_decoder_blocks.5.0.conv_block.1.num_batches_tracked", "face_decoder_blocks.5.1.conv_block.0.weight", "face_decoder_blocks.5.1.conv_block.0.bias", "face_decoder_blocks.5.1.conv_block.1.weight", "face_decoder_blocks.5.1.conv_block.1.bias", "face_decoder_blocks.5.1.conv_block.1.running_mean", "face_decoder_blocks.5.1.conv_block.1.running_var", "face_decoder_blocks.5.1.conv_block.1.num_batches_tracked", "face_decoder_blocks.5.2.conv_block.0.weight", "face_decoder_blocks.5.2.conv_block.0.bias", "face_decoder_blocks.5.2.conv_block.1.weight", "face_decoder_blocks.5.2.conv_block.1.bias", "face_decoder_blocks.5.2.conv_block.1.running_mean", "face_decoder_blocks.5.2.conv_block.1.running_var", "face_decoder_blocks.5.2.conv_block.1.num_batches_tracked", "face_decoder_blocks.6.0.conv_block.0.weight", "face_decoder_blocks.6.0.conv_block.0.bias", "face_decoder_blocks.6.0.conv_block.1.weight", "face_decoder_blocks.6.0.conv_block.1.bias", "face_decoder_blocks.6.0.conv_block.1.running_mean", "face_decoder_blocks.6.0.conv_block.1.running_var", "face_decoder_blocks.6.0.conv_block.1.num_batches_tracked", "face_decoder_blocks.6.1.conv_block.0.weight", "face_decoder_blocks.6.1.conv_block.0.bias", "face_decoder_blocks.6.1.conv_block.1.weight", "face_decoder_blocks.6.1.conv_block.1.bias", "face_decoder_blocks.6.1.conv_block.1.running_mean", "face_decoder_blocks.6.1.conv_block.1.running_var", "face_decoder_blocks.6.1.conv_block.1.num_batches_tracked", "face_decoder_blocks.6.2.conv_block.0.weight", "face_decoder_blocks.6.2.conv_block.0.bias", "face_decoder_blocks.6.2.conv_block.1.weight", "face_decoder_blocks.6.2.conv_block.1.bias", "face_decoder_blocks.6.2.conv_block.1.running_mean", "face_decoder_blocks.6.2.conv_block.1.running_var", "face_decoder_blocks.6.2.conv_block.1.num_batches_tracked", "face_decoder_blocks.7.0.conv_block.0.weight", "face_decoder_blocks.7.0.conv_block.0.bias", "face_decoder_blocks.7.0.conv_block.1.weight", "face_decoder_blocks.7.0.conv_block.1.bias", "face_decoder_blocks.7.0.conv_block.1.running_mean", "face_decoder_blocks.7.0.conv_block.1.running_var", "face_decoder_blocks.7.0.conv_block.1.num_batches_tracked", "face_decoder_blocks.7.1.conv_block.0.weight", "face_decoder_blocks.7.1.conv_block.0.bias", "face_decoder_blocks.7.1.conv_block.1.weight", "face_decoder_blocks.7.1.conv_block.1.bias", "face_decoder_blocks.7.1.conv_block.1.running_mean", "face_decoder_blocks.7.1.conv_block.1.running_var", "face_decoder_blocks.7.1.conv_block.1.num_batches_tracked", "face_decoder_blocks.7.2.conv_block.0.weight", "face_decoder_blocks.7.2.conv_block.0.bias", "face_decoder_blocks.7.2.conv_block.1.weight", "face_decoder_blocks.7.2.conv_block.1.bias", "face_decoder_blocks.7.2.conv_block.1.running_mean", "face_decoder_blocks.7.2.conv_block.1.running_var", "face_decoder_blocks.7.2.conv_block.1.num_batches_tracked", "output_block.0.conv_block.0.weight", "output_block.0.conv_block.0.bias", "output_block.0.conv_block.1.weight", "output_block.0.conv_block.1.bias", "output_block.0.conv_block.1.running_mean", "output_block.0.conv_block.1.running_var", "output_block.0.conv_block.1.num_batches_tracked", "output_block.1.weight", "output_block.1.bias". 
        size mismatch for audio_encoder.11.conv_block.0.weight: copying a param with shape torch.Size([512, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3]).
        size mismatch for audio_encoder.11.conv_block.0.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
        size mismatch for audio_encoder.11.conv_block.1.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
        size mismatch for audio_encoder.11.conv_block.1.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
        size mismatch for audio_encoder.11.conv_block.1.running_mean: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
        size mismatch for audio_encoder.11.conv_block.1.running_var: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
        size mismatch for audio_encoder.12.conv_block.0.weight: copying a param with shape torch.Size([512, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([512, 256, 3, 3]).

**Comment by wowopc** [comment]
How can I use HQ to correct neural network 96 * 2?

**Comment by wowopc** [comment]
How can I use HQ to correct neural network 96 * 2?

**Comment by Rudrabha** [comment]
You have tried to load the pretrained model in a different architecture?
