### ISSUE TITLE
Finetuning on personal dataset

### ISSUE THREAD

**Issue by Some-random** [Rudrabha/Wav2Lip#248]
The instruction says "You might not get good results by training/fine-tuning on a few minutes of a single speaker". I'm wondering why is that? Say I train a model using lrw/ lrs2 then fine-tune it on my personal dataset with the same resolution and fps, why wouldn't it work?

**Comment by Rudrabha** [comment]
If everything matches the datasets we have trained on, it may get expected results. We had a lot of issues created on people unable to train on their curated datasets. Thus we put that warning on the README.
