### ISSUE TITLE
Needs to generate higher resolution video on personal dataset

### ISSUE THREAD

**Issue by Some-random** [Rudrabha/Wav2Lip#250]
But I've found the resolution of LRW/ LRS2 dataset is too low compared to my own dataset...

Does anyone happen to know any work that can transform lower resolution video to higher resolution video (so I can using LRW for pretraining, generate lower resolution video on my own dataset, then transform it to higher resolution) or any dataset that contains higher resolution video that can be used for pretraining?

**Comment by ambitionforcomputervision** [comment]
If you are looking for a method to increase video resolution you could search for so called [video super resolution algorithms](https://paperswithcode.com/task/video-super-resolution) (there are some open source implementations available behind the link). As for a higher resolution dataset, you could have a look at [AVSpeech](https://looking-to-listen.github.io/avspeech/download.html). There are some tips available for this dataset in other issues ([1](https://github.com/Rudrabha/Wav2Lip/issues/249#issuecomment-820199187) [2](https://github.com/Rudrabha/Wav2Lip/issues/159#issuecomment-752065325) [3](https://github.com/Rudrabha/Wav2Lip/issues/167#issuecomment-750868922) [4](https://github.com/Rudrabha/Wav2Lip/issues/211#issuecomment-773268257)).
