### ISSUE TITLE
How large GPU memory does it need to preprocess the data

### ISSUE THREAD

**Issue by sniperwrb** [Rudrabha/Wav2Lip#254]
10G seems to be far too small.
How large could it be sufficient?

**Comment by ambitionforcomputervision** [comment]
I am not sure what the default memory requirements are but if `preprocess.py` gives you a CUDA out of memory error you can lower the `--batch_size` argument to something lower than the default `32` (e.g. `16` or `8`) until it works for your GPU.

**Comment by Rudrabha** [comment]
Please vary the batch size and try to find what fits in the memory.
