### ISSUE TITLE
Massive Ram Usage, Crashes Out

### ISSUE THREAD

**Issue by Excuze** [Rudrabha/Wav2Lip#255]
Hello! I'm trying to run this program on Kali Linux within a VM (VMWare Workstation 16 Player). It has around 5.4gb of free RAM when I try to run the script, but is killed at reading video frames by the OS. Apparently it's trying to use 8gb, my video and audio are both under a few hundred mb so I don't think it's them.

When trying to run this earlier with around 3gb free on the VM it also failed but it was trying to use 5bg back then.

Not sure what's causing this or how to fix it.

In dmesg it says
`[  617.472575] Out of memory: Killed process 1393 (python3) total-vm:8282104kB, anon-rss:5578288kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:13372kB oom_score_adj:0                                                             
[  617.607546] oom_reaper: reaped process 1393 (python3), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB`

**Comment by Rudrabha** [comment]
We extract and store all frames of the video in the RAM. A few hundred MB video will actually contain a lot of frames which can lead to this issue. You can modify the code inside this [else](https://github.com/Rudrabha/Wav2Lip/blob/403bc711dfb70171c09233ba9cf765b290f76e32/inference.py#L190) statement to avoid the issue. Please re-open if the error persists.
