### ISSUE TITLE
Alternative model structure

### ISSUE THREAD

**Issue by Some-random** [Rudrabha/Wav2Lip#257]
The GAN implementation in this work is very easy to follow, but it seems to be lacking some important tricks that have been used in other work (like WGAN, instance normalization, etc). Has anyone tried these tricks?

**Comment by Rudrabha** [comment]
We did try WGAN on Wav2Lip after the initial code was released. The amount of improvement was negligible to us so we did not release the model. You can give it a try. It may improve the quality of the generated output.

**Comment by Some-random** [comment]
Thanks for the reply! I've tried replacing the original GAN to WGAN-GP but the generated image seems to be copying the identity image (wrong_img in the code) and results in weird results when the pose of identity image and target image (the image to be generated) is different. Does anyone have insight on how this happened?

Some examples of the generated image are attached below: 
![7_0](https://user-images.githubusercontent.com/10830859/117595962-bff8ac00-b174-11eb-968c-0b4c9e65b9d5.jpg)
![8_0](https://user-images.githubusercontent.com/10830859/117595979-c9821400-b174-11eb-9f38-3b7f15d51582.jpg)

**Comment by Rudrabha** [comment]
We started with only reconstruction loss. We then introduced the sync loss and trained the network to a point where the lip-sync quality is very good (given in the Wav2Lip ckpt). Lastly, we introduced the vanilla GAN on top of this model and trained it for a few more epochs (Wav2Lip + GAN ckpt). We stopped when we found that the network is losing lip-sync while generating clearer visual quality. If you are training the GAN then please use the Wav2lip ckpt as the initialization. Also, you may have to adjust the lambdas for each loss which is very important as that ensures you continue to balance between sync and visual quality. I am reopening this issue.

**Comment by 15458wew** [comment]
@Rudrabha Hello, I am trying to train a higher resolution video. I use LSGAN to effectively promote the convergence of perception loss. But in the video I'm generating, the mouth always trembles. I trained syncnet in your way, and the loss converged to 0.22. During Gan's training process, l1 loss converged to 0.016, and sync loss converged to 0.17. However, in the generated video, the mouth will tremble in some frames.

**Comment by hnsywangxin** [comment]
@Some-random 你好，我碰到了同样的问题，请问有什么好的解决办法吗，谢谢
