### ISSUE TITLE
Video looping for videos smaller than audios

### ISSUE THREAD

**Issue by dipam7** [Rudrabha/Wav2Lip#26]
Hello,
I noticed that if the audio is longer than the video, the video loops from the start point. This seems to have an effect of a break in between and does not look natural. Do you have any tips on how to over come this?

**Comment by prajwalkr** [comment]
You can duplicate frames of the video evenly to match the audio length.

**Comment by dipam7** [comment]
Okay, I am thinking of using ffmpeg for this. Any tool that you would recommend?

**Comment by prajwalkr** [comment]
You can write a heuristic in Python probably. But if you can use FFMPEG, that would be simple, I guess. Please do let us know how you do it! We will try to add it to the repo :+1:

**Comment by dipam7** [comment]
Will do :)

**Comment by Adorablepet** [comment]
@prajwalkr @dipam7 how to solve this problem?Could you tell me?Thanks.
