### ISSUE TITLE
inference error No module named face_detection.core

### ISSUE THREAD

**Issue by pablobitcode** [Rudrabha/Wav2Lip#261]
I've been trying to run the inference.py to use the pre-trained model but i got this error:
  File "inference.py", line 7, in <module>
    import torch, face_detection
  File "C:\wav2lip\face_detection\__init__.py", line 1, in <module>
    from .core import FaceDetector
ModuleNotFoundError: No module named 'face_detection.core'

Tried to install face_detection using "pip install face_detection" but it upgrades torch and still doesn't work.
Requirements are all fine, so i don't know what else to do.

**Comment by pablobitcode** [comment]
If anyone else have the same problem, fixed it by changing "face_detection/__init__.py" file
```
ERROR - from .core import FaceDetector
FIXED - from .detection.core import FaceDetector
```

**Comment by prajwalkr** [comment]
I see, we  did not encounter this problem in Linux, thanks for pointing it out.
