### ISSUE TITLE
Links Of Weights Are Down

### ISSUE THREAD

**Issue by Sba-Stuff** [Rudrabha/Wav2Lip#262]
Your Links of Weights are down. please update.

**Comment by Rudrabha** [comment]
I have just cross-checked. Links are working fine at my end. 
Can you check this link: https://iiitaphyd-my.sharepoint.com/:f:/g/personal/radrabha_m_research_iiit_ac_in/El--_jWXJctHsvlBxb7BUusBqlZMxA8AOv98Y4yGdyP6CQ?e=BMYt32

**Comment by Sba-Stuff** [comment]
Thank You. I thought my Ip was banned. I used proxy. It is fixed. 👍
