### ISSUE TITLE
Way to speed up your training by at least 10x

### ISSUE THREAD

**Issue by OliverDayunLiu** [Rudrabha/Wav2Lip#263]
Hi,

I've found ways to speed up the training by at least 10x.
Below are my recommended adjustments for speeding up the training and evaluation:

1) The bottleneck in the dataloader happens at https://github.com/Rudrabha/Wav2Lip/blob/master/wav2lip_train.py#L138-L141 . As this step takes so much time, you should save the result to a dictionary. Subsequent loads can use lookup to see if it exists in prior, saving a lot of time.

2) As a continuation of 1), when using multiprocess, at each iteration, the dataloader's worker processes will be reset, thus losing the saved dictionary. To solve this problem, use Manager from multiprocessing as in the following post: https://discuss.pytorch.org/t/dataloader-re-initialize-dataset-after-each-iteration/32658/4

It will only take ~7 lines of code change in total. 

3) Remember to do the above for both train_dataset and test_dataset. Remember to do them for both color_syncnet_train.py and wav2lip_train.py.

**Comment by Rudrabha** [comment]
Hello,

Thanks a lot for these suggestions. Can you create a pull request with these changes? We will happily add it to our main branch :)

**Comment by Lex-voda** [comment]
In order to solve the overflow problem without abandoning memory acceleration, perhaps consider adding some substitution strategies to the dictionary such as the LRU or FIFO algorithm, which is worth trying anyway
