### ISSUE TITLE
Discriminator of wav2lip_hq

### ISSUE THREAD

**Issue by lzzyzlbb** [Rudrabha/Wav2Lip#266]
Hi, could you provide the discriminator of wav2lip_hq?

**Comment by PrashanthaTP** [comment]
Hey, are you asking the quality discriminator ?
https://github.com/Rudrabha/Wav2Lip/blob/80c01f9fe1aaa07e19c1e3088744bb8500cb45fa/models/wav2lip.py#L127-L184
