### ISSUE TITLE
Reading video frames... ^C error

### ISSUE THREAD

**Issue by bmox** [Rudrabha/Wav2Lip#267]
Using cuda for inference.
Reading video frames...
^C
`
!cd Wav2Lip && python inference.py --checkpoint_path checkpoints/wav2lip_gan.pth --face "../sample_data/input_vid.mp4" --audio "../sample_data/input_audio.wav"
`
I follow every step and also install requirements.txt.  input video.mp4 and input audio.wav duration is 7 minutes.

What is the problem ?

**Comment by Rudrabha** [comment]
^C is a key-board interrupt in general that the user provides to stop the execution of a program. Can you elaborate on this issue further?

**Comment by bmox** [comment]
I'm running the code on google colab. The video and audio is 10 minutes long and the video size is 25mb. Face is available in every frame. FPS is 24. file type .mp4 resolution 1920*1080 , audio type is .mp3.  But when I use a small video and audio  it work.

**Comment by Rudrabha** [comment]
I am not sure why this issue is coming. Please try it on a local machine, maybe. The other workaround is to chunk the audio and video into short segments and then sync them. You can rejoin them again later. I believe this issue is specific to collab since we have exported videos for up to 15 minutes without facing any issue.

**Comment by bmox** [comment]
Currently I am facing the same issue but I have found the solution to this problem. Previously I export the video from premiere pro. When I use that video for Wav2Lip , it giving me the error (^c). But after I edit this video in my phone app and export the video. Then giving the video to Wav2Lip it's work fine.  I think the problem was occuring because of premiere pro's video encoding format.
