### ISSUE TITLE
Colab notebook

### ISSUE THREAD

**Issue by zabique** [Rudrabha/Wav2Lip#270]
Hi!

I have created slightly more user friendly notebook. Feel free to use the code I already borrowed from you.
https://colab.research.google.com/drive/1IjFW1cLevs6Ouyu4Yht4mnR4yeuMqO7Y#scrollTo=MH1m608OymLH

**Comment by Rudrabha** [comment]
Thanks a lot :)

**Comment by justinjohn0306** [comment]
Noice!
