### ISSUE TITLE
Prominent Box occuring around lower half of the face

### ISSUE THREAD

**Issue by prajwaljpj** [Rudrabha/Wav2Lip#271]
While inferencing, There is a prominent box occurring around the lower half of the face. Is there any way to make this look better? Is it because the background clarity is better than generated image clarity. Any suggestions?

**Comment by krrishdholakia** [comment]
+1

**Comment by Rudrabha** [comment]
You can extract the exact face boundaries using some face segmentation techniques. Face landmarks can provide fine boundaries but are often deemed to be noisy. Some other face segmentation techniques can be used too.

**Comment by prajwaljpj** [comment]
@Rudrabha, Thank you for your suggestion. Restiching low-res segmented face over high resolution image will make it unnatural. Is there a way the quality of lip could be improved?

**Comment by RAJA-PARIKSHAT** [comment]
@prajwaljpj  I am getting the same issue a prominent box is occurring around the lip region, how to improve it? Did you manage to improve it?
