### ISSUE TITLE
Length(number of frames) of input and output video are not same

### ISSUE THREAD

**Issue by subhasis1990** [Rudrabha/Wav2Lip#274]
I found that the length(number of frames) of input and output video are not same. Due to these line of codes, we are taking a window of mel_step_size from the mel_spectogram and depending upon the fps of the video we are losing some frames. Is there any workareound anyone found?
mel_chunks = []
mel_idx_multiplier = 80./fps 
i = 0
while 1:
    start_idx = int(i * mel_idx_multiplier)
    if start_idx + mel_step_size > len(mel[0]):
        break
    mel_chunks.append(mel[:, start_idx : start_idx + mel_step_size])
    i += 1
full_frames = video_frames[:len(mel_chunks)]

**Comment by Rudrabha** [comment]
The easiest workaround will be to add blank audio at the end of the original audio. This will ensure that even the last few frames are considered.

**Comment by iamkhalidbashir** [comment]
What would be permanant solution to this?
