### ISSUE TITLE
Colab seems not working anymore

### ISSUE THREAD

**Issue by HelixNGC7293** [Rudrabha/Wav2Lip#28]
Hello! Got version conflict errors like this...
Is there any way to work around this?
Thank you!

Building wheels for collected packages: librosa
  Building wheel for librosa (setup.py) ... done
  Created wheel for librosa: filename=librosa-0.7.0-cp36-none-any.whl size=1598345 sha256=0ae5d8d2902c4310f2c50dd05a2eaec382bf31e30461ae2ce3cc203f286d16b1
  Stored in directory: /root/.cache/pip/wheels/49/1d/38/c8ad12fcad67569d8e730c3275be5e581bd589558484a0f881
Successfully built librosa
ERROR: xarray 0.15.1 has requirement setuptools>=41.2, but you'll have setuptools 39.1.0 which is incompatible.
ERROR: google-auth 1.17.2 has requirement setuptools>=40.3.0, but you'll have setuptools 39.1.0 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.
ERROR: tensorflow 1.10.0 has requirement numpy<=1.14.5,>=1.13.3, but you'll have numpy 1.17.1 which is incompatible.
Installing collected packages: numpy, soundfile, librosa, opencv-contrib-python, opencv-python, setuptools, tensorboard, tensorflow, torch, torchvision, tqdm
  Found existing installation: numpy 1.18.5
    Uninstalling numpy-1.18.5:
      Successfully uninstalled numpy-1.18.5
  Found existing installation: librosa 0.6.3
    Uninstalling librosa-0.6.3:
      Successfully uninstalled librosa-0.6.3
  Found existing installation: opencv-contrib-python 4.1.2.30

**Comment by prajwalkr** [comment]
Check if you get any future errors while running the actual code. In our experience, you should not get errors.

**Comment by prajwalkr** [comment]
The updated `requirements.txt` should not give you the TensorFlow error at least.
