### ISSUE TITLE
How to increase video resolution and audio length inside Colab?

### ISSUE THREAD

**Issue by inglesuniversal** [Rudrabha/Wav2Lip#281]
I got this error...

Using cuda for inference.
Reading video frames...
Number of frames available for inference: 1500
(80, 3630)
Length of mel chunks: 1357
  0% 0/11 [00:00<?, ?it/s]
  0% 0/85 [00:03<?, ?it/s]
Recovering from OOM error; New batch size: 8

  0% 0/170 [00:00<?, ?it/s]
Recovering from OOM error; New batch size: 4

  0% 0/340 [00:00<?, ?it/s]
Recovering from OOM error; New batch size: 2

  0% 0/679 [00:00<?, ?it/s]
Recovering from OOM error; New batch size: 1

  0% 0/1357 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "inference.py", line 78, in face_detect
    predictions.extend(detector.get_detections_for_batch(np.array(images[i:i + batch_size])))
  File "/content/Wav2Lip/face_detection/api.py", line 66, in get_detections_for_batch
    detected_faces = self.face_detector.detect_from_batch(images.copy())
  File "/content/Wav2Lip/face_detection/detection/sfd/sfd_detector.py", line 42, in detect_from_batch
    bboxlists = batch_detect(self.face_detector, images, device=self.device)
  File "/content/Wav2Lip/face_detection/detection/sfd/detect.py", line 65, in batch_detect
    imgs = torch.from_numpy(imgs).float().to(device)
RuntimeError: CUDA error: an illegal memory access was encountered

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inference.py", line 280, in <module>
    main()
  File "inference.py", line 250, in main
    total=int(np.ceil(float(len(mel_chunks))/batch_size)))):
  File "/usr/local/lib/python3.7/dist-packages/tqdm/std.py", line 1104, in __iter__
    for obj in iterable:
  File "inference.py", line 113, in datagen
    face_det_results = face_detect(frames) # BGR2RGB for CNN face detection
  File "inference.py", line 81, in face_detect
    raise RuntimeError('Image too big to run face detection on GPU. Please use the --resize_factor argument')
RuntimeError: Image too big to run face detection on GPU. Please use the --resize_factor argument
  0% 0/11 [00:07<?, ?it/s]

Is there a way to record longer videos and audios, instead of little chunks?

**Comment by Rudrabha** [comment]
It will be better if you use the resize factor argument to reduce the resolution of your video. Alternatively, you may reduce the batch size for face detection in this [line](https://github.com/Rudrabha/Wav2Lip/blob/80c01f9fe1aaa07e19c1e3088744bb8500cb45fa/inference.py#L31).

**Comment by inglesuniversal** [comment]
ok I will give it a try... but just to be on the safe side, size I can pre-render the videos and audio files to be mixed into the output. What is the maximum time allowed under the current configuration? That way I can also have chunks of videos and audios ready for testing without compromising the process with unexpected runtime errors. 

Best regards

**Comment by Rudrabha** [comment]
There is no max time defined as such in our inference code or model. It can potentially handle any amount of data. The hardware used to take the inference actually constrains this. I am not sure about the configuration you are using, but in my configuration, I have not faced issues up to 2-3 minutes of videos.
