### ISSUE TITLE
 interactive demo  

### ISSUE THREAD

**Issue by hafsamat** [Rudrabha/Wav2Lip#283]
how can I make an interactive demo as you're http://bhaasha.iiit.ac.in/lipsync/upload/, I managed to display the video and audio but the final result is not displayed, heeelp please

**Comment by Rudrabha** [comment]
The demo initially ran on a flask server but now uses Django. I had initially created the flask version. Please check tutorials on how to use run a python script in the backend using flask. One such tutorial is in this link: https://blog.pythonanywhere.com/169/
