### ISSUE TITLE
How to compute the metric to measure the Lip-Sync Error( LSE-D and LSE-C)? 

### ISSUE THREAD

**Issue by hanbaobao950123** [Rudrabha/Wav2Lip#284]
I have run the script on https://github.com/joonson/syncnet_python/issues. And I got a result for my synced video as follows. 
AV offset:      0
Min dist:       8.860
Confidence:     5.738
Should Min dist be LSE-D? 
Should Confidence be LSE-C?

**Comment by prajwalkr** [comment]
Yes, you are right.
