### ISSUE TITLE
How to verify that the extract audio window (spectrogram) corresponds to the extracted video window/ frames?

### ISSUE THREAD

**Issue by Mayur28** [Rudrabha/Wav2Lip#287]
Hi,

I just wanted to find out if anyone is able to provide any intuition on how can I verify that the portion of the audio mel spectrogram extracted is in fact synchronous with the video window extracted when training the lip-sync discriminator? I see that [this line](https://github.com/Rudrabha/Wav2Lip/blob/80c01f9fe1aaa07e19c1e3088744bb8500cb45fa/color_syncnet_train.py#L59) is used for this, but can anyone please elaborate on why this works please.

Thanks.

**Comment by prajwalkr** [comment]
1 second of video corresponds to 25 frames (FPS). And 1 second of audio corresponds to 80 mel frames. So, a video time-step x will correspond to (x / fps) * 80.
