### ISSUE TITLE
high memory usage but low volatile gpu-util

### ISSUE THREAD

**Issue by wuxiaolianggit** [Rudrabha/Wav2Lip#29]
Have you ever encountered this kind of situation when you train models？
![image](https://user-images.githubusercontent.com/34123600/92574600-e13d8b80-f2b9-11ea-8760-f9e819a239ec.png)
@ @ @prajwalkr

**Comment by prajwalkr** [comment]
The gpu-util will keep changing rapidly. don't worry about it as long as you are able to train on a GPU without errors.

**Comment by wuxiaolianggit** [comment]
Thank you very much for your reply
