### ISSUE TITLE
Results are different from the model when compared to generated from interactive demo

### ISSUE THREAD

**Issue by devvikas** [Rudrabha/Wav2Lip#291]
Great work and thanks for publishing the code & models.

For a video & audio, I generated a output using the models provided in this repo. Then for the same pair, I generated from your interactive website. Results are different. Are you using a more trained model on your website. It will be great if you can share that if its different.
Thanks

**Comment by prajwalkr** [comment]
The website code is optimized a bit for speed, so you might see inferior results sometimes there. The models are exactly the same though.
