### ISSUE TITLE
SyncNet converging too quickly for LRS2

### ISSUE THREAD

**Issue by Mayur28** [Rudrabha/Wav2Lip#293]
Hi,

I am trying to train the expert lip sync discriminator using LRS2 and using the code from the repo as is (without any changes), but I am unsure why is the model converging much quicker than it should be. Default parameters are used. As mentioned in one of the previous issues, I was expecting the loss to be around 0.69 for quite some time, and to only start to decrease after 150K steps. I have a loss curve that I am getting.
![image](https://user-images.githubusercontent.com/26574827/124249024-bf044b00-db23-11eb-961e-e564517a441b.png)

Any assistance would be highly appreciated.
Thanks

**Comment by zhanghming** [comment]
@Mayur28 , Hi, did you  use the LRS2 dataset or other dataset? The loss plot was drawed by tensorboard?

**Comment by Mayur28** [comment]
Hi @zhanghming,

I was using LRS2 and I was using weights and biases to plot the loss function. I realized my mistake when I posted my previous mistake - I erroneously ran my code on my small subset of the dataset instead of the full dataset, therefore the model converged quickly. Apologies for that.

**Comment by xopclabs** [comment]
Hi @Mayur28! How is your research work going? I'm quite interested in yours implementation of wav2lip. Do you plan on open-sourcing it any time soon? Thanks anyway!

**Comment by Mayur28** [comment]
Hi @xopclabs ,

My research has been delayed by a few months unfortunately, I am expecting to complete my research by the end of the year and at that point I will decide whether I will open-source the implementation or not. I will keep you posted.
