### ISSUE TITLE
High Quality Implementation?

### ISSUE THREAD

**Issue by TaoTeCha** [Rudrabha/Wav2Lip#295]
Anybody know of a repo with higher quality output? I've looked around and I see the Hq_train.py file but I don't see any results from it.
If there is a high quality model out there, do we need to revise inference.py and any other files?

Thank you.

**Comment by GzuPark** [comment]
@TaoTeCha the hq train file in this repo means use both lipsync discriminator and visual quality discriminator. I think you want to get high resolution results, but you cannot get them.

**Comment by TaoTeCha** [comment]
Not sure why this was closed, my question wasn't answered.
I saw the creators say somewhere they were working on a high quality model. And I would assume someone would have opened sourced a project with higher quality data.
Anybody know of a high quality model out there?

**Comment by MAYBreath** [comment]
> Not sure why this was closed, my question wasn't answered.
> I saw the creators say somewhere they were working on a high quality model. And I would assume someone would have opened sourced a project with higher quality data.
> Anybody know of a high quality model out there?

try this one
https://github.com/Markfryazino/wav2lip-hq

**Comment by GzuPark** [comment]
> > Not sure why this was closed, my question wasn't answered.
> > I saw the creators say somewhere they were working on a high quality model. And I would assume someone would have opened sourced a project with higher quality data.
> > Anybody know of a high quality model out there?
> 
> try this one
> https://github.com/Markfryazino/wav2lip-hq

Thank you for sharing it.

1. Super resolution is the simplest approach. It's good, but sometimes cv2 interpolation is enough.
2. Face parsing is a great idea.
3. I don't know how good it is. In my case, the tooth is emphasis.

**Comment by TaoTeCha** [comment]
> > Not sure why this was closed, my question wasn't answered.
> > I saw the creators say somewhere they were working on a high quality model. And I would assume someone would have opened sourced a project with higher quality data.
> > Anybody know of a high quality model out there?
> 
> try this one
> https://github.com/Markfryazino/wav2lip-hq

Thank you for looking, but I have actually tried this one. The results were... awkward. Wasn't much of an improvement.
