### ISSUE TITLE
hq_train batch size

### ISSUE THREAD

**Issue by sunshower76** [Rudrabha/Wav2Lip#297]
Hello.

On the paragraph, 3.5 Generating Photo-realistic Faces, in your paper, you wrote that you trained your network with batch size of 80.

However, in haparams.py, the default batch size is 16.

which batch size is correct?

thanks.

**Comment by Mayur28** [comment]
Hi,

If you got the answer to your question, could you please share it - I also was hoping to find out about this.

Thanks.
