### ISSUE TITLE
Questions about training

### ISSUE THREAD

**Issue by primepake** [Rudrabha/Wav2Lip#299]
1. One video should contain 1 person or multiple? 
2. How much data should need for 1 person?
3. How long for a video to get the best result?
4. What is the infrastructure for training? 2 or 4 GPUS?
5. How long it takes with the above infrastructure?

**Comment by prajwalkr** [comment]
1. One person
2. We have not trained for single speaker so we do not know
3. The training takes a couple of days on a single gpu
