### ISSUE TITLE
The environment mentioned by the author cannot be installed. There are conflicts. My environment is as follows

### ISSUE THREAD

**Issue by WIKI2020** [Rudrabha/Wav2Lip#30]
The environment mentioned by the author cannot be installed. There are conflicts. My environment is as follows：

numba                     0.48.0                  
numpy                     1.17.1                  
opencv-contrib-python     4.2.0.34                
opencv-python             4.1.0.25               
openssl                   1.0.2s                       
pillow                    7.2.0                   
pip                       19.1.1                 
protobuf                  3.13.0                  
pycparser                 2.20                  
python                    3.6.9    
tensorflow                1.12.0             
torch                     1.1.0                   
torchvision               0.3.0                
tqdm                      4.45.0

**Comment by prajwalkr** [comment]
Is the above a non-conflicting environment that works?

**Comment by WIKI2020** [comment]
yse,you can try!

**Comment by prajwalkr** [comment]
Thanks! Updated the `requirements.txt`
