### ISSUE TITLE
Download visual quality discriminator weights

### ISSUE THREAD

**Issue by jagnusson** [Rudrabha/Wav2Lip#301]
Hello, thank you so much for this very interesting work! I've been very much enjoying experimenting with it. I wonder if it might be possible to make available for download a checkpoint of the trained parameters of the visual quality discriminator that was trained along with the Wav2Lip + GAN checkpoint? This would make it much easier to do further training on the high quality checkpoint. Many thanks!

**Comment by Rudrabha** [comment]
Updated in readme
