### ISSUE TITLE
Question on Audio Preprocessing

### ISSUE THREAD

**Issue by Mayur28** [Rudrabha/Wav2Lip#304]
Hi 

I noticed something unusual the audio processing that I was hoping to clarify please.

I am working with video 5536038039829982468/00026.mp4 which is 0.92 seconds long, and I am trying to extract the audio of the video to a wav format. I noticed that the resulting wav does not have the same duration as the original video (the resulting wav often has a duration of 0.96 seconds instead of 0.92 seconds). Considering that the audio and video do not have an equal duration, wouldn't this result in being out-of-sync?

**Comment by prajwalkr** [comment]
Can you check if the first 0.92 seconds of audio, video are in sync?

**Comment by Mayur28** [comment]
When I view the video, they seem to be in-sync (however, because of human perception, we would not be able to detect whether there is an insignificant lip-sync error which might have an impact on the model's performance). I verified synchronicity with SyncNet and there is an AV offset of 1.
