### ISSUE TITLE
Checkerboard Artifacts in High Resolution Image

### ISSUE THREAD

**Issue by xungeer29** [Rudrabha/Wav2Lip#306]
I want to generate high-resolution images(96x96->384x384), but there are always checkboard artifacts on the generated images, and checkboard artifacts are concentrated in the mouth area. As shown in the following two images.
![image](https://user-images.githubusercontent.com/32890569/127251187-6c2231b1-a14f-40be-ba57-8667015769f5.png)
![image](https://user-images.githubusercontent.com/32890569/127251214-38cc6ad7-2f57-4b6e-a403-df406c1546e3.png)

I have experimented with a lot of ways, such as changing deconv to unsample+conv, pixelshuffle, finetuning the author's open source model and so on. But they all failed. 

In my experiment, unsample will generate black horizontal lines, and pixelshuffle will also generate checkboard artifacts.
![image](https://user-images.githubusercontent.com/32890569/127252008-551d63f4-8f5f-4180-9742-4d2efe902537.png)
![image](https://user-images.githubusercontent.com/32890569/127252033-62214a7e-94f6-4022-9041-f259f67e6f06.png)

When I finetuning the author's open source model, there was no checkboard artifact when the image was blur, but with the the image becomes clearer, the chessboard artifact became clearer and clearer.

In addition,
1. If I remove the audio encode module, only use the image part to generate high resolution images, the generated images don't have checkboard artifacts.
2. There is no artifact on the generated image when I train the wav2lip model with 96x96 image size with my own dataset. But if I change input size to 384, the chessboard artifact emerges.
3. The `kernel_size/stride` in deconv is modified to be divisible, which cannot be improved.
4. Image smoothing loss([total_variation_denoising loss](https://en.wikipedia.org/wiki/Total_variation_denoising)) can remove checkerboard points, but the image becomes very blurred.

Anyone can help me?

**Comment by OldSixOne** [comment]
you do preprocess.py ，How big is the generated img size! I will do high-resolution

**Comment by xungeer29** [comment]
> you do preprocess.py ，How big is the generated img size! I will do high-resolution

384*384

**Comment by OldSixOne** [comment]
跑preprocess.py，生成的照片是384*384的？那你更换了face_detection Model了么

**Comment by xungeer29** [comment]
> 跑preprocess.py，生成的照片是384*384的？那你更换了face_detection Model了么
preprocess.py只裁剪出人脸，没有缩放，没有更换face_detection Model

**Comment by OldSixOne** [comment]
我也要用高清的数据，然后我现在在思考img size的尺寸，我该如何设计！！！是更改网络，还是不更改网络，就在网络推理阶段再加一个人脸修复的网络

**Comment by Hothin** [comment]
> 我也要用高清的数据，然后我现在在思考img size的尺寸，我该如何设计！！！是更改网络，还是不更改网络，就在网络推理阶段再加一个人脸修复的网络

您好，你最后用了什么方法
