### ISSUE TITLE
How to improve image clarity when training wav2lip network

### ISSUE THREAD

**Issue by yonglianglan** [Rudrabha/Wav2Lip#307]
![25_1](https://user-images.githubusercontent.com/37431477/127949247-1c3e6959-e6f1-493b-893c-471273717a87.jpg)
when training wav2lip network, l1 recon loss is 0.02 and syncnet loss is 0.17 , but the wav2lip reconstructed image is blur. how can i improve the wav2lip network training? thank you all

**Comment by prajwalkr** [comment]
You can try training the GAN version of the model. Also, the resolution handled by Wav2Lip is low, so it is an inherent problem.

**Comment by HandsLing** [comment]
@prajwalkr hello I want to know where is the GAN version of Wav2Lip model thx

**Comment by gessha** [comment]
![image](https://user-images.githubusercontent.com/5369209/202580233-275cb3f6-88c8-446c-955f-7523fd4f5160.png)

second link
