### ISSUE TITLE
 Is this log normal？

### ISSUE THREAD

**Issue by DDDlk** [Rudrabha/Wav2Lip#309]
When I train hq_wav2lip_train.py, I got this log,  Sync is always 0.0, is this normal?
![image](https://user-images.githubusercontent.com/22271047/128623918-7d313b75-6b4b-4faf-a077-e54bb16dee62.png)

**Comment by prajwalkr** [comment]
No, sync loss was always at least ~0.2  in our experiments.

**Comment by 397688551** [comment]
I am the same as you, and the value of sync is also 0.0. Do you know the reason?
