### ISSUE TITLE
How to use the GPU ?

### ISSUE THREAD

**Issue by FarangoJones** [Rudrabha/Wav2Lip#31]
Hello everyone!

After many difficulties, I finally managed to get Wav2Lip working. However, the rendering is extremely slow and makes my computer unusable for one hour. How can I activate the GPU to accelerate the computing speed?

**Comment by prajwalkr** [comment]
The code uses GPU by default. Please check why it is not using a GPU at your end.

**Comment by QUTGXX** [comment]
by the way, I want to ask for help. I tried to train the sync net with Xeon Gold 6154 and 2 v100 GPUs. But the training time is a little bit longer taking 24 seconds per step. Could u please help me to address this issue? And all the parameters keep the same as you provided.

**Comment by prajwalkr** [comment]
Can you time each step of the training loop and see what is taking time? The speed which we observed was less than a second per iteration.

**Comment by QUTGXX** [comment]
> Can you time each step of the training loop and see what is taking time? The speed which we observed was less than a second per iteration.

The following screenshot shows the result of the training loop.
![屏幕截图_1](https://user-images.githubusercontent.com/36947214/92673559-f9f78100-f34d-11ea-95ac-798d4e9bc3a7.png)

**Comment by prajwalkr** [comment]
No, this is too slow, can you please check which part of the training step is taking time to execute?

**Comment by QUTGXX** [comment]
> No, this is too slow, can you please check which part of the training step is taking time to execute?

OK, I would check it.

**Comment by QUTGXX** [comment]
> No, this is too slow, can you please check which part of the training step is taking time to execute?

Hi, I have checked.  This step ("wav = audio.load_wav(wavpath, hparams.sample_rate)") would take nearly 0.35 seconds for 75 times  (totally takes around 27 seconds) for each training loop. 
![屏幕截图_2](https://user-images.githubusercontent.com/36947214/92679369-d2f37c00-f35a-11ea-80b4-717a9581eafa.png)

**Comment by prajwalkr** [comment]
Most of those audio reads are happening in parallel (by default, there are 16 workers running in parallel). The issue is most likely somewhere else.

**Comment by QUTGXX** [comment]
> Most of those audio reads are happening in parallel (by default, there are 16 workers running in parallel). The issue is most likely somewhere else.

The sample rate of audios in my dataset is 48K, but your code would load the wav through 16k. Therefore, this step would take a longer time. When I tried to change the sample rate by FFmpeg, the training loop would take nearly 1 second.

**Comment by prajwalkr** [comment]
I assumed you are training on LRS2. So, I think the training step is fast now?

**Comment by QUTGXX** [comment]
> I assumed you are training on LRS2. So, I think the training step is fast now?

Yes. just using FFmpeg to address this issue.

**Comment by prajwalkr** [comment]
Great!! 👍

**Comment by dipam7** [comment]
Hey @QUTGXX can you tell me the command to change the sample rate of audio using ffmpeg?
