### ISSUE TITLE
Does inference.py use audio frames from i-2 to i+2 ?

### ISSUE THREAD

**Issue by 649459021** [Rudrabha/Wav2Lip#312]
I found the code about audio frames from i-2 to i+2  at  Dataset.get_segmented_mels() of train.py.
But I dont' find this in inference.py.  Does inference.py use audio frames from i to i+5 ?
By the way, what's the meaning of 0-indexing ---> 1-indexing ?

**Comment by prajwalkr** [comment]
During training, we take the center frame and the mel frames surrounding it. During inference, we simply take the mel frames available from the start. The model will generate center frames for all these mel windows.

**Comment by bd20222** [comment]
What if we feed the video frame and mel frame with the exact same timestamp during training, but don't use the surrounding mel frames?
