### ISSUE TITLE
dlib, ffmpeg version

### ISSUE THREAD

**Issue by sunshower76** [Rudrabha/Wav2Lip#313]
Hi,

I checked your requirements.txt file, but the dlib and ffmpeg version was not written in this file.

Could you update the requirements.txt file?

thanks!

I evaluate your model with the libraries below:
librosa                       0.7.0
numpy                      1.17.1
opencv-contrib-python 4.5.2.54
opencv-python            4.1.0.25
torch                        1.8.0
torchvision 0.8.0
tqdm                        4.31.1                   
numba                      0.48.0 

dlib-19.22.0
ffmpeg version 3.4.8

**Comment by prajwalkr** [comment]
requirements.txt is for performing pip install. the other non-pip requirements are mentioned in the readme
