### ISSUE TITLE
Fake/Real stay at 0.69

### ISSUE THREAD

**Issue by primepake** [Rudrabha/Wav2Lip#314]
I trained with multiple GPUs but Fake/Real just stayed at 0.69 
4 GPUs with batch_size=128

L1: 0.025484307669103146, Sync: 0.0, Percep: 0.6968241333961487 | Fake: 0.6908760070800781, Real: 0.6942079961299896: : 1it [05:02, 301.12s/L1: 0.025484307669103146, Sync: 0.0, Percep: 0.6968241333961487 | Fake: 0.6908760070800781, Real: 0.6942079961299896: : 2it [05:02, 211.17s/L1: 0.025484307669103146, Sync: 0.0, Percep: 0.6968241333961487 | Fake: 0.6908760070800781, Real: 0.6942079961299896: : 2it [05:02, 151.27s/it]

I don't know what the reason is?

**Comment by zswzifir** [comment]
> I trained with multiple GPUs but Fake/Real just stayed at 0.69 4 GPUs with batch_size=128
> 
> L1: 0.025484307669103146, Sync: 0.0, Percep: 0.6968241333961487 | Fake: 0.6908760070800781, Real: 0.6942079961299896: : 1it [05:02, 301.12s/L1: 0.025484307669103146, Sync: 0.0, Percep: 0.6968241333961487 | Fake: 0.6908760070800781, Real: 0.6942079961299896: : 2it [05:02, 211.17s/L1: 0.025484307669103146, Sync: 0.0, Percep: 0.6968241333961487 | Fake: 0.6908760070800781, Real: 0.6942079961299896: : 2it [05:02, 151.27s/it]
> 
> I don't know what the reason is?

Hi, I would wonder have you finally this problem？

**Comment by windTwT** [comment]
> I trained with multiple GPUs but Fake/Real just stayed at 0.69 4 GPUs with batch_size=128
> 
> L1: 0.025484307669103146, Sync: 0.0, Percep: 0.6968241333961487 | Fake: 0.6908760070800781, Real: 0.6942079961299896: : 1it [05:02, 301.12s/L1: 0.025484307669103146, Sync: 0.0, Percep: 0.6968241333961487 | Fake: 0.6908760070800781, Real: 0.6942079961299896: : 2it [05:02, 211.17s/L1: 0.025484307669103146, Sync: 0.0, Percep: 0.6968241333961487 | Fake: 0.6908760070800781, Real: 0.6942079961299896: : 2it [05:02, 151.27s/it]
> 
> I don't know what the reason is?

hi! do you solve the problem?

**Comment by hannarud** [comment]
Hi @primepake! As you closed the issue, you probably found the solution to that? Could you share it, please?

**Comment by primepake** [comment]
you should check your dataset carefully, using syncnet python to filter your dataset

**Comment by hannarud** [comment]
Thank you for the response!
What kind of problems should I check for? Video image & sound not synced? Or faces detected not everywhere?

**Comment by primepake** [comment]
you can check my repo for detail

https://github.com/primepake/wav2lip_288x288/issues/21

**Comment by Utkarsh-shift** [comment]
why is L1: 0.023011334964113256, Sync: 0.0, Percep: 0.9181626143044983 | Fake: 0.5949714519330208, Real: 0.5965797347869831: : 452it [01:38,  5.89iL1: 0.023011334964113256, Sync: 0.0, Percep: 0.9181626143044983 | Fake: 0.5949714519330208, Real: 0.5965797347869831: : 453it [01:38,  5.78i] 
the sync loss is always : 0.0
