### ISSUE TITLE
The lip color is darker than a original video

### ISSUE THREAD

**Issue by freecui** [Rudrabha/Wav2Lip#315]
The problem is that the lip's color of a video from inference.py is darker than a original video

This is original video:
![original](https://user-images.githubusercontent.com/8288975/131793860-8075782c-b4e6-425b-83f6-4a1e573cfc63.jpg)

**Comment by freecui** [comment]
the  video from inference.py :
![infernce](https://user-images.githubusercontent.com/8288975/131793969-4124493f-da17-4318-8468-4831d0e6e81d.jpg)

**Comment by prajwalkr** [comment]
We are not sure why this happens. If you want superior results for a specific speaker, then training a sepearate model for that speaker should give you better results.
