### ISSUE TITLE
Higher Quality MODEL... Soon ?

### ISSUE THREAD

**Issue by AlonDan** [Rudrabha/Wav2Lip#316]
Many months ago I think it was mentioned that a better high-res model is on the working and will released soon.

It's been a while, and since it's very hard for newbies to understand or follow the current documents in order to train our own models, unfortunately, there are no step-by-step tutorials written or in YouTube at the moment.

I would train my own model if it wasn't so hard and complicated to understand how to do, but I tried and it's very complicated.

---
Is there a chance that a High Quality Model will be released soon? or higher-quality model in any way instead of the low-res current one?

Thanks ahead!

**Comment by prajwalkr** [comment]
> Is there a chance that a High Quality Model will be released soon?

Please check the frirst  line of the README

**Comment by AlonDan** [comment]
> > Is there a chance that a High Quality Model will be released soon?
> 
> Please check the first line of the README

Sorry, maybe you can help because I didn't find the instructions for how to use a **High Quality Model** in the Readme as you suggest in the first line:
`# **Wav2Lip**: *Accurately Lip-syncing Videos In The Wild*`

or also later on when I tried to look for an answer to my question above, high quality model instead of the original model.
Can you please tell me where it is so I can try and follow?

---
I tried to guess how to do it, because I really don't have a clue and there are no tutorials or good guides to explain how it's done:
I tried to replace the original (older) model: 🔸wav2lip_gan.pth🔸  with the 🔹visual_quality_disc.pth🔹 but it crashes... so I'm not sure how to make it work.
I just replaced it on the command, maybe I'm missing something?

How can I make it work with the 🔹visual_quality_disc.pth🔹 ?
do I need to change or add something to the command?

If anyone can give an example how to use the High Quality Model by making a short step-by-step tutorial please it will be very helpful for many people who wants to experiment and test.

Thanks ahead!

**Comment by Ha0Tang** [comment]
@AlonDan have you figured out how to use the visual_quality_disc.pth?

**Comment by AlonDan** [comment]
@Ha0Tang  Unfortunately there is no solution or support or step-by-step tutorial to explain how to make it work correct.
