### ISSUE TITLE
💡 IDEA / SUGGESTION: When NOT talking = Closed Mouth ? 💋

### ISSUE THREAD

**Issue by AlonDan** [Rudrabha/Wav2Lip#317]
I noticed that if there is no talking (in the WAV sound file) the original video will keep talking.
I wonder if it will be possible to make that while during the WAV sound there is silence (or nothing) the mouth will be closed.

For example if the WAV sound is 10 seconds, but there is 3 seconds of silence inside, during the 3 seconds the mouth will be closed all the time. it will be really nice to test something like that.

* This could be as an extra option, not a must use by default. 
Example  command:  --SilenceMouthClosed (or anything like that)

Thanks ahead, keep up the good work on this wonderful project! :)

**Comment by prajwalkr** [comment]
It is an interesting idea. But such a control is very hard to incorporate into a deep learning model, at least with the one we have.
