### ISSUE TITLE
Training not working 

### ISSUE THREAD

**Issue by qustions** [Rudrabha/Wav2Lip#32]
Hi, @prajwalkr I am trying to train   hq_wav2lip_train but I have waited nearly 1 hour but nothing happened my GPU is using only 984mb and all my CPUs are been used.
here is the command that I have run.
`python hq_wav2lip_train.py --data_root lrs2_preprocessed/ --checkpoint_dir train_checkpoint --syncnet_checkpoint_path checkpoints/lipsync_expert.pth`
Output
```
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
env/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

use_cuda: True
total trainable params 36298035
total DISC trainable params 14113793
Load checkpoint from: checkpoints/lipsync_expert.pth
Starting Epoch: 0
0it [00:00, ?it/s]
``` 
CPU Usage 
![image](https://user-images.githubusercontent.com/65636785/92609806-9b41f100-f2d4-11ea-816f-b0791fd8c9e4.png)
GPU Usage 

![image](https://user-images.githubusercontent.com/65636785/92610678-9a5d8f00-f2d5-11ea-9107-29ca60307759.png)

**Comment by prajwalkr** [comment]
So the dataloader keeps continuing if the training images/audios are absent. Please check if you have provided the right path, and also add print statements in the dataloader to check where it is stuck in an infinite loop.

**Comment by qustions** [comment]
@prajwalkr thanks for the reply have solved it by checking the directory which was not having .jpg inside it. I have 2 questions 

1. Traning started successfully but It's not saving weights.
2. When should I stop training and what is `L1`, `Sync`, `Percep`, `Fake`, `Real` by seeing what var should I decide how is the training going 
```
L1: 0.03487106040120125, Sync: 0.0, Percep: 27.63102149963379 | Fake: 0.0, Real: 27.63102149963379: : 1it [00:02,  2.13s/it]
Starting Epoch: 771
L1: 0.03605598956346512, Sync: 0.0, Percep: 27.63102149963379 | Fake: 0.0, Real: 27.63102149963379: : 1it [00:02,  2.12s/it]
Starting Epoch: 772
L1: 0.03456452488899231, Sync: 0.0, Percep: 27.63102149963379 | Fake: 0.0, Real: 27.63102149963379: : 1it [00:02,  2.13s/it]
Starting Epoch: 773
```

**Comment by prajwalkr** [comment]
why is your training epoch only 1it? The checkpoint saves for every 2000 or 3000 iterations.

**Comment by qustions** [comment]
thanks for the reply its default 1it only where can i change it

**Comment by qustions** [comment]
No, I am Training  it on the `Lip2Wav`  Chemistry Lectures dataset

**Comment by Rudrabha** [comment]
It may be better to resample any dataset you use to 25 fps. The chemistry lecture dataset is 30 fps. Also, do let us know about the results you achieve.

**Comment by qustions** [comment]
Ok I will let you know about the results soon thank you for your time

**Comment by HaSaKiYasuooo** [comment]
filelist是手动写入吗，我在预处理之后并没有文件内容生成
![image](https://github.com/Rudrabha/Wav2Lip/assets/87591236/7ac1ce4b-eb81-4a82-b8db-63bb5a3d2834)

**Comment by pikeyang** [comment]
> filelist是手动写入吗，我在预处理之后并没有文件内容生成 ![image](https://user-images.githubusercontent.com/87591236/254503539-7ac1ce4b-eb81-4a82-b8db-63bb5a3d2834.png)

是[下载](https://www.robots.ox.ac.uk/~vgg/data/lip_reading/lrs2.html)的
<img width="561" alt="image" src="https://github.com/Rudrabha/Wav2Lip/assets/59758624/9db8c3fd-8176-47c1-ab59-e26be594df33">

**Comment by Utkarsh-shift** [comment]
can you give the new __getitem__ ?
