### ISSUE TITLE
mouth too fast 

### ISSUE THREAD

**Issue by primepake** [Rudrabha/Wav2Lip#321]
why mouth is too fast?
my video link: https://drive.google.com/file/d/1fRFQeBuOR6fg5bvE5RXwMxfUkLWvLFtC/view?usp=sharing

**Comment by fancat-programer** [comment]
I encountered the same problem

**Comment by OldSixOne** [comment]
your face size is 96 * 96 ?

**Comment by primepake** [comment]
> your face size is 96 * 96 ?

yup, what is the problem?

**Comment by OldSixOne** [comment]
After training, I found that the mouth in the generated video was closed slightly.

**Comment by primepake** [comment]
I see that it's different from the author's demo video

**Comment by OldSixOne** [comment]
> I see that it's different from the author's demo video

I agree with you，and I trained step by step as the author said. I don't know why this happened.Gan network is so powerful that it's really hard to train.

**Comment by VERMANs** [comment]
I also have a similar problem, have you solved it?

**Comment by sedanijay** [comment]
change the value of mel_idx_multiplier in inference.py 
works for me.

**Comment by 1105135335** [comment]
How do you handle this situation
