### ISSUE TITLE
HD Model 288x288 Implementation 

### ISSUE THREAD

**Issue by primepake** [Rudrabha/Wav2Lip#328]
Thanks for your dedication and great results, I would like to contribute some of my improvements on Loss Function, Activation, Size of Input Image. I have added some layers and the model can be trained with size 288x288. But when using this version, you have to spend a lot of money on infrastructure

https://github.com/primepake/wav2lip_288x288

**Comment by zhongweizhi123** [comment]
> Thanks for your dedication and great results, I would like to contribute some of my improvements on Loss Function, Activation, Size of Input Image. I have added some layers and the model can be trained with size 288x288. But when using this version, you have to spend a lot of money on infrastructure
> 
> https://github.com/primepake/wav2lip_288x288

Hi~, what about the result of your version
