### ISSUE TITLE
SyncNet fails if batch_size set to 1 in hparams.py

### ISSUE THREAD

**Issue by siddu9501** [Rudrabha/Wav2Lip#34]
raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 512, 1, 1])

input to syncnet:
torch.Size([1, 15, 48, 96]) torch.Size([1, 1, 80, 16])

Does the syncnet batch_size have to be a specific ratio of batch_size used for the GAN?

**Comment by siddu9501** [comment]
A quick fix that worked for me is 

```
def get_sync_loss(mel, g):
    g = g[:, :, :, g.size(3)//2:]
    g = torch.cat([g[:, :, i] for i in range(syncnet_T)], dim=1)
    # B, 3 * T, H//2, W
    if g.size(0) ==1:
        mel = mel.repeat(2,1,1,1)
        g = g.repeat(2,1,1,1)
    a, v = syncnet(mel, g)
    y = torch.ones(g.size(0), 1).float().to(device)
    return cosine_loss(a, v, y)
```

**Comment by prajwalkr** [comment]
Why do you have to train with batch size 1?

**Comment by siddu9501** [comment]
I'm training on higher resolution and my GPU memory prevents me rom going any higher than batch size 1

**Comment by prajwalkr** [comment]
Please change the architecture to suit larger images. Ensure you are able to train with batch size at least 4-8 for batch normalisation to work decently.

**Comment by dipam7** [comment]
What changes will be required to the architecture for the same?
