### ISSUE TITLE
"import torch" giving error "from torch._C import *, DLL load failed: The specified module could not be found"

### ISSUE THREAD

**Issue by BrutalCaeser** [Rudrabha/Wav2Lip#341]
1. Do we need to use python 3.6 exclusively or can a higher version be used?
2.  Does the cuda toolkit for pytorch need to be downloaded or can it run on only cpu?

**Comment by NithinJangid** [comment]
For the first question, I would recommend using python3.6 version.

As of for second use this pip command to install torch with cuda support
- pip3 install torch==1.9.1+cu111 torchvision==0.10.1+cu111 torchaudio==0.9.1 -f https://download.pytorch.org/whl/torch_stable.html

First uninstall all pytorch/torch dependencies/packages and then use above command to install.

**Comment by prajwalkr** [comment]
Adding to the previous answer, the model can run on cpu, although it will be very slow.
