### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy'

### ISSUE THREAD

**Issue by Frehyyy** [Rudrabha/Wav2Lip#343]
ModuleNotFoundError: No module named 'numpy'
![image](https://user-images.githubusercontent.com/89162555/150793881-11531fc1-aea3-4423-83b3-9a1e5fb0410d.png)

**Comment by Frehyyy** [comment]
plz help

**Comment by prajwalkr** [comment]
Please install the requirements.txt packages.
