### ISSUE TITLE
When trying to install pip install -r requirements.txt. How to correct a mistake?

### ISSUE THREAD

**Issue by Frehyyy** [Rudrabha/Wav2Lip#345]
![image](https://user-images.githubusercontent.com/89162555/151034548-97f4cce6-f96a-476e-881a-35e7146370c1.png)
When trying to install `pip install -r requirements.txt`

**Comment by sahilg06** [comment]
@Frehyyy You can replace == with >= in all the requirements in the file. Then it will work fine ig.
