### ISSUE TITLE
Data Pipeline and Processing Question 

### ISSUE THREAD

**Issue by ayush714** [Rudrabha/Wav2Lip#348]
Hi, 

I have a question which is How I can prepare my custom dataset, let's say I have some video and audio of the same duration, So can you tell me about folder structure I got confused when reading the readme about this, and here's what I understand:- 

I don't understand what we have to put in main and what is the list of folders, It would be better if you could elaborate in detail with samples!! 

```
data_root (mvlrs_v1)
├── main, pretrain (we use only main folder in this work)
|	├── list of folders
|	│   ├── five-digit numbered video IDs ending with (.mp4)
```

**Comment by ljy-002** [comment]
+1

**Comment by sahilg06** [comment]
Hi @ayush714, Actually this folder structure is according to the **lrs2** dataset, for any other dataset you can simply pass a folder of videos as data_root after doing some minor changes in **preprocess.py**.
And about the given folder structure in the readme:
When you download the lrs2 dataset, you get some folders(each folder contain multiple videos) and all those folders are put in the main

**Comment by ayush714** [comment]
Hi @sahilg06 , I tried and it worked, but when training, it is asking for train.txt, val.txt, so how should I prepare it?

**Comment by sahilg06** [comment]
@ayush714  These files are just required for train and validation split. So there is an argument named **split**[ here](https://github.com/Rudrabha/Wav2Lip/blob/b9759a3467cb1b7519f1a3b91f5a84cb4bc1ae4a/color_syncnet_train.py#L39) which they pass to [this](https://github.com/Rudrabha/Wav2Lip/blob/b9759a3467cb1b7519f1a3b91f5a84cb4bc1ae4a/hparams.py#L4) function to get train or validation dataset respectively.
You can change [this ](https://github.com/Rudrabha/Wav2Lip/blob/b9759a3467cb1b7519f1a3b91f5a84cb4bc1ae4a/color_syncnet_train.py#L39) line according to your dataset to read all the videos i.e. eliminating the use of those files named train.txt, val.txt etc.
eg:  `self.all_videos = [f for f in os.listdir(args.data_root) if isdir(join(args.data_root, f))]`

**Comment by ayush714** [comment]
Hi @sahilg06 , It now worked, but I am having an issue, I am only training on 3 videos, just to check it is working or not, but it is taking so much time!! Why it is so? Is it normal or not? any suggestions for faster training!
 
![image](https://user-images.githubusercontent.com/81796368/152944916-f44dfe9a-f904-4ca5-a6a6-f7c5fd91222b.png)

**Comment by sahilg06** [comment]
Yeah, it's normal I guess. Idk how to train it faster except using a more powerful GPU😅

**Comment by ayush714** [comment]
Hi @sahilg06 Can u check me new issues, I have posted it

**Comment by tushar7770** [comment]
@ayush714 I am also training but it is at the 0th iteration and not proceeding further. Did you get any solution?
