### ISSUE TITLE
RuntimeError: Image too big to run face detection on GPU. Please use the --resize_factor argument

### ISSUE THREAD

**Issue by Nyrize** [Rudrabha/Wav2Lip#367]
So, I am getting this error even after I am using resize_factor 2
I tried it without using it by directly using a 720p and 480p video as input but the issue persists.

With the same inputs on a 1050ti machine, even though inference is slow I get a result.
but when using the same input for inference on a 3060 machine, I get this error.
Please, help!

**Comment by edmundman** [comment]
how did you solve?

**Comment by YinqiCai** [comment]
> how did you solve?

you can see this issue. https://github.com/Rudrabha/Wav2Lip/issues/231

**Comment by venxzw** [comment]
@Nyrize have you solved this problem
