### ISSUE TITLE
about training samples

### ISSUE THREAD

**Issue by T5eng** [Rudrabha/Wav2Lip#375]
I tried to fine-tune the pre-train model with official LRS2 dataset and my own dataset.

Looks like what the model learned at training phase is simply copying the lower half face to the generated image.
The first 2 images are sampled from LRS2, and the last from my own dataset.
from left to right are reference, input, generated and gt frames
![image](https://user-images.githubusercontent.com/14946599/163952777-e06584fd-5433-42f6-83c1-808b9a006b26.png)
![image](https://user-images.githubusercontent.com/14946599/163955272-99020c82-12a0-4779-a78b-b6df9e2e3c3c.png)
![image](https://user-images.githubusercontent.com/14946599/163955508-095cfa80-09b5-46f0-a465-c6723e737404.png)

**Comment by trivikramak** [comment]
Hi, Could you get access to the LRS2 dataset?

**Comment by T5eng** [comment]
apply for it at the official website. 
pre-process code is included in wav2lip source code. :)

**Comment by hnsywangxin** [comment]
@T5eng I have the same problem, can you tell me how to solve it.
thank you

**Comment by ranck626** [comment]
+1
