### ISSUE TITLE
Assertion `input_val >= zero && input_val <= one` failed.

### ISSUE THREAD

**Issue by Quanta-of-solitude** [Rudrabha/Wav2Lip#384]
So running the command:

python color_syncnet_train.py --data_root preprocessedData/ --checkpoint_dir checkpoints

use_cuda: True
total trainable params 19881059
0it [00:00, ?it/s]Saved checkpoint: checkpoints/checkpoint_step000000001.pth
Loss: 1.130293607711792: : 1it [12:44, 764.86s/it]
Loss: 0.9026422500610352: : 1it [14:37, 877.93s/it]
Loss: 1.0647838115692139: : 1it [14:40, 880.54s/it]
Loss: 1.0123388767242432: : 1it [15:36, 936.53s/it]
Loss: 0.9266862869262695: : 1it [15:00, 900.80s/it]
Loss: 0.8942291140556335: : 1it [13:57, 837.86s/it]
Loss: 1.0073713064193726: : 1it [15:19, 919.58s/it]
Loss: 1.0768300294876099: : 1it [15:41, 941.04s/it]
Loss: 0.9291326999664307: : 1it [16:07, 967.90s/it]
Loss: 0.9046692848205566: : 1it [13:43, 823.88s/it]
Loss: 0.6578884720802307: : 1it [16:10, 970.35s/it]
Loss: 1.1847789287567139: : 1it [12:44, 764.03s/it]
Loss: 1.0758931636810303: : 1it [12:53, 773.66s/it]
Loss: 0.9432123899459839: : 1it [13:43, 823.22s/it]
Loss: 1.0592972040176392: : 1it [14:08, 848.07s/it]
Loss: 0.8582468032836914: : 1it [16:44, 1004.22s/it]
Loss: 0.9379435777664185: : 1it [14:03, 843.51s/it]

0it [00:00, ?it/s]/pytorch/aten/src/ATen/native/cuda/Loss.cu:115: operator(): block: [0,0,0], thread: [37,0,0] Assertion `input_val >= zero && input_val <= one` failed.
0it [16:28, ?it/s]
Traceback (most recent call last):
File "color_syncnet_train.py", line 279, in <module>
nepochs=hparams.nepochs)
File "color_syncnet_train.py", line 162, in train
loss.backward()
File "/home/Wav2Lip/env/lib/python3.6/site-packages/torch/_tensor.py", line 307, in backward
torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
File "/home/Wav2Lip/env/lib/python3.6/site-packages/torch/autograd/__init__.py", line 156, in backward
allow_unreachable=True, accumulate_grad=True) # allow_unreachable flag
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by Teoge** [comment]
@Quanta-of-solitude I had the same problem. How did you fix it?

**Comment by WinstonDeng** [comment]
use `logloss = nn.BCEWithLogitsLoss()`
not `logloss = nn.BCELoss()`

**Comment by aishoot** [comment]
> 

Nice! it works

**Comment by HaSaKiYasuooo** [comment]
> 所以运行命令：
> 
> python color_syncnet_train.py --data_root preprocessedData/ --checkpoint_dir 检查点
> 
> use_cuda：真正的 总可训练参数19881059 0it [00:00，？it/s]保存的检查点：checkpoints/checkpoint_step000000001.pth 损失：1.130293607711792：：1it [12：44，764.86s/it] 损失：0.902642250 0610352: : 1it [14 :37, 877.93s/it] 丢失: 1.0647838115692139: : 1it [14:40, 880.54s/it] 丢失: 1.0123388767242432: : 1it [15:36, 936.53s/it] 丢失: 0.92668628 69262695: : 1it [15:00 , 900.80s/it] 丢失: 0.8942291140556335: : 1it [13:57, 837.86s/it] 丢失: 1.0073713064193726: : 1it [15:19, 919.58s/it] 丢失 : 1.07683002948 76099: : 1it [15:41, 941.04 s/it] 损失: 0.9291326999664307: : 1it [16:07, 967.90s/it] 损失: 0.9046692848205566: : 1it [13:43, 823.88s/it] 损失: 0.6578884720802307: : 1it [16:10, 970.35s/it] 损失: 1.1847789287567139: : 1it [12:44, 764.03s/it] 损失: 1.0758931636810303: : 1it [1 2:53, 773.66s/it] 损失： 0.9432123899459839: : 1it [13:43, 823.22s/it] 丢失: 1.0592972040176392: : 1it [14:08, 848.07s/it] 丢失: 0.8582468032836914: : 1it [16:4 4、1004.22s/it] 损失：0.9379435777664185： : 1it [14:03, 843.51s/it]
> 
> 0it [00:00，？it/s]/pytorch/aten/src/ATen/native/cuda/Loss.cu:115：运算符（）：块：[0,0,0]，线程：[37,0 ,0] 断言`input_val >= zero && input_val <= one`失败。 0it [16:28，？it/s] 回溯（最近一次调用）： 文件“color_syncnet_train.py”，第 279 行，在 nepochs=hparams.nepochs） 文件“color_syncnet_train.py”，第 162 行，在列车 丢失中。向后（） 文件“/home/Wav2Lip/env/lib/python3.6/site-packages/torch/_tensor.py”，第307行，向后 torch.autograd.backward（self，gradient，retain_graph，create_graph，inputs =输入） 文件“/home/Wav2Lip/env/lib/python3.6/site-packages/torch/autograd/ **init** .py”，第156行，向后 allow_unreachable=True， 运行时错误：CUDA 错误：设备端断言触发的 CUDA 内核错误可能会在某些其他 API 调用中异步报告，因此下面的堆栈跟踪可能不正确。 对于调试，请考虑传递 CUDA_LAUNCH_BLOCKING=1。

你好，我想问一下filelist的文件在预处理的时候没有自动生产，怎么解决
