### ISSUE TITLE
unrecognized arguments

### ISSUE THREAD

**Issue by echosvile** [Rudrabha/Wav2Lip#386]
Please i used the argument as shown in the code `python inference.py --checkpoint_path <ckpt> --face <video.mp4> --audio <an-audio-source>`

and typed it like this
`python inference.py --checkpoint_path checkpoints/wav2lip.pth --face video/silver.MP4 --audio audio/michele.mp3`

It shows me the image attached here
![face](https://user-images.githubusercontent.com/71806009/170837369-118374e0-25ee-4dde-8815-0a2f41c3e833.png)
e

**Comment by instant-high** [comment]
try
--face video/silver.mp4 
instaed of
--face video video/silver.mp4

path to video not correct

**Comment by echosvile** [comment]
I was able to figure out what the problem was which was from me: i didn't download the face detection file (sfd...) neither did I copy the the facedetection folder. So it went well after the copying and pasting
