### ISSUE TITLE
module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline'

### ISSUE THREAD

**Issue by Unmesh28** [Rudrabha/Wav2Lip#387]
I am trying to run inference, getting this error :

AttributeError: module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline'

Running on Windows 11, Cuda : 10

**Comment by Hparvaresh** [comment]
same error when importing cv2.
on linux with no cuda. and linux with cuda 11.6.

AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)

**Comment by Tanaanan** [comment]
same here do u got any solution?

**Comment by Unmesh28** [comment]
Try This :

`pip install "opencv-python-headless<4.3"`

It solved my issue

**Comment by Henu-ZhangGao** [comment]
> Try This :
> 
> `pip install "opencv-python-headless<4.3"`
> 
> It solved my issue

Thanks dude, i can successfully run it by that command

**Comment by PAVANKUMARRB123** [comment]
Thank you . solved my issue

**Comment by PAVANKUMARRB123** [comment]
can you please let us know the reason on how issue got resolved ?

**Comment by Unmesh28** [comment]
@PAVANKUMARRB123 , I also don't know the exact ans for your question. I was just digging into the issue then searched in opencv repo, there I found some people facing similar issues. You can check the thread : https://github.com/opencv/opencv-python/issues/591

They say it has something to do with [backward compatibility](https://github.com/opencv/opencv-python#backward-compatibility) was dropped since 4.3.0.

**Comment by PAVANKUMARRB123** [comment]
Thank you for the information.

**Comment by anupkafle** [comment]
Thanks dude
