### ISSUE TITLE
Inference Stuck at start 

### ISSUE THREAD

**Issue by Unmesh28** [Rudrabha/Wav2Lip#388]
I tried running inference, getting no error but its stuck : 

<img width="926" alt="Screenshot 2022-06-13 at 11 19 27 AM" src="https://user-images.githubusercontent.com/11707809/173288107-60b06937-9914-4bfb-ab69-790912246fb6.png">

Running on Ubuntu 18.04, Cuda : 10.1

**Comment by 101arrowz** [comment]
Encountered this myself, the face detection model is inexplicably slow. Just use a fixed bounding box or implement face detection yourself, it's not very difficult with the OpenCV HAAR cascade classifier.

**Comment by Unmesh28** [comment]
Hey @101arrowz , Thanks for replying. For me the issue was with torch version. 

`conda install pytorch torchvision cudatoolkit=11 -c pytorch-nightly`

This solved my issue.
