### ISSUE TITLE
The code stuck at selecting device while preprocessing 

### ISSUE THREAD

**Issue by Unmesh28** [Rudrabha/Wav2Lip#389]
I am trying to train the model on my own dataset. When I started preprocessing, the code is getting stuck while selecting the device :

<img width="1052" alt="Screenshot 2022-06-14 at 5 32 57 PM" src="https://user-images.githubusercontent.com/11707809/173572974-32fd4bbf-03aa-4456-82bb-51d75ed8fd96.png">

Everything is correctly installed with Cuda 11.4, Ubuntu 18.04 

Screenshot of of nvidia-smi adding below 

<img width="361" alt="Screenshot 2022-06-14 at 5 38 36 PM" src="https://user-images.githubusercontent.com/11707809/173573661-12aa7efa-ce1d-4ade-b68a-28b1617b8d05.png">

**Comment by anikdatos** [comment]
Did you try 
https://stackoverflow.com/questions/54216920/how-to-use-multiple-gpus-in-pytorch

**Comment by Unmesh28** [comment]
@anikdatos I had tried that,  I was able to fix the issue with playing versions of cuda and pytorch. Best solution I found is :

`conda install pytorch torchvision cudatoolkit=11 -c pytorch-nightly`
