### ISSUE TITLE
Link to pretrained of Expert discriminator not exist

### ISSUE THREAD

**Issue by vietnvri** [Rudrabha/Wav2Lip#4]
I can't access to link pretrained of expert discriminator,
Please show me the link.

Thanks,

**Comment by Rudrabha** [comment]
I have updated the readme with the weights. The link is [here](https://iiitaphyd-my.sharepoint.com/:u:/g/personal/radrabha_m_research_iiit_ac_in/EQRvmiZg-HRAjvI6zqN9eTEBP74KefynCwPWVmF57l-AYA?e=ZRPHKP).
