### ISSUE TITLE
Question regarding sr in audio.load_wav

### ISSUE THREAD

**Issue by jays0606** [Rudrabha/Wav2Lip#40]
In line 221 in inference.py, sr has been set to 16000, and mel_idx_multiplier has been set to 80./fps . Is there any particular reason you chose these numbers?? 
Thank you very much

**Comment by prajwalkr** [comment]
One second yields 80 timesteps of mel and 25 video frames (FPS). So to get the mel window for ith frame...

**Comment by jays0606** [comment]
Thank you very mcuh!

**Comment by anesum99** [comment]
> One second yields 80 timesteps of mel and 25 video frames (FPS). So to get the mel window for ith frame...

how do we get 80 time steps for one second?

**Comment by aflyingnoob** [comment]
> > One second yields 80 timesteps of mel and 25 video frames (FPS). So to get the mel window for ith frame...
> 
> how do we get 80 time steps for one second? What determines the number of mels per second?

hop_length is 200 points, so every second, the 16000 points would generate 80 number of frames
