### ISSUE TITLE
GAN training from scratch too erratic

### ISSUE THREAD

**Issue by siddu9501** [Rudrabha/Wav2Lip#41]
Is there a random seed that works well consistently.

During training, the loss gets stuck on either Real / Fake. 
This was trained from scratch on a dataset of my own. Single Identity with about ~3 hr videos

```
L1: 0.003016742644831538, Sync: 0.0, Percep: 0.7017908990383148 | Fake: 0.6846120357513428, Real: 0.7016448080539703: : 2it [00:03,  1.65s/it]Starting Epoch: 19022

L1: 0.003017835319042206, Sync: 0.0, Percep: 14.170929253101349 | Fake: 0.3378826081752777, Real: 14.172042548656464: : 2it [00:03,  1.66s/it]Starting Epoch: 19023

L1: 0.003155902144499123, Sync: 0.0, Percep: 27.63102149963379 | Fake: 0.0, Real: 27.63102149963379: : 2it [00:03,  1.65s/it]Starting Epoch: 19024

L1: 0.003000790602527559, Sync: 0.0, Percep: 27.63102149963379 | Fake: 0.0, Real: 27.63102149963379: : 2it [00:03,  1.66s/it]Starting Epoch: 19025

```

I'hv also seen this happening once the syncnet_wt gets set to 0.03 ;

**Comment by prajwalkr** [comment]
Hello, 

I see you are training on your own dataset. We suggest you train without GAN first in that case. If it works, then try with a GAN after that.

**Comment by siddu9501** [comment]
I'll try that. Thank you
