### ISSUE TITLE
ValueError: Face not detected! Ensure the video contains a face in all the frames.

### ISSUE THREAD

**Issue by ak9250** [Rudrabha/Wav2Lip#42]
is it possible to run inference on non faces similar to this paper
https://arxiv.org/abs/2004.12992v1

**Comment by prajwalkr** [comment]
Please paste your input video here?

**Comment by ak9250** [comment]
@prajwalkr I am using a image
<img width="154" alt="Screen Shot 2020-09-11 at 7 11 24 PM" src="https://user-images.githubusercontent.com/6818285/92980038-9b6ff700-f462-11ea-82dd-5948e5031f70.png">

**Comment by prajwalkr** [comment]
Please use the `--box` argument and give it a try.

**Comment by dndwoasd** [comment]
> Please use the `--box` argument and give it a try.

Of course I apologize for my stupidity, but where do I enter --box? I run in google colab

**Comment by chikiuso** [comment]
Hi @prajwalkr , may I ask what value should be put in --box to skip a missing face frame? Should it be [0,0,0,0]? I just tried but failed thanks.

**Comment by sumaliqinghua** [comment]
> 

Have you resolved this question? I have the same problem.

**Comment by tinchoforever** [comment]
Same issue here

**Comment by sbt5731** [comment]
Guys I am having the same error can you please resolve it

**Comment by rithikg24** [comment]
> Please use the `--box` argument and give it a try.
@prajwalkr could give sample values for this?

**Comment by RAJGUPTA28** [comment]
can you please explain how to use --box argument. , what should be 4 values along with it so that frames that does not have any face shall be ignored
