### ISSUE TITLE
Exported Video Shorter Than Imported Video

### ISSUE THREAD

**Issue by kilerb** [Rudrabha/Wav2Lip#43]
I believe this happens every time, or at least most...  The outputted video is just shorter than what goes into it.  BTW, when I create my input_audio.wav and my input_vid.mp4, I create them in premiere and the have the exact same time span.  If the video is 4.8 seconds, the audio is as well.  Output vid is shorter though.  Thanks!

**Comment by prajwalkr** [comment]
The current code does not generate one last frame. That is why the output video is always ~200ms or so shorter.

**Comment by prajwalkr** [comment]
Please pull the latest code and let me know if it works smoothly. Getting an exact output video length is difficult since the audio is chunked into equal segments and if it is not equally divisible, it is an issue. The latest change will get you to the closest possible, I think.

**Comment by kilerb** [comment]
Thanks!  I will try it when at the computer later today.  BTW, love the
software.  Sorry if this is off topic, but is there a way to up the
resolution or lower the compression on my end?  Higher batch size?  It
always drops to 8 whether I'm on colab, or my titan 24gb vram card or even
my rtx8000 48gb vram card.  Would love to maintain the resolution a bit
more if possible.  Thanks!!!

**Comment by prajwalkr** [comment]
Hello, the reason for lower resolution is that the model is trained on LRS2, which are low res videos.

**Comment by kilerb** [comment]
Gotcha...  any plans to upgrade the model type? :))

**Comment by prajwalkr** [comment]
Currently looking for ways to do that! We will update the repo once that happens! :)

**Comment by kilerb** [comment]
Any luck on a commercial model by chance?  The only option I have right now
is to dot he low resolution wav2lip, mask out the mouth and then make a
deepfake over it on the original video to bring the resolution back.  Such
a long process.  Love to get something better without all these steps.
Thanks!!
