### ISSUE TITLE
The specific meaning of i-2 in wav2lip_train.py

### ISSUE THREAD

**Issue by old-fan-kk** [Rudrabha/Wav2Lip#45]
_Hi, thank you for sharing this code.
Why is i-2 used in the following code._

```
def get_segmented_mels(self, spec, start_frame):
        mels = []
        assert syncnet_T == 5
        start_frame_num = self.get_frame_id(start_frame) + 1 # 0-indexing ---> 1-indexing
        if start_frame_num - 2 < 0: return None
        for i in range(start_frame_num, start_frame_num + syncnet_T):
            m = self.crop_audio_window(spec, i - 2)
            if m.shape[0] != syncnet_mel_step_size:
                return None
            mels.append(m.T)

        mels = np.asarray(mels)

        return mels
```

**Comment by prajwalkr** [comment]
For each frame that is to be generated, we feed an audio window around that frame as input. The audio window size is `200ms = 5 video frames`. So, essentially, to get an audio window of size `200ms = 5 video frames` surrounding a frame `i`, we crop an audio window starting from frame `i - 2` to `i + 2` (5 frames).

**Comment by QUTGXX** [comment]
> For each frame that is to be generated, we feed an audio window around that frame as input. The audio window size is `200ms = 5 video frames`. So, essentially, to get an audio window of size `200ms = 5 video frames` surrounding a frame `i`, we crop an audio window starting from frame `i - 2` to `i + 2` (5 frames).

Is it better to learn the audio features that matching the video frames?

**Comment by prajwalkr** [comment]
The video frame is the center of that audio window. So, the audio and video frames match.

**Comment by 649459021** [comment]
> The video frame is the center of that audio window. So, the audio and video frames match.

Hi, I don't find i-2 in inference.py. Is the audio window starting from frame i to i+5 ?  
And what's the meaning of the "0-indexing ---> 1-indexing" ?  I don't understand +1 here.
