### ISSUE TITLE
when using inference.py,why does it occur TypeError: guvectorize() missing 1 required positional argument: 'signature'?

### ISSUE THREAD

**Issue by 11whitewater** [Rudrabha/Wav2Lip#454]
when using inference.py,why does it occur TypeError: guvectorize() missing 1 required positional argument: 'signature'?

**Comment by 11whitewater** [comment]
yeah  I solve it

**Comment by prajwalraju** [comment]
hey @11whitewater can you please share how you solved this issue ?

**Comment by prajwalraju** [comment]
Sorry, I don't speak Chinese, but yeah we might have ended up in a similar situation for different reasons.
