### ISSUE TITLE
Local install, returning TypeError

### ISSUE THREAD

**Issue by nononouser** [Rudrabha/Wav2Lip#456]
TypeError: guvectorize() missing 1 required positional argument: 'signature'

Is what I get for the return when attempting to run my command
- python inference.py --checkpoint_path checkpoints/wav2lip_gan.pth --face media/inputvid.mp4 --audio media/inputaud.wav --outfile results/w2l-test1.mp4

I have been following [this](https://github.com/feitgemel/Python-Code-Cool-Stuff/blob/master/Wav2Lip/Wav2Lip-Install-instructions.txt) instruction.

**Comment by nononouser** [comment]
believe I resolved this 
need to install older version of resampy (0.2.2)

https://stackoverflow.com/questions/73918403/why-is-it-showing-guvectorize-missing-1-required-positional-argument-signat

**Comment by Trimad** [comment]
@nononouser Can you post your requirements.txt config? I keep running into issues with a local install.

**Comment by nononouser** [comment]
librosa==0.7.0
numpy==1.17.1
opencv-contrib-python>=4.2.0.34
opencv-python==4.1.2.30
tensorflow==2.2.0
torch==1.1.0
torchvision==0.6.0
tqdm==4.45.0
numba==0.48

Also needed ffmpeg downloaded and exe files in wav2lip folder
