### ISSUE TITLE
Shared notebook fails in last step

### ISSUE THREAD

**Issue by SebaGenetic** [Rudrabha/Wav2Lip#47]
Hello! After processing the video it fails, I tried several videos including one of your own videos (the dictator one).

`/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Using cuda for inference.
Reading video frames...
Number of frames available for inference: 210
(80, 1595)
Length of mel chunks: 594
  0% 0/5 [00:00<?, ?it/s]
  0% 0/14 [00:00<?, ?it/s]THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=383 error=11 : invalid argument
  0% 0/14 [00:00<?, ?it/s]
Recovering from OOM error; New batch size: 8

  0% 0/27 [00:00<?, ?it/s]
  4% 1/27 [00:04<01:56,  4.50s/it]
  7% 2/27 [00:05<01:23,  3.32s/it]
 11% 3/27 [00:05<00:59,  2.50s/it]
 15% 4/27 [00:06<00:44,  1.92s/it]
 19% 5/27 [00:06<00:33,  1.51s/it]
 22% 6/27 [00:07<00:25,  1.23s/it]
 26% 7/27 [00:07<00:20,  1.03s/it]
 30% 8/27 [00:08<00:17,  1.12it/s]
 33% 9/27 [00:09<00:14,  1.22it/s]
 37% 10/27 [00:09<00:12,  1.33it/s]
 41% 11/27 [00:10<00:11,  1.43it/s]
 44% 12/27 [00:10<00:09,  1.51it/s]
 48% 13/27 [00:11<00:08,  1.56it/s]
 52% 14/27 [00:12<00:08,  1.60it/s]
 56% 15/27 [00:12<00:07,  1.62it/s]
 59% 16/27 [00:13<00:06,  1.66it/s]
 63% 17/27 [00:13<00:05,  1.67it/s]
 67% 18/27 [00:14<00:05,  1.69it/s]
 70% 19/27 [00:14<00:04,  1.69it/s]
 74% 20/27 [00:15<00:04,  1.66it/s]
 78% 21/27 [00:16<00:03,  1.65it/s]
 81% 22/27 [00:16<00:03,  1.64it/s]
 85% 23/27 [00:17<00:02,  1.60it/s]
 89% 24/27 [00:18<00:01,  1.61it/s]
 93% 25/27 [00:18<00:01,  1.62it/s]
 96% 26/27 [00:19<00:00,  1.63it/s]
100% 27/27 [00:21<00:00,  1.23it/s]
Load checkpoint from: checkpoints/wav2lip_gan.pth
  0% 0/5 [00:26<?, ?it/s]
Traceback (most recent call last):
  File "inference.py", line 277, in <module>
    main()
  File "inference.py", line 249, in main
    model = load_model(args.checkpoint_path)
  File "inference.py", line 166, in load_model
    checkpoint = _load(path)
  File "inference.py", line 157, in _load
    checkpoint = torch.load(checkpoint_path)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 581, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 2577609 more bytes. The file might be corrupted.
terminate called after throwing an instance of 'c10::Error'
  what():  owning_ptr == NullType::singleton() || owning_ptr->refcount_.load() > 0 ASSERT FAILED at /pytorch/c10/util/intrusive_ptr.h:350, please report a bug to PyTorch. intrusive_ptr: Can only intrusive_ptr::reclaim() owning pointers that were created using intrusive_ptr::release(). (reclaim at /pytorch/c10/util/intrusive_ptr.h:350)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7fb2ddb06441 in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7fb2ddb05d7a in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)
frame #2: THStorage_free + 0xca (0x7fb2deaa029a in /usr/local/lib/python3.6/dist-packages/torch/lib/libcaffe2.so)
frame #3: <unknown function> + 0x53a157 (0x7fb31d20f157 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_python.so)
frame #4: python3() [0x54f226]
frame #5: python3() [0x572cd0]
frame #6: python3() [0x4b18a8]
frame #7: python3() [0x588a98]
frame #8: python3() [0x5ad558]
frame #9: python3() [0x5ad56e]
frame #10: python3() [0x5ad56e]
frame #11: python3() [0x5ad56e]
frame #12: python3() [0x5ad56e]
frame #13: python3() [0x5ad56e]
frame #14: python3() [0x56b636]
<omitting python frames>
frame #20: __libc_start_main + 0xe7 (0x7fb3673dfb97 in /lib/x86_64-linux-gnu/libc.so.6)
`

**Comment by prajwalkr** [comment]
The checkpoint file might be corrupted. Please re-download it and try again.
