### ISSUE TITLE
Increase the resolution

### ISSUE THREAD

**Issue by wangrui5781** [Rudrabha/Wav2Lip#5]
Hi, thank you for sharing this code. The result is pretty amazing.
But I found that when used a high resolution video such as 1920 * 1080 as input, the output video becomes blurred. So can we increse the resolution at the training step?

**Comment by prajwalkr** [comment]
Hi, thank you for checking out the work. Since the model is trained on LRS2 containing low-resolution videos and faces, the model does not work too well with high-res inputs. We would need to train on some other high-res data.
