### ISSUE TITLE
can not install requirements.txt on windows 10

### ISSUE THREAD

**Issue by halpz** [Rudrabha/Wav2Lip#51]
I get this error message

```
Could not find a version that satisfies the requirement torch==1.1.0 (from -r requirements.txt (line 6)) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
No matching distribution found for torch==1.1.0 (from -r requirements.txt (line 6))
```

if I try to install one of the other versions (0.1.2.post2) the script fails later on

**Comment by dipam7** [comment]
What version of Python are you using? It's likely that. You should be using Python 3.5 or 3.6 for this repo.

**Comment by halpz** [comment]
I’m using the recommended 3.5.7 64 bit

**Comment by prajwalkr** [comment]
Try to download the right `.whl` file from the Pytorch site and do `pip install <path_to_whl_file>`

**Comment by halpz** [comment]
the requirements don't work with Python 3.5.2, I needed to use Python 3.6.0 for it to work - maybe you should update the instructions on the page!

thanks!

**Comment by halpz** [comment]
but still doesn't work on Windows, this was mac

**Comment by prajwalkr** [comment]
> the requirements don't work with Python 3.5.2, I needed to use Python 3.6.0 for it to work - maybe you should update the instructions on the page!

done! thanks!

**Comment by prajwalkr** [comment]
> but still doesn't work on Windows, this was mac

can you install anaconda and try the installation once? We have never tested with windows, so we do not know.

**Comment by halpz** [comment]
also on mac os X numba 0.48 requires  > python 3.6.0

**Comment by prajwalkr** [comment]
> but still doesn't work on Windows,

https://www.youtube.com/watch?v=f_NUZDBiaZg

Is there any useful information for you in this video?
