### ISSUE TITLE
I try these code in inferrence.py,but return with error: face_landmarks_detector has not been defined,can you show how to create this object with mediapipe?

### ISSUE THREAD

**Issue by sailorsale** [Rudrabha/Wav2Lip#516]
> It's a bit problematic for me to send the code. However, I can send the modifications. Take them as rough guidelines rather than exact. Read about how to use MediaPipe.
> 
> Install MediaPipe:
> 
> `pip install mediapipe==0.10.0`
> 
> Download face landmarker model and put it in the "weights" folder:
> 
> `wget -O weights/face_landmarker_v2_with_blendshapes.task -q https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task`
> 
> Add MediaPipe imports:
> 
> ```
> from mediapipe.tasks import python
> from mediapipe.tasks.python import vision
> import mediapipe as mp
> ```
> 
> Add face mask args:
> 
> ```
> 	parser.add_argument('--face_landmarks_detector_path', default='weights/face_landmarker_v2_with_blendshapes.task',
> 						type=str, help='Path to face landmarks detector')
> 	parser.add_argument('--with_face_mask', action='store_true',
> 						help='Blend output into original frame using a face mask rather than directly blending the face box. This prevents a lower resolution square artifact around lower face')
> ```
> 
> In main() in the loop starting with "for p, f, c in ..." Modify The line `f[y1:y2, x1:x2] = p` to:
> 
> ```
> 				mask = face_mask_from_image(p, face_landmarks_detector)
> 				f[y1:y2, x1:x2] = f[y1:y2, x1:x2] * (1 - mask[..., None]) + p * mask[..., None]
> 			else:
> 				f[y1:y2, x1:x2] = p
> ```
> 
> Add face_mask_from_image function:
> 
> ```
> def face_mask_from_image(image, face_landmarks_detector):
> 	"""
> 	Calculate face mask from image. This is done by
> 
> 	Args:
> 		image: numpy array of an image
> 		face_landmarks_detector: mediapipa face landmarks detector
> 	Returns:
> 		A uint8 numpy array with the same height and width of the input image, containing a binary mask of the face in the image
> 	"""
> 	# initialize mask
> 	mask = np.zeros((image.shape[0], image.shape[1]), dtype=np.uint8)
> 
> 	# detect face landmarks
> 	mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=image)
> 	detection = face_landmarks_detector.detect(mp_image)
> 
> 	if len(detection.face_landmarks) == 0:
> 		# no face detected - set mask to all of the image
> 		mask[:] = 1
> 		return mask
> 
> 	# extract landmarks coordinates
> 	face_coords = np.array([[lm.x * image.shape[1], lm.y * image.shape[0]] for lm in detection.face_landmarks[0]])
> 
> 	# calculate convex hull from face coordinates
> 	convex_hull = cv2.convexHull(face_coords.astype(np.float32))
> 
> 	# apply convex hull to mask
> 	return cv2.fillPoly(mask, pts=[convex_hull.squeeze().astype(np.int32)], color=1)
> ```

I try these code in inferrence.py,but return with error: face_landmarks_detector has not been defined,can you show how to create this object with mediapipe?

_Originally posted by @liumaokun2022 in https://github.com/Rudrabha/Wav2Lip/issues/415#issuecomment-1594108520_

**Comment by einsqing** [comment]
May I ask how you resolved it?

**Comment by sailorsale** [comment]
> 

I didn't use his method to solve it, because his code has problems, I solved it in other ways, I learned from the training and face model parameters

**Comment by einsqing** [comment]
> > 
> 
> I didn't use his method to solve it, because his code has problems, I solved it in other ways, I learned from the training and face model parameters

Thank you, I know how to solve it, but it's a bit troublesome under win. Testing under ubuntu can be solved using this method

**Comment by sailorsale** [comment]
> > > 
> > 
> > 
> > I didn't use his method to solve it, because his code has problems, I solved it in other ways, I learned from the training and face model parameters
> 
> Thank you, I know how to solve it, but it's a bit troublesome under win. Testing under ubuntu can be solved using this method

Could you please tell me how to solve it in ubuntu?

**Comment by monk-after-90s** [comment]
Refer to https://developers.google.com/mediapipe/solutions/vision/face_landmarker/python#create_the_task

**Comment by m00ali** [comment]
@sailorsale can you share code on how you solved it, i am stuck on it too
