### ISSUE TITLE
Issue with inference.py

### ISSUE THREAD

**Issue by little512** [Rudrabha/Wav2Lip#52]
Using the example command for inference with pretrained models in the README, I get a ModuleNotFoundError, saying: `No module named 'numba.decorators'`, even though I installed all of the requirements via `pip3 install -r requirements.txt` in a virtual environment. Am I doing something wrong? The exact command I'm running looks like this:

`python3 inference.py --checkpoint_path checkpoints --face image.png --audio audio.mp3`

Where image.png and audio.mp3 are the pairs I want to sync.

I have the model (Wav2Lip + GAN) in `checkpoints/` and `face_detection/detection/sfd/s3fd.pth` in it's proper place.

I'm on Linux Mint 19.1, using Python 3.6.9 and Pip 20.2.1

**Comment by little512** [comment]
The issue is with the version of Numba required, as defined in [this issue](https://github.com/librosa/librosa/issues/1160) from librosa. The solution is to install numba==0.48 where `numba.decorators` is still present.

**Comment by prajwalkr** [comment]
Added it in requirements.txt, thanks!
