### ISSUE TITLE
how to resolve vfile.split('/')[-2] ?

### ISSUE THREAD

**Issue by HaSaKiYasuooo** [Rudrabha/Wav2Lip#531]
I don't use the datasets from http://www.robots.ox.ac.uk/~vgg/data/lip_reading/lrs2.html
how to set the directory structure 
![image](https://github.com/Rudrabha/Wav2Lip/assets/87591236/2d6e1e08-96e5-46bf-9154-4a5e1f4b84d2)

**Comment by RainMen1277** [comment]
这是获取上上级目录名称
