### ISSUE TITLE
Training Tutorial

### ISSUE THREAD

**Issue by brunodbrazil** [Rudrabha/Wav2Lip#54]
Where can I find a video tutorial for training a model? Is there a community in which users provide other models trained for use?

**Comment by prajwalkr** [comment]
> Where can I find a video tutorial for training a model?

https://www.youtube.com/results?search_query=wav2lip. There are a few tutorials here. I am not sure if any of them demonstrate training this model. 

> Is there a community in which users provide other models trained for use?

https://modelzoo.co

**Comment by brunodbrazil** [comment]
> > Where can I find a video tutorial for training a model?
> 
> https://www.youtube.com/results?search_query=wav2lip. There are a few tutorials here. I am not sure if any of them demonstrate training this model.
> 
> > Is there a community in which users provide other models trained for use?
> 
> https://modelzoo.co

No one tutorial. I cannot find a model to  Wav2lip on this site
