### ISSUE TITLE
Another form to use Wav2Lip

### ISSUE THREAD

**Issue by diogoalmeida1991** [Rudrabha/Wav2Lip#547]
Why the colab exists? The platform has 80% of change of "is reconnecting", has a lot of problems whether I need do again the proccess when it works in the first time, it has a lot of bug and the system is extreme poor, if considered my resources as cpu, gpu, memory and another configs. Has another form to use wav2lip? 

Common bug:

When you upload own your video:
      video_duration = mp.VideoFileClip(PATH_TO_YOUR_VIDEO).duration -> line 73. Freeze!

Whether you made a terrible mistake of choose upload method and no the custom_path and you need change this option, prepare to pay all of your sins, the result is a freeze! Restart the project!

Another bug is when is finishing the lip with wav:
mp4 = open(file_path,'rb').read() 
FileNotFoundError: [Errno 2] No such file or directory: '/content/Wav2Lip/results/result_voice.mp4' in line 19.

**Comment by HassanMuhammadSannaullah** [comment]
Don't know if it will be helpful for you in your case but I have created a repository that fixes the running for inference using the pretrained model. here is the link https://github.com/HassanMuhammadSannaullah/Wav2lip-Fix-For-Inference. You can directly perform inference in python code instead of using cli

**Comment by justinjohn0306** [comment]
> Why the colab exists? The platform has 80% of change of "is reconnecting", has a lot of problems whether I need do again the proccess when it works in the first time, it has a lot of bug and the system is extreme poor, if considered my resources as cpu, gpu, memory and another configs. Has another form to use wav2lip?
> 
> Common bug:
> 
> When you upload own your video: video_duration = mp.VideoFileClip(PATH_TO_YOUR_VIDEO).duration -> line 73. Freeze!
> 
> Whether you made a terrible mistake of choose upload method and no the custom_path and you need change this option, prepare to pay all of your sins, the result is a freeze! Restart the project!
> 
> Another bug is when is finishing the lip with wav: mp4 = open(file_path,'rb').read() FileNotFoundError: [Errno 2] No such file or directory: '/content/Wav2Lip/results/result_voice.mp4' in line 19.

this issue has been fixed, try again :)

**Comment by diogoalmeida1991** [comment]
Thanx!
