### ISSUE TITLE
How many steps does the expert discriminator take to converge?

### ISSUE THREAD

**Issue by desmondchchan** [Rudrabha/Wav2Lip#56]
How many steps does the expert discriminator take to converge? The loss stuck at 0.69 for quite a while.

**Comment by prajwalkr** [comment]
What dataset are you training on?

**Comment by desmondchchan** [comment]
I am using voxceleb2. I am going to try with LRS2 in a bit. How many steps did it take using LRS2? I have a hard time understanding how the SyncNet works. It seems like the network is having a hard time classifying in sync and out of sync and the cosine distance converges to 0.5

**Comment by prajwalkr** [comment]
On LRS2, it'll easily take around 700k+ steps to converge. For a long time, you will see it not converging and suddenly it starts to converge. We are trying to figure out the reason as well.

**Comment by desmondchchan** [comment]
700k steps is a lot, it will take days! Does it take 700k steps to start to converge or finish converging?

**Comment by prajwalkr** [comment]
Finish converging.

**Comment by K0923** [comment]
I thought this is merely a binary classification task, why is so hard to converge?

**Comment by prajwalkr** [comment]
We are not entirely sure of this either, but, it is far from being a easy binary classification task.

**Comment by mushanshanshan** [comment]
@desmondchchan  Hi, I also want to train this model on voxceleb2, did you succeed in the end?

**Comment by Nyquist0** [comment]
I am working on VoxCeleb2 within 20k training samples. It still does not converge after 90k steps.
