### ISSUE TITLE
Can't install requirements

### ISSUE THREAD

**Issue by billythegoat356** [Rudrabha/Wav2Lip#574]
ERROR: Could not find a version that satisfies the requirement torch==1.8.0 (from versions: none)
ERROR: No matching distribution found for torch==1.8.0

**Comment by sahreen-haider** [comment]
> ERROR: Could not find a version that satisfies the requirement torch==1.8.0 (from versions: none)
> ERROR: No matching distribution found for torch==1.8.0

hey, I used the latest torch version, it hasn't raised any error for me.
I guess they have removed the support for 1.8.0, since they have only listed the torch version 1.11.0 and above
or another possible solution could be lower your python version to older versions.

**Comment by billythegoat356** [comment]
hello thank you it works for me!

**Comment by Jumao-OC** [comment]
It should now support 1.8.0
