### ISSUE TITLE
Mouth position dislocated or some weird artefact's.

### ISSUE THREAD

**Issue by sahreen-haider** [Rudrabha/Wav2Lip#580]
### **The model is pretty great but, when getting the results, I'm getting distorted mouth in the resultant video output.**

I've already tried guided instructions from the documentation.
like the ones below.

- Experiment with the --pads argument to adjust the detected face bounding box. Often leads to improved results. You might need to increase the bottom padding to include the chin region. E.g. --pads 0 20 0 0.

- If you see the mouth position dislocated or some weird artifacts such as two mouths, then it can be because of over-smoothing the face detections. Use the --nosmooth argument and give it another try.

**Comment by Peter-SungwooCho** [comment]
Did you solve the problem? I have same problem with you.
