### ISSUE TITLE
invalid load key, '-'

### ISSUE THREAD

**Issue by 2secslater** [Rudrabha/Wav2Lip#59]
I've tried to run wav2lip on example assets, and no matter what face/audio I use, I always get the same end result: https://bin.snopyta.org/?18f73b4767f722db#8Btn7ebqChWJaKJyx5sBNuy9WsjpYP3TnfxfHJ7UNcLz

`python3.6 inference.py --checkpoint_path checkpoints --face bazigar_part1.mp4 --audio bazigar_part1.wav` is the command I ran, with the assets from the website linked on this repository. Also, I'm just using the wav2lip model which is also linked on the repository's readme.

**Comment by prajwalkr** [comment]
Can you check:

- [ ] Your PyTorch version
- [ ] If your checkpoint file is correct. Please re-download once and check.

**Comment by 2secslater** [comment]
The version of PyTorch installed is 1.1.0.
I have tried to redownload the checkpoint file, but I still get the same error.

**Comment by prajwalkr** [comment]
You are trying to load a PyTorch model checkpoint. Try to load it outside of this project, i.e., in a different environment that you often use to run PyTorch codes. See if you get an error there as well. 

A quick Google search tells that the checkpoint file is corrupted or the checkpoint file specified is wrong. I do not know any other reason why you might get this error. Please check if you have the right Python version as well.
