### ISSUE TITLE
Preprocessing cannot be completed with preprocess.py

### ISSUE THREAD

**Issue by kzxuan** [Rudrabha/Wav2Lip#6]
Sorry for bothering again.
But when I use preprocess.py to process LSR2 dataset (or my own videos), I only get a lot of white-black square images with size 1x4 (as *.jpg in the preprocessed_root).
I couldn't figure out what went wrong, and I want to know what a *.jpg should look like.
Thank you for your attention.

**Comment by prajwalkr** [comment]
Please paste your folder structure of the LRS2 dataset here (similar to how it is mentioned in the README). And also please paste the exact command you have run.

**Comment by kzxuan** [comment]
**The data_root folder structure:**
```
filelists
└── main
    └── mydata
        └── 00001.mp4
        └── 00002.mp4
        └── 00003.mp4
```
**I use the following command:**
```
python3 preprocess.py --data_root ./filelists/main --preprocessed_root ./temp
```
The program can find all the mp4 files and create the corresponding folders under ./temp. But the preprocessed *.jpg is not correct. For LipGAN project, all the *.jpg files will be a face picture of each frame of the mp4 file.

Thank you so much.

**Comment by kzxuan** [comment]
For more information, in line 63 of preprocess.py, the face range information of each frame in a batch can be correctly obtained, including the coordinates of the upper left corner and the lower right corner.
I think the code of line 70 is not work correctly:
```
cv2.imwrite(path.join(fulldir, '{}.jpg'.format(i)), f[0])
```

**Comment by prajwalkr** [comment]
Please pull the latest version and check and let us know if the issue persists.

**Comment by kzxuan** [comment]
Thanks for your help, the code is working efficiently.
