### ISSUE TITLE
preprocess error

### ISSUE THREAD

**Issue by 397688551** [Rudrabha/Wav2Lip#609]
preprocess error:
1、RuntimeError: CUDA error: an illegal memory access was encountered
2、ntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
3、RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/THCGeneral.cpp:383

and the preprocessed folder contains only wav audio files and no jpg files

**Comment by Salmanshams67** [comment]
I needed a version of PyTorch that supports CUDA 11.1 or higher to use the A100 GPU. The latest versions of PyTorch support this, so one should install the correct version.

Run the following commands to update PyTorch and ensure you have the appropriate CUDA version:

1. Uninstall the current PyTorch version:
`pip uninstall torch torchvision`

2. Install the latest version of PyTorch with CUDA 11.1 support: (according to my requirement) 
`pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu111`

This command ensures that you install PyTorch with CUDA 11.1 support, which is compatible with the A100 GPU.

**Comment by MDSALMANSHAMS** [comment]
I needed a version of PyTorch that supports CUDA 11.1 or higher to use the A100 GPU. The latest versions of PyTorch support this, so one should install the correct version.

Run the following commands to update PyTorch and ensure you have the appropriate CUDA version:

1. Uninstall the current PyTorch version:
`pip uninstall torch torchvision`

2. Install the latest version of PyTorch with CUDA 11.1 support: (according to my requirement) 
`pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu111`

This command ensures that you install PyTorch with CUDA 11.1 support, which is compatible with the A100 GPU.
