### ISSUE TITLE
经过gfpgan处理,中文数据集,脸部有抖动 | After processing with gfpgan, the Chinese dataset shows facial tremors

### ISSUE THREAD

**Issue by angel-yi** [Rudrabha/Wav2Lip#620]
脸部有抖动如何能够消除呢
How can facial tremors be eliminated

https://github.com/Rudrabha/Wav2Lip/assets/51775756/359044f2-6e96-42e7-9b4c-0951b85edb35

https://github.com/Rudrabha/Wav2Lip/assets/51775756/9cbf13c3-3a80-47d4-b3c8-37d1439d27c0

**Comment by fjesikfjdskl** [comment]
你好请问是CMLR视频数据训练的吗
