### ISSUE TITLE
Why is my loss always 0

### ISSUE THREAD

**Issue by ZhuWenxuan123code** [Rudrabha/Wav2Lip#624]
![屏幕截图 2024-02-01 175804](https://github.com/Rudrabha/Wav2Lip/assets/127590639/bcb31de0-143b-4f49-9931-7989136eafdf)

**Comment by ZhuWenxuan123code** [comment]
![txt](https://github.com/Rudrabha/Wav2Lip/assets/127590639/b850ebba-c98f-4ad8-b623-3844a35b3407)
is this the right format?

**Comment by fuxuelinwudi** [comment]
hyparams 里有个 weight 的设置，一开始 sync 的 loss weight = 0.0， 它是让训练到达一定步数的时候变大一点，到 0.03 这样。你可以看下训练的代码逻辑进行更改。

**Comment by ZhuWenxuan123code** [comment]
谢谢你
