### ISSUE TITLE
https://bhaasha.iiit.ac.in/lipsync/

### ISSUE THREAD

**Issue by molo32** [Rudrabha/Wav2Lip#63]
https://bhaasha.iiit.ac.in/lipsync/ 
not show videos
I can not see the videos
goes black

**Comment by prajwalkr** [comment]
Ensure your filename does not have spaces, and faces are present in all frames. If not, you will not get a result.

**Comment by molo32** [comment]
that is, the video player does not load, it does nothing, it is only gray

**Comment by prajwalkr** [comment]
download the sample video/audios given in the site and feed those as input. You can see that the video player works. The reason it is not giving a result is because of the reasons I have mentioned above.
