### ISSUE TITLE
Wav2Lip 报错TypeError: mel() takes 0 positional arguments but 2 positional arguments (and 3 keyword-only arguments) were given

### ISSUE THREAD

**Issue by TzyTman** [Rudrabha/Wav2Lip#634]
我在运行：

python inference.py --checkpoint_path /home/mk/Wav2Lip-master/input_model/wav2lip_gan.pth --face /home/mk/Wav2Lip-master/input_video/xiaobao.mp4 --audio /home/mk/Wav2Lip-master/input_audio/xiaobao.MP3

报错：
Using cuda for inference.
Reading video frames...
Number of frames available for inference: 223
Extracting raw audio...
ffmpeg version 4.2.7-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[mp3 @ 0x55a65e362800] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from '/home/mk/Wav2Lip-master/input_audio/xiaobao.MP3':
  Metadata:
    encoder         : LAME3.101 (beta 2)
  Duration: 00:00:13.51, start: 0.000000, bitrate: 128 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 128 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (mp3 (mp3float) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, wav, to 'temp/temp.wav':
  Metadata:
    ISFT            : Lavf58.29.100
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, stereo, s16, 1411 kb/s
    Metadata:
      encoder         : Lavc58.54.100 pcm_s16le
size=    2327kB time=00:00:13.50 bitrate=1411.2kbits/s speed= 485x    
video:0kB audio:2326kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.003274%
Traceback (most recent call last):
  File "/home/mk/Wav2Lip-master/inference.py", line 280, in <module>
    main()
  File "/home/mk/Wav2Lip-master/inference.py", line 225, in main
    mel = audio.melspectrogram(wav)
  File "/home/mk/Wav2Lip-master/audio.py", line 47, in melspectrogram
    S = _amp_to_db(_linear_to_mel(np.abs(D))) - hp.ref_level_db
  File "/home/mk/Wav2Lip-master/audio.py", line 95, in _linear_to_mel
    _mel_basis = _build_mel_basis()
  File "/home/mk/Wav2Lip-master/audio.py", line 100, in _build_mel_basis
    return librosa.filters.mel(hp.sample_rate, hp.n_fft, n_mels=hp.num_mels,
TypeError: mel() takes 0 positional arguments but 2 positional arguments (and 3 keyword-only arguments) were given

谷歌搜索了一些答案但是无法解决！

这是我requirements.txt 依赖库的版本如下：
librosa==0.10.0
numpy==1.24.3
opencv-contrib-python>=4.2.0.34
opencv-python>=4.7.0.72
torch==1.11.0
torchvision==0.12.0
tqdm==4.45.0
numba==0.59.0

麻烦各位大神帮忙了！

**Comment by TzyTman** [comment]
系统信息:Ubuntu 20.04.5 LTS (GNU/Linux 5.4.0-170-generic x86_64)

**Comment by dwanggit** [comment]
应该是librosa版本的问题，但是老版本的装不上，我也在苦恼怎么解决这个问题

**Comment by TzyTman** [comment]
这个问题我已经解决了。明天发你解决办法。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: dwanggit ***@***.***&gt;
发送时间: 2024年2月22日 20:22
收件人: Rudrabha/Wav2Lip ***@***.***&gt;
抄送: tuzhengyao ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Rudrabha/Wav2Lip] Wav2Lip 报错TypeError: mel() takes 0 positional arguments but 2 positional arguments (and 3 keyword-only arguments) were given (Issue #634)





 
应该是librosa版本的问题，但是老版本的装不上，我也在苦恼怎么解决这个问题

**Comment by TzyTman** [comment]
> 应该是librosa版本的问题，但是老版本的安装上不上，我一直很苦恼怎么解决这个问题
修复此问题不走：
1. 修改依赖版本号：
librosa==0.10.1
numpy==1.24.3
opencv-contrib-python>=4.2.0.34
opencv-python>=4.7.0.72
torch==1.11.0
torchvision==0.12.0
tqdm==4.45.0
numba==0.59.0
2. 修改audio.py 第一百行代码：
return librosa.filters.mel(sr=hp.sample_rate, n_fft=hp.n_fft, n_mels=hp.num_mels,
                               fmin=hp.fmin, fmax=hp.fmax)   
调整参数 在运行 就没问题了。

**Comment by TzyTman** [comment]
已修复

**Comment by dwanggit** [comment]
感谢，我试一下，我也想过把function改成新版本的格式。就是怕后面还有其他要改的，就说先尝试下弄版本行不行

**Comment by hanhan-20240326** [comment]
已经搞定，感谢
