### ISSUE TITLE
Face Detection / Mouth Placement - is not accurate

### ISSUE THREAD

**Issue by AlonDan** [Rudrabha/Wav2Lip#64]
## ISSUE:
I did some tests, and I noticed if the FACE on the video is 90 degrees or -20 +20 the Mouth placed on the correct spot.

But if the face is more horizontal / rotation than 90 degrees, the face still detected but the Mouth Placement at the final result video is not on the correct place, it is moving with the face (means it detected the face movement) but the mouth could be next to the head somewhere,  it's **NOT** related to the ```--pads``` or to the ```--nosmooth``` because with with or without these, the mouth can't be placed on the BEST location related to the face if **the face on the video isn't close to 90 degrees**.

I'm not sure if it's related to the detection part of the face, or to the placement based on the detection since I'm not a programmer, but it could be improved if the faces won't have to be close to 90 degrees but also on other angels.
##

## Reproduce Issue:
**1**. Try it on ANY short video (5 seconds will be enough for quick test), and rotate the video so the MOUTH is around 90 degrees (you can do that on any editing video or after effects.
You will see that the results will be pretty accurate.
**2**. Try the SAME video but now rotate it so the FACE is more horizontal, the results will be very weird... mouth will not appear on the face but next to the head somewhere.
**3**. Try a DIFFERENT VIDEO this time, but one that the HEAD is not 90 degrees but more horizontal rotation (for example if a head is turning on the video or it's already rotated. the results will be like #2 = not good...

##

I believe that it's somehow related to the detection but I'm not sure, you sure know better than I do.
I hope this could be fixed or improved, thanks ahead and keep up the good work!

**Comment by prajwalkr** [comment]
Hello, we are aware of the issue, and a possible fix as well. We are working on it and will update the repo once that is done :+1:
