### ISSUE TITLE
video clips length

### ISSUE THREAD

**Issue by hnsywangxin** [Rudrabha/Wav2Lip#659]
Do the video clips have to be less than 5 seconds? Can I cut them with the lengths in 4-7 seconds？
thanks

**Comment by xpdd123** [comment]
yes

**Comment by xpdd123** [comment]
> Do the video clips have to be less than 5 seconds? Can I cut them with the lengths in 4-7 seconds？ thanks

you can cut them with the lengths in 4-7 seconds

**Comment by hnsywangxin** [comment]
> > Do the video clips have to be less than 5 seconds? Can I cut them with the lengths in 4-7 seconds？ thanks
> 
> you can cut them with the lengths in 4-7 seconds

thank you !
