### ISSUE TITLE
Cannot access files in Colab

### ISSUE THREAD

**Issue by htshnr** [Rudrabha/Wav2Lip#67]
Hey, great paper. Just wanted to let you know that in the Colab you've mounted your own Drive, and therefore this line
`!cp -ri "/content/gdrive/My Drive/Wav2lip/wav2lip_gan.pth" /content/Wav2Lip/checkpoints/` doesn't work for anybody else as we don't have such a path in our own drives.

I saw that you've provided links to the .pth files as well but they're hosted on SharePoint and you can't directly wget them into Colab due to a 403 error.

An easy way to fix this would be to enable sharing on the Wav2Lip folder in your own Drive and share the link with us, so that we may copy the files into our own drive and hence access them inside Colab.

Amazing work, btw!

**Comment by prajwalkr** [comment]
> An easy way to fix this would be to enable sharing on the Wav2Lip folder in your own Drive and share the link with us, so that we may copy the files into our own drive and hence access them inside Colab

Done.
