### ISSUE TITLE
Idle/Pauses

### ISSUE THREAD

**Issue by Crazyjoedevola** [Rudrabha/Wav2Lip#69]
Hi
Would it be possible to add an idle expression for silent portions (where there is no audio). I would like to point to a neutral expression which is used during no sound.

**Comment by prajwalkr** [comment]
Closing the lips convincingly and having a neutral expression during silences is still not fully solved. We will update the repo once we have a solution.

**Comment by dizhenx** [comment]
> Closing the lips convincingly and having a neutral expression during silences is still not fully solved. We will update the repo once we have a solution.

Is there a solution now?
