### ISSUE TITLE
Training on videos with different fps

### ISSUE THREAD

**Issue by dheerajmpai** [Rudrabha/Wav2Lip#70]
I am planning to train on voxceleb2 dataset which has videos collected from youtube. The FPS for each video is different. Can you please tell me when changes do I need to make to incorporate this. Where does the FPS actually matter? In the preprocessing step or in the training (or both)?

My thoughts were either 

1. to make the changes in the code tp detect the framerate for each video and incorporate the changes in the code
OR  
2. to convert all the videos to fps 25 using ffmpeg. 

 Is there any other way to incorporate this?

**Comment by prajwalkr** [comment]
> The FPS for each video is different.

"We provide URLs for each YouTube video and timestamps for utterances. The frame number provided assumes that the video is saved at 25fps." - Written in vox2 website

**Comment by dheerajmpai** [comment]
Thanks, @prajwalkr .
