### ISSUE TITLE
Teeth look fuzzy

### ISSUE THREAD

**Issue by QUTGXX** [Rudrabha/Wav2Lip#71]
Hi, we trained the model with our own datasets followed by your requirements "Training on datasets other than LRS2". And we have some issues with that the following screenshot shows the results. The teeth look not visible, can u give us more suggestions?
![image](https://user-images.githubusercontent.com/36947214/93840519-43878a80-fcc3-11ea-8519-d7bdd418aa66.png)

**Comment by Augnine** [comment]
I have the same probelm.

**Comment by prajwalkr** [comment]
Are you using the Wav2Lip + GAN model?

**Comment by QUTGXX** [comment]
> Are you using the Wav2Lip + GAN model?

Not yet, we just try the wav2lip model.

**Comment by prajwalkr** [comment]
Please try that and re-open the issue if you are facing the same problem.

**Comment by QUTGXX** [comment]
> Please try that and re-open the issue if you are facing the same problem.

Got it,  thanks for your reply.

**Comment by QUTGXX** [comment]
> Please try that and re-open the issue if you are facing the same problem.

@prajwalkr 
We have tried the wav2lip+gan model, but the result seems not good.
![image](https://user-images.githubusercontent.com/36947214/93954247-cbcb6580-fd7f-11ea-9e08-ba7f75305988.png)
And the training parameter is the same as you provided. The loss may have some issues. Could u plz give us more suggestions?
![image](https://user-images.githubusercontent.com/36947214/93954333-07662f80-fd80-11ea-927d-8eebc4e09560.png)

**Comment by prajwalkr** [comment]
Such a low sync loss and L1 loss is probably not good. How big is your dataset? Also, the GAN seems to have failed in your case, the real and perceptual losses are zero. We would be unable to help you much with training on your own custom datasets, as there are a lot of moving variables. Our suggestions are derived from our training experience on LRS2.

**Comment by QUTGXX** [comment]
> Such a low sync loss and L1 loss is probably not good. How big is your dataset? Also, the GAN seems to have failed in your case, the real and perceptual losses are zero. We would be unable to help you much with training on your own custom datasets, as there are a lot of moving variables. Our suggestions are derived from our training experience on LRS2.

Thanks for your reply. Can u tell us how these losses would converge about the range as a guiding?

**Comment by prajwalkr** [comment]
> Can u tell us how these losses would converge about the range as a guiding?

Last point of [this section](https://github.com/Rudrabha/Wav2Lip#training-on-datasets-other-than-lrs2) in the readme.

**Comment by QUTGXX** [comment]
> > Can u tell us how these losses would converge about the range as a guiding?
> 
> Last point of [this section](https://github.com/Rudrabha/Wav2Lip#training-on-datasets-other-than-lrs2) in the readme.

Got it, but it did not show any losses about the hq_wav2lip model. This model has five losses. Can u tell us more details about that?

**Comment by QUTGXX** [comment]
@prajwalkr Sorry again for troubling you.  We need your help.

**Comment by DogeFlow** [comment]
Had the same problem, did you finally solve it?

**Comment by dizhenx** [comment]
Had the same problem, did you finally solve it?

> @prajwalkr Sorry again for troubling you. We need your help.
Had the same problem, did you finally solve it?
