### ISSUE TITLE
Just curious about resolution

### ISSUE THREAD

**Issue by kilerb** [Rudrabha/Wav2Lip#72]
Hi!  I know you replied to my previous question regarding resolution.  If you have a minute, just had a couple more questions?  Is there a reason the res is only 96?  And secondly, if someone had enough resources and time, could they train a higher resolution model?  I think you said you were working on something like this, but was just curious about that.  Thanks a lot!  Love the software :)

**Comment by prajwalkr** [comment]
> Is there a reason the res is only 96?

LRS2 dataset is low-res, so we could only get faces around that size. 

> And secondly, if someone had enough resources and time, could they train a higher resolution model?

Yes, definitely, why not.
