### ISSUE TITLE
First image on the Main Page is broken

### ISSUE THREAD

**Issue by AlonDan** [Rudrabha/Wav2Lip#73]
Just like the title say: the first image is broken.
I refreshed and also tried other browser just in case.

I thought to mention it in case it helps.
Keep up the good work 👍 

##
![chrome_2020-09-22_09-55-47](https://user-images.githubusercontent.com/21152334/93851994-dc190d00-fcb9-11ea-8fa1-929a5c67ccd3.png)

**Comment by prajwalkr** [comment]
Hello, the GIF is of a large size. So, it can happen sometimes. But the link of the GIF is valid.
