### ISSUE TITLE
Why do you want to delete this line of code?

### ISSUE THREAD

**Issue by ZerRui** [Rudrabha/Wav2Lip#77]
In the color_syncnet_train.py file, you deleted a line of code that can be processed by multiple GPUs. Did you test the multiple GPUs with errors?

model = nn.DataParallel(model_single)

Looking forward to your reply！

**Comment by prajwalkr** [comment]
The data-parallel line was not used during the paper submission time. We felt that it is apt to provide the closest version of the code that was used for the paper.
