### ISSUE TITLE
Hello, what should I use to determine the number of eval steps?

### ISSUE THREAD

**Issue by ZerRui** [Rudrabha/Wav2Lip#79]
Hello, what should I use to determine the number of eval steps?
In your code, eval=700. What is the basis for determining it? How much should you write if you use your own data for training? Is it a percentage of the total data?
Looking forward to your reply!

**Comment by prajwalkr** [comment]
`eval=700` leads to about 2-3 segments evaluated from each validation video. It's just to get a decent estimate of the validation loss, we did not think too much before setting it to 700.
