### ISSUE TITLE
how use --box option?

### ISSUE THREAD

**Issue by molo32** [Rudrabha/Wav2Lip#80]
according to interference.py - -box option takes 1 argument but a rectangle has Syntax: (top, bottom, left, right). ')

How does a single argument represent (top, bottom, left, right)?
how to put (top, bottom, left, right) individually?

**Comment by prajwalkr** [comment]
See the first point of [this](https://github.com/Rudrabha/Wav2Lip#tips-for-better-results), where we show how to use `--pads`. `--box` is also the same way.
