### ISSUE TITLE
I've tried everything.

### ISSUE THREAD

**Issue by sitedude1337** [Rudrabha/Wav2Lip#82]
Fresh install of Ubuntu. Comes with 2.7 python and 3.8.2 

Seems like TensorFlow needs to be updated. I tried their upgrade script but still get 

File "/home/sitedude/Downloads/Wav2hax/audio.py", line 7, in <module>
    from hparams import hparams as hp
  File "/home/sitedude/Downloads/Wav2hax/hparams.py", line 1, in <module>
    from tensorflow.contrib.training import HParams
ModuleNotFoundError: No module named 'tensorflow.contrib'

Would you be able to fix those two files in the repo?

**Comment by prajwalkr** [comment]
Please follow the installation steps and install the correct versions mentioned in the readme.

**Comment by sitedude1337** [comment]
Tried on those versions of python but the problem is that the older version of TF doesn't exist on any repos. Is there any way you could convert the code to tf2? They have an upgrade script but it's throwing an error on the contrib line

**Comment by mowshon** [comment]
First of all, you need to change the **tensorflow** version to 1.13.1 in **requirements.txt** file.

Change
```
tensorflow==1.12.0
```
to
```
tensorflow==1.13.1
```
Install via `pip` like this:
```
pip install -r requirements.txt
```

**Comment by sitedude1337** [comment]
Okay sweet, i think i got all the requirements met now.

I tried python3 inference.py --checkpoint_path checkpoints/wav2lip.pth --face Videos/joe.jpg --audio Audio/b.mp3

It gives a message that says

FileNotFound No such file or directory 'temp/temp.wav'

Any ideas on this?

**Comment by prajwalkr** [comment]
> Any ideas on this?

This means that FFMPEG on this line: https://github.com/Rudrabha/Wav2Lip/blob/07b5fae35121c9c5e9308c06c48da5d8fe5fd44b/inference.py#L222

had an error while executing. Make sure you have FFmpeg installed.

**Comment by sitedude1337** [comment]
absolutely amazing. thanks for all you do. I can't believe after pipping so much i forgot ffmpeg, doh.

if anyone has problems the code works sound under Ubuntu 18 not sure why i couldn't get it to work on 20.

Awesome app too, thanks guys

**Comment by echosvile** [comment]
please i have the same issue but i am using anaconda. i have installed everything including the ffmpeg still having this error

2020-09-27 05:53:55.290406: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-09-27 05:53:55.299248: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "inference.py", line 3, in <module>
    import scipy, cv2, os, sys, argparse, audio
  File "C:\Users\user\OneDrive\Documents\WAV\Wav2Lip\audio.py", line 7, in <module>
    from hparams import hparams as hp
  File "C:\Users\user\OneDrive\Documents\WAV\Wav2Lip\hparams.py", line 1, in <module>
    from tensorflow.contrib.training import HParams
ModuleNotFoundError: No module named 'tensorflow.contrib'

**Comment by prajwalkr** [comment]
Please try this: https://github.com/Rudrabha/Wav2Lip/issues/82#issuecomment-698932704

**Comment by echosvile** [comment]
i have and it's still the same

(WAV2LIP) C:\Users\user\OneDrive\Documents\WAV\Wav2Lip>python inference.py --checkpoint_path checkpoints/wav2lip.pth --face video/result.mp4 --audio audio/sound.wav
2020-09-27 07:10:15.438432: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2020-09-27 07:10:15.448024: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "inference.py", line 3, in <module>
    import scipy, cv2, os, sys, argparse, audio
  File "C:\Users\user\OneDrive\Documents\WAV\Wav2Lip\audio.py", line 7, in <module>
    from hparams import hparams as hp
  File "C:\Users\user\OneDrive\Documents\WAV\Wav2Lip\hparams.py", line 1, in <module>
    from tensorflow.contrib.training import HParams
ModuleNotFoundError: No module named 'tensorflow.contrib'

**Comment by echosvile** [comment]
one thing i noticed was that during the pipping of the requirements, it gave this error
![wav error 1](https://user-images.githubusercontent.com/71806009/94357518-6209cf00-0091-11eb-91c4-8a7721d0a206.PNG)

**Comment by mowshon** [comment]
@echosvile in requirements.txt file change this like
```
torch==1.1.0
```
to
```
torch==1.1.2
```

**Comment by echosvile** [comment]
same thing
![Uploading wav error 2.PNG…]()

**Comment by echosvile** [comment]
![wav error 2](https://user-images.githubusercontent.com/71806009/94365152-73210300-00c6-11eb-8375-10c76714d41a.PNG)
> @echosvile in requirements.txt file change this like
> 
> ```
> torch==1.1.0
> ```
> 
> to
> 
> ```
> torch==1.1.2
> ```

**Comment by leijue222** [comment]
Use Python 3.6 will be OK under Ubuntu 18.04

**Comment by prajwalkr** [comment]
> one thing i noticed was that during the pipping of the requirements, it gave this error
> ![wav error 1](https://user-images.githubusercontent.com/71806009/94357518-6209cf00-0091-11eb-91c4-8a7721d0a206.PNG)

make sure you are using 64-bit Python.
