### ISSUE TITLE
Regarding the problem that the face crop of the training data set does not include the chin？

### ISSUE THREAD

**Issue by ZerRui** [Rudrabha/Wav2Lip#83]
Hello, thank you very much for your project!
When I generated the training data set, I used the face detection in your project and found that many cropped faces did not contain a chin. Will this affect the effect of chin generation? Looking forward to your reply!

**Comment by prajwalkr** [comment]
> When I generated the training data set, I used the face detection in your project and found that many cropped faces did not contain a chin. Will this affect the effect of chin generation?

Yes, it can. Probably, you can add some padding to the boxes while preprocessing the training data. There is no option in the current code to do that, but you should be able to modify it.
