### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement torch==1.1.0 (from -r requirements.txt (line 6)) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)

### ISSUE THREAD

**Issue by echosvile** [Rudrabha/Wav2Lip#85]
i have installed ffmepg, changed the version of the torch in requirements to 1.1.2 and its all still giving me the same 'could not find a version that satisfies the requirements torch==1.1.0'

![wav error 3](https://user-images.githubusercontent.com/71806009/94369822-eedd7880-00e3-11eb-9643-c027b9d9f30d.PNG)
'

**Comment by prajwalkr** [comment]
https://stackoverflow.com/a/57565285

Does this help?

**Comment by echosvile** [comment]
yes thank you. like one stage of everlasting problem passed.
i had to
`torch==1.5.0 -f https://download.pytorch.org/whl/torch_stable.html`
then changed the torch in the requirements from torch==1.1.0 to 1.5.0 and then it loaded and brought this
![wav error 4](https://user-images.githubusercontent.com/71806009/94383499-2544e300-0138-11eb-9ece-4b9a509b3b26.PNG)

**Comment by prajwalkr** [comment]
I think you should be able to run the code irrespective of those errors

**Comment by echosvile** [comment]
ok. i ran the code irrespective of the errors and i guess its running but its showing me this which i guess might be from the path
i save the audio which is mp3 for the syncing in a folder named audio inside the Wav2lip file and the video its meant to sync named result which is mp4 inside a folder named video and this is the code i ran
`python inference.py --checkpoint_path checkpoints/wav2lip.pth --face "../video/result.mp4" --audio "../audio/sound.mp3"
and this is what i get 
![wav error 6](https://user-images.githubusercontent.com/71806009/94385512-4bb94d00-013d-11eb-8371-f2c55a5bdf8a.PNG)

**Comment by echosvile** [comment]
and i already have installed 
`pip install ffmpeg`

**Comment by prajwalkr** [comment]
> and i already have installed
> `pip install ffmpeg`
this is not the right way to install ffmpeg. Please check how to install it on Windows.

**Comment by echosvile** [comment]
i ran these codes respectively
`conda install -c conda-forge ffmpeg'
'conda install -c conda-forge/label/gcc7 ffmpeg'
'conda install -c conda-forge/label/cf201901 ffmpeg'
'conda install -c conda-forge/label/cf202003 ffmpeg`

**Comment by echosvile** [comment]
is this error now from me again?
![wav error 7](https://user-images.githubusercontent.com/71806009/94389798-b4f28d80-0148-11eb-9919-dd78d9d46f26.PNG)

**Comment by prajwalkr** [comment]
> is this error now from me again?

Yes. Please follow the steps in the pre-requisites section of the README.

**Comment by echosvile** [comment]
finally it works.... i had to go to the file directory face_detection, detection, sfd and i renamed the s3fd.pth from s3fd-6789.pth to s3fd.pth and it ran to an extent  and it stopped 
![wav error 8](https://user-images.githubusercontent.com/71806009/94390264-19621c80-014a-11eb-82ef-48794e2c7a0f.PNG)
as shown in the attachment

**Comment by prajwalkr** [comment]
Your GPU memory is too less. Reduce the batch sizes of face detection and wav2lip. There are arguments to control that.

**Comment by echosvile** [comment]
please i beg you direct me, i don't understand this part

**Comment by prajwalkr** [comment]
Along with the other arguments you have used such as `--face` etc., please add `--face_det_batch_size 2` and `--wav2lip_batch_size 8`.

**Comment by echosvile** [comment]
i.e python inference.py --checkpoint_path checkpoints/wav2lip.pth --face_det_batch_size 2 --wav2lip_batch_size 8"../video/result.mp4" --audio "../audio/sound.mp3"

**Comment by echosvile** [comment]
that didnt run please can you help me with the arrangement i don't know where to place the '--wav2lip_batch_size 8'

**Comment by prajwalkr** [comment]
> 8"../

add a space here between your arguments.

**Comment by echosvile** [comment]
python inference.py --checkpoint_path checkpoints/wav2lip.pth --face_det_batch_size 2  --wav2lip_batch_size 8 "../video/result.mp4" --audio "../audio/sound.mp3"
![wav error 9](https://user-images.githubusercontent.com/71806009/94392023-0bfb6100-014f-11eb-8d60-49cf9a40992c.PNG)

**Comment by prajwalkr** [comment]
`python inference.py --checkpoint_path checkpoints/wav2lip.pth --face_det_batch_size 2 --wav2lip_batch_size 8 "../video/result.mp4" --audio "../audio/sound.mp3"`

**Comment by echosvile** [comment]
showed me the same thing
![Uploading wav error 9.PNG…]()

**Comment by echosvile** [comment]
![wav error 9](https://user-images.githubusercontent.com/71806009/94392447-326dcc00-0150-11eb-898b-807ead336799.PNG)

**Comment by Rudrabha** [comment]
``` python inference.py --checkpoint_path checkpoints/wav2lip.pth --face_det_batch_size 2 --wav2lip_batch_size 8 --face "../video/result.mp4" --audio "../audio/sound.mp3"```
Please try this once

**Comment by echosvile** [comment]
`python inference.py --checkpoint_path checkpoints/wav2lip.pth --face_det_batch_size 2 --wav2lip_batch_size 8 --face "../video/result.mp4" --audio "../audio/sound.mp3"`
![wac error 10](https://user-images.githubusercontent.com/71806009/94392735-0141cb80-0151-11eb-82c9-583a0e17d71e.PNG)

**Comment by echosvile** [comment]
![show error 1](https://user-images.githubusercontent.com/71806009/94392827-5251bf80-0151-11eb-87ad-d982e6f7576d.PNG)
and its still in the same directory as it was when it ran the other time

**Comment by prajwalkr** [comment]
Please google and figure out how to specify the audio and video paths correctly. I do not know how to specify this properly in Windows.

**Comment by echosvile** [comment]
ok i used this no and its running i hope and pray it doesnt give error again
`python inference.py --checkpoint_path checkpoints/wav2lip.pth --face_det_batch_size 2 --wav2lip_batch_size 8 --face video/result.mp4 --audio audio/sound.mp3`

**Comment by echosvile** [comment]
finally its done.
very big thank you to you @prajwalkr  and @Rudrabha 
Hat's off as i roll on the ground in thanks.
Bless you!
![success](https://user-images.githubusercontent.com/71806009/94393800-bffeeb00-0153-11eb-825e-3ce043ae012e.PNG)

**Comment by nishir53** [comment]
> i have installed ffmepg, changed the version of the torch in requirements to 1.1.2 and its all still giving me the same 'could not find a version that satisfies the requirements torch==1.1.0'
> 
> ![wav error 3](https://user-images.githubusercontent.com/71806009/94369822-eedd7880-00e3-11eb-9643-c027b9d9f30d.PNG) '

hi there can you tell which version of python you have used and if possible can you help us with this project , we have this same project and we are getting issues in installing dependencies and running it 

please please can you help?

**Comment by sahilg06** [comment]
@nishir53 Using python 3.9 and replacing all the == in req.txt with >= worked for me.

**Comment by nishir53** [comment]
@sahilg06 thanks but if you are free can we arrange google meet?

**Comment by nishir53** [comment]
also sir its taking too much time in loading
![Screenshot (54)](https://user-images.githubusercontent.com/101323193/162389715-2f466dde-1d54-442c-af83-98438432dfb8.png)

**Comment by nishir53** [comment]
@sahilg06 can you share your input video and input audio file please

**Comment by nishir53** [comment]
my files are having lot of frames
please can you share your input video and input audio file

**Comment by sahilg06** [comment]
@nishir53 you can download video/audio for inference from [here](https://bhaasha.iiit.ac.in/lipsync/)
