### ISSUE TITLE
about eval_model()

### ISSUE THREAD

**Issue by ZerRui** [Rudrabha/Wav2Lip#88]
May I ask why the step logic of the eval_model method of the color_syncnet_train.py and wav2lip_train.py files are different, and I look forward to your reply! thank!

**Comment by prajwalkr** [comment]
SyncNet is less compute-intensive than Wav2Lip. So, we can afford to run more evaluation steps for SyncNet by not wasting a lot of computing time.

**Comment by ZerRui** [comment]
What I mean is that if the amount of data is relatively small, for example, I only have 5 batches of data, then the eval logic eval_steps=1400 in SyncNet will not work at all. In fact, it will be over after only 4 steps.

**Comment by prajwalkr** [comment]
If you have only 5 batches then you would face serious difficulties in training the network. The network requires large amounts of data to train on. Nevertheless, You can reduce the eval steps in this case.
