### ISSUE TITLE
Audio features

### ISSUE THREAD

**Issue by QUTGXX** [Rudrabha/Wav2Lip#89]
I saw that you tried to extract audio features by 'mfcc'. When the voices are on mute, the mfcc features are -4. But I saw other feature extraction methods, the value would be changed to 0 or other values. Could you plz help me to address this issue?

**Comment by prajwalkr** [comment]
We use mel features. Are you talking about the mel features?

**Comment by QUTGXX** [comment]
> We use mel features. Are you talking about the mel features?

yes, I am said the mel features.

**Comment by prajwalkr** [comment]
The mel features are normalized between [-4, 4]. That is why you are getting -4.

**Comment by Mayur28** [comment]
Hi @prajwalkr , I just wanted to find out if there is any particular reason that the audio features were manually extracted (as opposed to using the built-in mel-spectrogram function from librosa or torchaudio). Are there any advantages achieved by manually extracting the features as it is done in the Wav2Lip code? 

Thanks.

**Comment by mushanshanshan** [comment]
@Mayur28 I also have this question, did you figure out that?

**Comment by Mayur28** [comment]
Hi @mushanshanshan , unfortunately I could not figure it out. Although, I tried using the built-in functions instead while keeping the hyperparameters the same (n_fft, hop, etc), however, the model did not converge. It seems that the model is very sensitive to the normalization method used.

**Comment by mushanshanshan** [comment]
@Mayur28 Got it! Thanks very much!
