### ISSUE TITLE
Help required on line #3 in Colab Notebook

### ISSUE THREAD

**Issue by chetancc** [Rudrabha/Wav2Lip#9]
Hi Sir,

Very interesting project :) 
I am getting below error on line 5 while executing colab notebook. I got below error - 
cp: cannot stat '/content/gdrive/My Drive/Wav2lip/wav2lip_gan.pth': No such file or directory

I tried to search wav2lip_gan.pth file but couldn't find...please suggest
Thanks in advance.

**Comment by prajwalkr** [comment]
Please make a copy of the Colab notebook, upload the checkpoint to your own google drive and then try again.

**Comment by chetancc** [comment]
Hi Sir / Prajwalkr, 
Thanks for reply. I have made copy of Wav2Lip_quick_trial.ipynb and when I click on play button for line 3, I get error
!cp -ri "/content/gdrive/My Drive/Wav2lip/wav2lip_gan.pth" /content/Wav2Lip/checkpoints/
cp: cannot stat '/content/gdrive/My Drive/Wav2lip/wav2lip_gan.pth': No such file or directory

It looks like it is looking for wav2lip_gan.pth Also please explain what do you mean by upload the checkpoint to your own google drive

Please find below screenshot for more information.
![image](https://user-images.githubusercontent.com/17129451/91755135-3dcce680-ebe8-11ea-8521-e3de343aecfe.png)

**Comment by prajwalkr** [comment]
> Also please explain what do you mean by upload the checkpoint to your own google drive

Google Colab accesses files from your Google Drive. If you upload the checkpoint to your Google Drive, you can access them via Colab.

**Comment by prajwalkr** [comment]
Please re-open if the issue is not resolved.
