### ISSUE TITLE
How many content hours needed to improve results on the particular dictor?

### ISSUE THREAD

**Issue by crankyz** [Rudrabha/Wav2Lip#90]

**Comment by prajwalkr** [comment]
Please explain the question.

**Comment by crankyz** [comment]
> Please explain the question.

I wanna make wav2lip video with myself, but on the provided weights i've got not very clearly results. So if I will train on my videoset your network, how many hours of video I need to get good results?_

**Comment by prajwalkr** [comment]
https://github.com/Rudrabha/Wav2Lip#training-on-datasets-other-than-lrs2
