### ISSUE TITLE
Advice on sync correcting videos

### ISSUE THREAD

**Issue by dipam7** [Rudrabha/Wav2Lip#91]
The training tips suggest that we should sync-correct videos. Can you suggest a good way to figure out if a video really needs it and some library to do that?
Thanks

**Comment by prajwalkr** [comment]
You can use this: https://github.com/joonson/syncnet_python

**Comment by dipam7** [comment]
Can you help me understand how to use the link you've attached to sync correct videos? I couldn't understand it

**Comment by prajwalkr** [comment]
You can first compute the offset value using the instructions in the readme and shift the video forward/backward by that many frames.

**Comment by dipam7** [comment]
Is the frame shifting done by ffmpeg? I cannot find the right command to do that

**Comment by prajwalkr** [comment]
You can use cv2 to read the video and write back another video with shifted frames.

**Comment by QUTGXX** [comment]
> You can first compute the offset value using the instructions in the readme and shift the video forward/backward by that many frames.

Hi, I tried to compute the offset value using `syncnet_python`. And I got the following values such as -1, -3, and 3. Could u plz tell me what does it mean and how to work out these values?

![image](https://user-images.githubusercontent.com/36947214/98195037-c440d400-1f5b-11eb-9dbd-d27016c3bd6c.png)

**Comment by prajwalkr** [comment]
It means the audio and video are shifted forward (backward) in time by that many frames. What you need to do is load the videos in OpenCV and write back the videos by shifting the video frames by that offset amount.

**Comment by QUTGXX** [comment]
> It means the audio and video are shifted forward (backward) in time by that many frames. What you need to do is load the videos in OpenCV and write back the videos by shifting the video frames by that offset amount.

Does it mean that if the value is larger than zero, we should shift forward?

**Comment by prajwalkr** [comment]
I have forgotten which positive is forward or if negative is forward. You can shift in one direction and compute that offset again on the shifted video and see if you have corrected it.

**Comment by QUTGXX** [comment]
> I have forgotten which positive is forward or if negative is forward. You can shift in one direction and compute that offset again on the shifted video and see if you have corrected it.

Thanks for your quick reply. Actually, I am a freshman in this area. Can u share some code about shifting frames with OpenCV to diminsh the offset value?

**Comment by hannarud** [comment]
You can do it with ffmpeg.
I find this comment to be very suitable here:
https://github.com/Rudrabha/Wav2Lip/issues/354#issuecomment-1161817296
Providing it just for reference:

`ffmpeg -y -i <video> -itsoffset <shift> -i <video> -ss <shift> -t <full duration of video - abs(shift)> -map 0:v -map 1:a <new output>`
Here, `shift = AV offset / FPS`

`AV offset` is in terms of number of frames. `shift` (above) will get you to seconds.

**Comment by EhsanRusta** [comment]
Thanks for your responses,
I tried suggested sync correction, and measure the offset and shift the video, but after applying shift the new offset is not zero and is sth else, and the video has delay or forwarded audio respect to the face, 
what is the problem? (the video is from youtube)

**Comment by devsvarun** [comment]
How do I calculate the shift. After randomly trying some values, the offset still doesn't get close to 1.

**Comment by devsvarun** [comment]
> Thanks for your responses, I tried suggested sync correction, and measure the offset and shift the video, but after applying shift the new offset is not zero and is sth else, and the video has delay or forwarded audio respect to the face, what is the problem? (the video is from youtube)

Did you find any solution to this?

**Comment by rainbowoldhorse** [comment]
> You can use cv2 to read the video and write back another video with shifted frames.

Hello, bro, do you mean that I first train a syncnet using an original dataset, then use the trained model to perform offset correction on the video, and then use the corrected video to retrain the syncnet?

**Comment by jinqinn** [comment]
@prajwalkr  should i shuffle all sync corrected videos?
