### ISSUE TITLE
Problem in calculating metrics: No module named 'SyncNetModel'

### ISSUE THREAD

**Issue by avisekiit** [Rudrabha/Wav2Lip#92]
Dear Authors,

Thanks for the awesome repo. So, I was trying to use your evaluation codes to get the LSE-D and LSE-C metrics and I think
evaluation/scores/calc_scores_syncnet.py might be the right code for that ?
So, I changed my directory to evaluation/scores/ and then executed
`python calc_scores_syncnet.py --data_root=path/to/mp4/files`

However I get the error:
`Traceback (most recent call last):
  File "calc_scores_syncnet.py", line 9, in <module>
    from SyncNetInstance_calc_scores import *
  File "/data/Wav2Lip/evaluation/scores/SyncNetInstance_calc_scores.py", line 13, in <module>
    from SyncNetModel import *
ModuleNotFoundError: No module named 'SyncNetModel'
`
Do you suggest linking some paths before we can get the metrics calculations code to be working ? Or if you can suggest a command line to run the metrics generation code?

Looking forward to your thoughts.

Thanks,
Avisek

**Comment by Rudrabha** [comment]
We will be updating the instructions shortly.

**Comment by avisekiit** [comment]
Hi @Rudrabha 
Thanks for your fast reply. I will keenly look forward to the instructions for getting the metrics.

We are submitting a lip-sync kind of work to a conference very soon and recently came across your paper. So, it will be really awesome to compare with your work and ourselves being able to run the evaluation metrics.

Thanks,
Avisek

**Comment by avisekiit** [comment]
Dear Authors,
I know you must be working hard towards refining the repo further.
Actually, we are planning to submit to a graphics conference this week and would have dearly loved to use the evaluation metrics/protocols of your paper.
Thus keenly waiting to get some pointers (can be some hacky suggestions also as of now) to get the test time LSE-D and LSE-C metrics for a testing video. 

Apologies for requesting you so frequently.

Regards,
Avisek

**Comment by Rudrabha** [comment]
Hello,

We have updated the instructions inside the evaluation folder. Please follow them and see if you can get the scores. In case, you face any difficulty please revert back. For your own video, you need to use the script for the evaluation of real videos (there is one specifically for lrs2, lrs3, and lrw videos since they don't require a preprocessing step). 

All the best for the conference (EUROGRAPHICS I suppose) :)

**Comment by avisekiit** [comment]
Hi @Rudrabha 
Thanks for updating the evaluation code. I could get it working by some subtle corrections here and there.
There were some issues with paths mentioned in your .sh file- seems like it was written according to some local folder which you were using.
Thanks a lot again !! Yes, it was for EUROGRAPHICS !!!!


Just one additional doubt: I was trying the online demo. But if I press on "sync this pair", I seem the video window coming up, but nothing is displayed. I can't also download the generated video. See attached screenshot.
Is there any issue at your background while processing the videos ? I am using Chrome browser.



![Screenshot 2020-10-08 at 8 58 29 PM](https://user-images.githubusercontent.com/12903678/95480161-33e99080-09a9-11eb-85c2-46420824b168.png)

**Comment by Rudrabha** [comment]
I think the video is not getting generated because the face is not getting detected or some similar issue. You can try once with our code directly.

**Comment by prajwalkr** [comment]
> Thanks for updating the evaluation code. I could get it working by some subtle corrections here and there.
> There were some issues with paths mentioned in your .sh file- seems like it was written according to some local folder which you were using.

Thanks for letting us know, we will correct these in a few days or so. 

> Yes, it was for EUROGRAPHICS !!!!

Haha! All the best :) 

> I seem the video window coming up, but nothing is displayed. I can't also download the generated video.

Can you try with the pairs given? Can you download them to your machine and upload them into those fields and see if you get a result?

**Comment by avisekiit** [comment]
Hi @Rudrabha 
Thanks for your reply. Yes, initially I thought face detection might be an issue.
But even the demo video-audio pairs manifest similar issues- i.e output video is not being generated or can be downloaded. 
In fact, the input video columns itself are blank.
Are you also noticing similar issues when you open in your Chrome browser ?

Here is the snip of the demo page with the video-audio pairs released by you.
![Screenshot 2020-10-11 at 1 13 13 AM](https://user-images.githubusercontent.com/12903678/95663719-178f5480-0b5f-11eb-8394-7951c1ef7a44.png)

**Comment by Rudrabha** [comment]
Our server is down for some reason. You can use the code/google colab to generate results. Sorry for the inconvenience caused.

**Comment by avisekiit** [comment]
Hi,

I understand that the online demos might be affected by the servers. I was also trying to run the Colab. I could run a small audio and video pair.
However, when I am trying to use an audio and video pair of about 15-20 secs duration, I get a message of 
"Past duration * is too large".

Here is a snip below. Do you feel there is some upper bound on the length of video-audio pairs that can be handled by the Colab?
![Screenshot 2020-10-15 at 7 52 00 PM](https://user-images.githubusercontent.com/12903678/96142992-4a02ce00-0f20-11eb-8ecd-fba79c17bc86.png)

**Comment by aithasahith02** [comment]
```
(wave2lip) C:\Users\hp\w2p\Wav2Lip-master\Wav2Lip-master>pyt
hon inference.py --checkpoint_path checkpoints/wav2lip.pth -
-face input_video.mp4 --audio input_audio.wav
Traceback (most recent call last):
  File "C:\Users\hp\w2p\Wav2Lip-master\Wav2Lip-master\inference.py", line 16, in <module>
    from batch_face import RetinaFace
ModuleNotFoundError: No module named 'batch_face'

(wave2lip) C:\Users\hp\w2p\Wav2Lip-master\Wav2Lip-master>

```
I am getting this error. Can anyone help me. Thank you .

**Comment by wwdok** [comment]
Does this issue really solved ? I sitll did not see the SyncNetModel module
