### ISSUE TITLE
Some problems of model training

### ISSUE THREAD

**Issue by guoxinlei1911** [Rudrabha/Wav2Lip#93]
Sorry for my poor English.
I have prepared a 1080p data set. The training result is not ideal, and the lip part is still fuzzy. How can I change the code to adjust FPS and img_ size training more HD model?

**Comment by prajwalkr** [comment]
You need to change the model architecture to accommodate more high-resolution faces.

**Comment by guoxinlei1911** [comment]
> 您需要更改模型架構，以容納更多高分辨率的面孔。

Does the neural network need to be changed?

**Comment by guoxinlei1911** [comment]
> You need to change the model architecture to accommodate more high-resolution faces.

Does the neural network need to be changed?

**Comment by prajwalkr** [comment]
Yes. It currently accepts 96x96 faces only. You need to change that.

**Comment by guoxinlei1911** [comment]
> Yes. It currently accepts 96x96 faces only. You need to change that.

Thank you for your answer
