### ISSUE TITLE
Higher resolution and Docker

### ISSUE THREAD

**Issue by brazilgithub** [Rudrabha/Wav2Lip#95]
Has anyone trained a model in higher resolution? Is it possible to create a Wav2Lip Docker and make it available for download?

**Comment by prajwalkr** [comment]
> Has anyone trained a model in higher resolution?

This is a work in progress.



> Is it possible to create a Wav2Lip Docker and make it available for download?

We are not planning to do that at the moment.

**Comment by dipam7** [comment]
> This is a work in progress.
> 
> >

Are you attempting to train a high res model?

**Comment by prajwalkr** [comment]
Yes.

**Comment by dipam7** [comment]
> Yes

Any updates on this?

**Comment by 649459021** [comment]
Is there a proper HD dataset? thx
