### ISSUE TITLE
Issue with FPS variable.

### ISSUE THREAD

**Issue by jev217** [Rudrabha/Wav2Lip#96]
Hello I have recently been trying to learn how to start using this library, I've got my environment working on Python 3.7, Debian.  All requirements installed as well as the pth file being in the correct position.  One thing I'm noticing is I keep getting errors over FPS.  The first few times I would get errors stating that FPS was 0 causing for a error to be raised now I'm getting a error stating that the FPS variable hasn't been declared yet.  Both retraining to the line 233 inside of the inference file.  Below is the present error I'm getting speaking of the variable not being declared yet:
`Traceback (most recent call last):
  File "inference.py", line 281, in <module>
    main()
  File "inference.py", line 233, in main
    mel_idx_multiplier = 80./fps
UnboundLocalError: local variable 'fps' referenced before assignment`
Thinking this might be attributed to the FPS variable being 0 I did try doing a try/except statement to use the one that can be passed via command line arguments but the error still remains.

If you need any additional information please let me know.

**Comment by prajwalkr** [comment]
Please download the latest code and run the inference command mentioned in the readme. Let me know if it causes the same error.
